### ISSUE TITLE
Two dictionaries are not the same

### ISSUE THREAD

**Issue by ray1919** [lindenb/jvarkit#102]
### Subject of the issue
two bam file using same aligner(minimap2) and same index file, when using bamstats04, it had error of "Two dictionaries are not the same"

### Your environment
* version of jvarkit: 36ee99261b96d93f02bc270a53156300dd11548d
* version of java 1.8
* which OS Ubuntu 16.04

### Steps to reproduce
two bam file using same aligner(minimap2) and same index file, when using bamstats04, it had error of "Two dictionaries are not the same"

### Expected behaviour
I use samtools view -H to output header of two bam files, only RG and PG lines are differnet

### Actual behaviour
It out put two string of chrom names, I copied the two very long string, and compared them in text editor. It was exactly the same.

**Comment by ray1919** [comment]
I have comment out the error code in source file , and it works. Is there a better solution.

**Comment by lindenb** [comment]
thanks for the bug report, I can reproduce the problem when using two bams.

**Comment by lindenb** [comment]
fixed in https://github.com/lindenb/jvarkit/commit/8e4e28a5390bafe9c401dfc075109905d6606794

thanks for the bug report

closing.
