### ISSUE TITLE
msa2vcf

### ISSUE THREAD

**Issue by vinay104** [lindenb/jvarkit#105]
Hello, 

i am vinay lkumar reddy nannuru, i want to convert a fasta alignment file into vcf. I installed jvarkit and when i follow the next steps like make msa3vcf, it gives following error. 

" vinay410@server230:jvarkit > make msa2vcf
mkdir -p /storage2/active/nvinay/mthesis/jvarkit/dist/ 
rm -rf "/storage2/active/nvinay/mthesis/jvarkit/_tmp-2.15.0"
mkdir -p /storage2/active/nvinay/mthesis/jvarkit/_tmp-2.15.0/META-INF/services
echo "com.github.lindenb.jvarkit.annotproc.JVarkitAnnotationProcessor" > /storage2/active/nvinay/mthesis/jvarkit/_tmp-2.15.0/META-INF/services/javax.annotation.processing.Processor
echo '### Printing javac version : it should be Oracle 1.8 (NOT OpenJDK). if Not, check your $${PATH}.'
### Printing javac version : it should be Oracle 1.8 (NOT OpenJDK). if Not, check your $${PATH}.
javac -version
javac 1.6.0_41
#compile
javac -d /storage2/active/nvinay/mthesis/jvarkit/_tmp-2.15.0 -sourcepath /storage2/active/nvinay/mthesis/jvarkit/src/main/java:/storage2/active/nvinay/mthesis/jvarkit/src/main/generated-sources/java /storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:84: illegal start of expression
			map(C->C.getName()).
			      ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:169: illegal start of expression
			filter(E->E.getKind()==ElementKind.CLASS).
			         ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:170: illegal start of expression
			filter(E-> E.getAnnotation(IncludeSourceInJar.class) !=null).
			         ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:171: illegal start of expression
			forEach(E->{					
			          ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:171: illegal start of expression
			forEach(E->{					
			           ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:171: ';' expected
			forEach(E->{					
			            ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:172: not a statement
				if( thisDir==null || thisDir.isEmpty()) return;
				  ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:172: ';' expected
				if( thisDir==null || thisDir.isEmpty()) return;
				                                       ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:174: illegal start of type
				});
				 ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:180: <identifier> expected
		roundEnv.getElementsAnnotatedWith(Program.class).stream().
		                                 ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:180: <identifier> expected
		roundEnv.getElementsAnnotatedWith(Program.class).stream().
		                                          ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:180: ';' expected
		roundEnv.getElementsAnnotatedWith(Program.class).stream().
		                                                ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:182: illegal start of type
			filter(E->{final Program prog=E.getAnnotation(Program.class); return prog!=null && prog.generate_doc();}).
			                                                                                                        ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:182: ';' expected
			filter(E->{final Program prog=E.getAnnotation(Program.class); return prog!=null && prog.generate_doc();}).
			                                                                                                         ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:183: invalid method declaration; return type required
			forEach(E->{
			^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:183: <identifier> expected
			forEach(E->{
			         ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:183: ';' expected
			forEach(E->{
			          ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:233: illegal start of expression
									map(T->"["+T.getAccession()+"]"+T.getLabel()).
									      ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:294: illegal start of type
				});
				 ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:295: illegal start of type
		return true;
		^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:295: ';' expected
		return true;
		      ^
/storage2/active/nvinay/mthesis/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java:300: class, interface, or enum expected
}
^
22 errors
make: *** [/storage2/active/nvinay/mthesis/jvarkit/dist/annotproc.jar] Error 1
vinay410@server230:jvarkit > "

Can someone help me out of this issue and also what is  the usage for msa2vcf to convert a fasta to vcf format.

Thanks,
Vinay

**Comment by lindenb** [comment]
The problem is clearly displayed, in the first lines:

```
Printing javac version : it should be Oracle 1.8 (NOT OpenJDK). if Not, check your $${PATH}.

javac -version
javac 1.6.0_41
```
