### ISSUE TITLE
Errors installing Bam2Raster tool 

### ISSUE THREAD

**Issue by xiucz** [lindenb/jvarkit#106]
### Your environment
* version of jvarkit : 
* version of java : 
```
$ java -version
$ openjdk version "1.8.0_65"
```
* the value of `${JAVA_HOME}`
```
$ whereis javac
$ javac: /usr/bin/javac /usr/share/man/man1/javac.1.gz
```

* which OS:
```
Linux version 3.10.0-327.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) 
```
### Subject of the issue
Hi,
I want to use the **bam2raster** tool to visualize my bam files, but I get struck in installing it:
```
cd jvarkit && make bam2raster
```
, and I get this error:
```
～/software/jvarkit/src/main/java/com/github/lindenb/jvarkit/util/Hershey.java:51: error: package javafx.scene.canvas does not exist
import javafx.scene.canvas.GraphicsContext;
                          ^
～/software/jvarkit/src/main/java/com/github/lindenb/jvarkit/util/Hershey.java:277: error: cannot find symbol
			final GraphicsContext g,
			      ^
  symbol:   class GraphicsContext
  location: class Hershey
2 errors
make: *** [bam2raster] Error 1
[zhangbo@ln01 jvarkit]$ make
This  is the top target. Run 'make name-of-target' to build the desired target. Run 'make all' if you're Pierre Lindenbaum. See http://lindenb.github.io/jvarkit/  for a list of the available tools.
```
Can you show me how to solve it ? 
Thanks a lot. ^_^

**Comment by lindenb** [comment]
> http://lindenb.github.io/jvarkit/Bam2Raster.html
>
> java compiler SDK 1.8 (NOT the old java 1.7 or 1.6, not the new 1.9) and avoid OpenJdk, use the java from Oracle

you're not using the **oracle** version of java. Distributions of java like openjdk are missing some packages. 

I'm closing this one.
