### ISSUE TITLE
biostar214299 handles some of the soft clipped reads incorrectly 

### ISSUE THREAD

**Issue by Glombas** [lindenb/jvarkit#108]
### Subject of the issue
Some of the soft clipped reads get assigned the "UNAFFECTED" tag or get assigned to a different group according to SNP located on that position no matter if the clipped part overlaps the SNP or not. 

Please find a SAM and a BED file in attachment along with a list of suspicious reads
[bug.zip](https://github.com/lindenb/jvarkit/files/2269934/bug.zip)

### Your environment
* version of jvarkit
* version of java: java version "1.8.0_181"
* the value of `${JAVA_HOME}`
* which OS: Ubuntu 16.04.4 LTS (64 bit)

**Comment by lindenb** [comment]
thank you for the bug report, you were right about the clipping. I've changed things : https://github.com/lindenb/jvarkit/commit/8369e8d0f456428c37a255c1ea1696332c2cd8ef ; does it work now ?

**Comment by Glombas** [comment]
Yes, now it works perfectly fine. Thank you very much!
