### ISSUE TITLE
Can sam4weblogo output the read quality in the aligned fastq file, instead of a fasta file.

### ISSUE THREAD

**Issue by yech1990** [lindenb/jvarkit#109]
`sam4weblogo` is a powerful tool for generate msa file from bam file.

Sometime, I need to filter the msa file with phread quality of each base. Can `sam4 weblogo` generate a fastq file with read quality as output?

**Comment by lindenb** [comment]
I added a new option '-q' to genrate fastq format. Can you tell me if it's working ?

**Comment by yech1990** [comment]
https://github.com/lindenb/jvarkit/pull/110
