### ISSUE TITLE
does Sam2Tsv only print out variants but no perfect matches?

### ISSUE THREAD

**Issue by Huanle** [lindenb/jvarkit#111]
Hi  Pierre,

thanks for developing sam2tsv.
Just a quick question about the ouput.
It seems sam2tsv only output varaints (SNP and indels) but not perfect matches.
Is this correct?

Will it be possible to let it generate reads the perfectly matched to reference at a given position.

Thanks,
Huanlee

**Comment by lindenb** [comment]
>  It seems sam2tsv only output varaints (SNP and indels) but not perfect matches.

no, it prints everything.


```
$ java -jar dist/sam2tsv.jar -A  \
    -r samtools-0.1.18/examples/toy.fa 
      samtools-0.1.18/examples/toy.sam
r001	163	ref	0	T	.	7	T	M
r001	163	ref	1	T	.	8	T	M
r001	163	ref	2	A	.	9	A	M
r001	163	ref	3	G	.	10	G	M
r001	163	ref	4	A	.	11	A	M
r001	163	ref	5	T	.	12	T	M
r001	163	ref	6	A	.	13	A	M
r001	163	ref	7	A	.	14	A	M
```

**Comment by Huanle** [comment]
@lindenb 
sorry. i mistaken it with the output from another program. :(
thanks.
