### ISSUE TITLE
bamstats05 ERROR : error msg : Exited with failure (-1) 

### ISSUE THREAD

**Issue by Vithyanatarajan** [lindenb/jvarkit#113]
### Verify
* Java 10.0.2

### Subject of the issue
Error on running bamstats05
Getting the error  as 
bamstats05 Exited with failure (-1)

### Your environment
* version of jvarkit    -  latest version
* version of java 10.0.2
* the value of `${JAVA_HOME}` -   /home/vithya/Downloads/jdk1.8.0_191/
* linux

### Steps to reproduce
Command used 

_java -jar dist/bamstats05.jar --bed ~/Documents/Variant_caller/freebayes/TruSeq_exome_targeted_regions.hg19.4col.bed ~/Documents/Variant_caller/freebayes/Santhi_fastq.bam --strandmost opposite -o output.txt_

### Actual behaviour

obtained error result

[SEVERE][BamStats05]overlapping region: chr11	64008603	64008710	FKBP2 and chr11:64008413-64008604	+	.
java.io.IOException: overlapping region: chr11	64008603	64008710	FKBP2 and chr11:64008413-64008604	+	.
	at com.github.lindenb.jvarkit.tools.bamstats04.BamStats05.readBedFile(BamStats05.java:161)
	at com.github.lindenb.jvarkit.tools.bamstats04.BamStats05.doWork(BamStats05.java:329)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:1145)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:1303)
	at com.github.lindenb.jvarkit.tools.bamstats04.BamStats05.main(BamStats05.java:406)
[INFO][Launcher]bamstats05 Exited with failure (-1)

**Comment by lindenb** [comment]
as the message said your bed file contains two overlapping regions which is forbidden to compute the coverage for one gene.

**Comment by Vithyanatarajan** [comment]
Hi @lindenb 
> as the message said your bed file contains two overlapping regions which is forbidden to compute the coverage for one gene.
       Thank you for your explanation. I removed the overlapping region and ran,analysis got completed successfully.

          And one query 
               May I know how to use more than one bam file. As I want to run for normal and tumor bam in a single command.

**Comment by lindenb** [comment]
> May I know how to use more than one bam file. As I want to run for normal and tumor bam in a single command.

yes there will be one line per bam/segment

closing
