### ISSUE TITLE
SAM2TSV OUTPUT: reference position is not always 0-based?

### ISSUE THREAD

**Issue by Huanle** [lindenb/jvarkit#114]
Hi There,

It seems in the output of sam2tsv. the coordinates of reference sequence are not always 0-based.

here are a couple of examples:

1) 0- based 
![image](https://user-images.githubusercontent.com/909201/47781227-80c48700-dcfd-11e8-807b-2ecbf09dde73.png)
python string slicing validation:
![image](https://user-images.githubusercontent.com/909201/47781257-95088400-dcfd-11e8-8535-6e55df3daad6.png)

2) 1-based
![image](https://user-images.githubusercontent.com/909201/47781284-a8b3ea80-dcfd-11e8-9df0-7635f5eb90e1.png)

 python string slicing validation
![image](https://user-images.githubusercontent.com/909201/47781312-b2d5e900-dcfd-11e8-8f58-b6b3c6b8273a.png)

can you let me know what caused this?
Best

**Comment by lindenb** [comment]
reference sequence is 1-based.

**Comment by Huanle** [comment]
@lindenb thanks a lot for your quick response.
 sorry i uploaded the wrong example.

here is a 1-based example.

![refpos-0-based](https://user-images.githubusercontent.com/909201/47781982-64c1e500-dcff-11e8-844b-b0b43bbf4408.png)

![refpos-0-based-string](https://user-images.githubusercontent.com/909201/47781994-6d1a2000-dcff-11e8-8085-dec0690db44d.png)

**Comment by Huanle** [comment]
@lindenb 
Sorry i confused myself with conversion between 0- based read position and 1-based reference base position :( .
