### ISSUE TITLE
advice about a program similar to blast2snp for tblastn results

### ISSUE THREAD

**Issue by rbatorsky** [lindenb/jvarkit#118]
Hi,  I've been using blastn2snp for converting blastn inputs to snp, I'm wondering if you are aware of any tool that can do the same for tblastn outputs. The goal is to create a list of amino acid substitutions.
Thanks for the helpful toolkit!

**Comment by lindenb** [comment]
> I'm wondering if you are aware of any tool that can do the same for tblastn outputs.

not as far as I know, you should ask biostars.org or bioinformatics.stackexchange.com

**Comment by rbatorsky** [comment]
Thanks very much for your response. I've found a solution using biopython.
