### ISSUE TITLE
javax.annotation does not exist

### ISSUE THREAD

**Issue by DavideGue** [lindenb/jvarkit#120]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

### Subject of the issue
vcffilterjdk error

### Your environment
* version of jvarkit: available at 13/02/2019
* version of java: OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
* the value of `${JAVA_HOME}`: /DATA/utenza1/jdk-11.0.2 added to PATH using export PATH=$PATH:/DATA/utenza1/jdk-11.0.2/bin
* which OS: Distributor ID: Ubuntu
                   Description:    Ubuntu 16.04.2 LTS
                   Release:        16.04
                   Codename:       xenial

### Steps to reproduce
Tell us how to reproduce this issue. Please provide an example.

### Expected behaviour
Obtaining a vcf filtered by allele balance

### Actual behaviour
No output is produced:
when I invoke vcffilterjdk with the following command: java -jar vcffilterjdk.jar -f prova.js -o output.vcf 151_sample_solo_variant_site_blp.vcf, where prova.js has been copied from https://www.biostars.org/p/319148/ I get the follow:
[DEBUG][VcfFilterJdk] Compiling :
         1  import java.util.*;
         2  import java.util.stream.*;
         3  import java.util.function.*;
         4  import htsjdk.samtools.util.*;
         5  import htsjdk.variant.variantcontext.*;
         6  import htsjdk.variant.vcf.*;
         7  @javax.annotation.Generated(value="VcfFilterJdk",date="2019-02-15T14:34:39+0100")
         8  public class VcfFilterJdkCustom811031656 extends com.github.lindenb.jvarkit.tools.vcffilterjs.VcfFilterJdk.AbstractFilter {
         9    public VcfFilterJdkCustom811031656(final VCFHeader header) {
        10    super(header);
        11    }
        12    @Override
        13    public Object apply(final VariantContext variant) {
        14     /** user's code starts here */
        15  return new VariantContextBuilder(variant).
        16  genotypes(
        17      variant.
        18      getGenotypes().
        19      stream().
        20      map( G->{
        21          if(G.hasAD()) {
        22              if(!G.isHet()) return G;
        23              final int A[]= G.getAD();
        24              if(A.length>1 &&  A[0]>0 && A[1]/(double)A[0]> 0.33) return G;
        25              }
        26          return  GenotypeBuilder.createMissing(G.getSampleName(),2);
        27          }).
        28      collect(Collectors.toList())
        29      ).
        30  make();
        31  /** user's code ends here */
        32     }
        33  }
/tmp/jvarkit1045150881693312448.tmp/VcfFilterJdkCustom811031656.java:7: error: package javax.annotation does not exist
@javax.annotation.Generated(value="VcfFilterJdk",date="2019-02-15T14:34:39+0100")
                 ^
1 error
[SEVERE][VcfFilterJdk]java.lang.RuntimeException: Cannot compile
java.lang.RuntimeException: java.lang.RuntimeException: Cannot compile
        at com.github.lindenb.jvarkit.lang.OpenJdkCompiler$DefaultOpenJdkCompiler.compileClass(OpenJdkCompiler.java:255)
        at com.github.lindenb.jvarkit.tools.vcffilterjs.VcfFilterJdk$CtxWriterFactory.initialize(VcfFilterJdk.java:722)
        at com.github.lindenb.jvarkit.tools.vcffilterjs.VcfFilterJdk.doWork(VcfFilterJdk.java:822)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:736)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:894)
        at com.github.lindenb.jvarkit.tools.vcffilterjs.VcfFilterJdk.main(VcfFilterJdk.java:841)
Caused by: java.lang.RuntimeException: Cannot compile
        at com.github.lindenb.jvarkit.lang.OpenJdkCompiler$DefaultOpenJdkCompiler.exec(OpenJdkCompiler.java:180)
        at com.github.lindenb.jvarkit.lang.OpenJdkCompiler$DefaultOpenJdkCompiler.compileClass(OpenJdkCompiler.java:232)
        ... 5 more
[SEVERE][VcfFilterJdk]Cannot initialize
[INFO][Launcher]vcffilterjdk Exited with failure (-1)

**Comment by lindenb** [comment]
I suspect it's a problem with different versions of java on your computer what are the extact outputs of 
```
javac -version
java -version
```

furthermore, you should set

`export PATH=DATA/utenza1/jdk-11.0.2/bin:$PATH`

not

`export PATH=$PATH:/DATA/utenza1/jdk-11.0.2/bin`

---

furthmore, try

`/DATA/utenza1/jdk-11.0.2/bin/java -jar  vcffilterjdk.jar -f prova.js -o output.vcf`

**Comment by DavideGue** [comment]
These are the versions you requested:
javac -version
javac 11.0.2
java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

moreover I tried all your suggestions and invoking vcffilters in the way you indicated it looks working halthough several warnings have been generated:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by htsjdk.samtools.util.CloserUtil (file:/DATA/utenza1/jvarkit/dist/vcffilterjdk.jar) to method com.sun.xml.internal.stream.XMLEventReaderImpl.close()
WARNING: Please consider reporting this to the maintainers of htsjdk.samtools.util.CloserUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[WARN][SnpEffPredictionParser]no INFO[EFF] or no description. This VCF was probably NOT annotated with SnpEff (old version). But it's not a problem if this tool doesn't need to access SnpEff Annotations.
[WARN][VepPredictionParser]NO INFO[CSQ] found in header. This VCF was probably NOT annotated with VEP. But it's not a problem if this tool doesn't need to access VEP Annotations.
[WARN][AnnPredictionParser]no INFO[ANN] or no description This VCF was probably NOT annotated with SnpEff(ANN version) . But it's not a problem if this tool doesn't need to access SnpEff Annotations.
[INFO][VcfFilterJdk]done: N=108

thank you very much for your time and help
Davide

**Comment by lindenb** [comment]
```
javac -version
javac 11.0.2
java -version
openjdk version "1.8.0_191"
```

so you compiled with a modern java compiler (java 11) but you're trying to execute with an old java (8).

the warnings are ok.

I'm closing this one.
