### ISSUE TITLE
samextractclip not working on Minimap2 SAM file

### ISSUE THREAD

**Issue by MaestSi** [lindenb/jvarkit#121]
Dear jvarkit developer,
I am trying to use a combination of pcrclipreads.jar and samextractclip.jar to extract only the non-soft-clipped portion of ONT (single-end) reads mapped to a reference with Minimap2 aligner.
Following your suggestions in https://www.biostars.org/p/147136/ I was able to obtain a SAM file where the CIGAR flag reports the soft-clipping as I wanted.
However, when trying to extract only the non-soft-clipped portion of mapped reads, I get no output.
These are the commands that I ran:

```
echo -e "contig_1\t10\t100" > test.bed
java -jar /home/simone/software/jvarkit/dist/pcrclipreads.jar -B test.bed BC01.bam | samtools view -q 1 -F 4 -bu | samtools sort - > clipped.bam
samtools index clipped.bam
samtools view -h clipped.bam > clipped.sam
java -jar /home/simone/software/jvarkit/dist/samextractclip.jar -c clipped.sam
```

Everything seems to work fine unitl the last samextractclip.jar step, which gives error:
> [INFO][SamExtractClip]writing to stdout
> [INFO][SamExtractClip]Reading from clipped.sam
> [SEVERE][SamExtractClip]String index out of range: 11
> java.lang.StringIndexOutOfBoundsException: String index out of range: 11
>         at java.lang.String.substring(String.java:1963)
>         at com.github.lindenb.jvarkit.tools.structvar.SamExtractClip.run(SamExtractClip.java:243)
>         at com.github.lindenb.jvarkit.tools.structvar.SamExtractClip.doWork(SamExtractClip.java:185)
>         at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:736)
>         at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:894)
>         at com.github.lindenb.jvarkit.tools.structvar.SamExtractClip.main(SamExtractClip.java:301)
> [INFO][Launcher]samextractclip Exited with failure (-1)
> 

I am using Ubuntu 14.04.4 and this is the Java version:

> openjdk version "1.8.0_152-release"
> OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
> OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)

Thanks in advance,
Simone

**Comment by lindenb** [comment]
thanks for the report, could you please attach the output of 

```
samtools view BC01.bam contig_1:10-100 > error.sam
```

to this issue.

**Comment by MaestSi** [comment]
I moved it to error.txt, since Github only supports some formats.
[error.txt](https://github.com/lindenb/jvarkit/files/2888176/error.txt)
However, I realised the problem was given by the fact that BC01.bam contained fasta reads mapped to the reference, and not fastq reads.
When trying to do the same with a bam file obtained mapping fastq reads, everything when smooth.
So I guess the problem was given by the fact I expected the output being fastq, eventually without quality scores, while the program crashes if it doesn't find quality scores.
Is it expected that the bam file must be obtained mapping fastq reads instead of fasta?
Thanks

**Comment by lindenb** [comment]
> I moved it to error.txt, since Github only supports some formats.

thanks but i cannot use that file because the sam   header is missing. (you need to use the option `-h` of samtools )

> So I guess the problem was given by the fact I expected the output being fastq, eventually without quality scores, while the program crashes if it doesn't find quality scores.

yes, I don't think I managed to use the fact that the quality string is missing. But it's something that can be fixed (or I can print a warning )

**Comment by MaestSi** [comment]
Here it is.
[error.txt](https://github.com/lindenb/jvarkit/files/2888258/error.txt)
Thanks.

**Comment by lindenb** [comment]
I modified samextractclip so it creates a fake quality string (with `#`) if it is missing in the bam. https://github.com/lindenb/jvarkit/commit/64f1068dd3106754eae22a8a6d1027fc935ba759

it seems to works on my side, tell me if it's ok

**Comment by MaestSi** [comment]
Thanks, I've tried it out and it works as expected!
Simone
