### ISSUE TITLE
An exception in running sam2tsv.jar

### ISSUE THREAD

**Issue by weir12** [lindenb/jvarkit#122]
### Verify
* openjdk version **"11.0.2" 2019-01-15**

### Subject of the issue
An exception in running sam2tsv.jar

### Your environment
* version of jvarkit:  **64f1068d**
* version of java:  **openjdk version "11.0.2" 2019-01-15
                            OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
                            OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)**
* the value of `${JAVA_HOME}`：**/home/weir/softwave_packages/jvm/jdk-11.0.2**
* which OS: **CentOS release 6.5 (Final)**

### Steps to reproduce
1.First,I have arabidopsis transcriptome file (**Araport11_genes.201606.cdna.fasta**),picard SequenceDictionary result(**Araport11_genes.201606.cdna.dict**),samtools index result(**Araport11_genes.201606.cdna.fasta.fai**).and **sorted.bam file** (Be generated by minimap2 aligner and view/sorted/index by samtools).

2.Then,I was running command:`java -jar /home/weir/Epinano/jvarkit/dist/sam2tsv.jar  -r  ./Araport11_genes.201606.cdna.fasta  ./"$sample".sorted.bam > "$sample".bam.tsv`

### Expected behaviour

1.get correct tsv file in Total transcriptome level.
2.No error was reported during software running 

### Actual behaviour
1.**tsv file only covers two transcript** (The first two transcripts of the transcriptome)
2. error was reported during software running
```
[SEVERE][Sam2Tsv]scan error:
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.printAln(Sam2Tsv.java:326)
        at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.scan(Sam2Tsv.java:468)
        at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.doWork(Sam2Tsv.java:504)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:736)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:894)
        at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.main(Sam2Tsv.java:528)
[SEVERE][Sam2Tsv]Index 0 out of bounds for length 0
java.lang.RuntimeException: Index 0 out of bounds for length 0
        at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.scan(Sam2Tsv.java:476)
        at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.doWork(Sam2Tsv.java:504)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:736)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:894)
        at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.main(Sam2Tsv.java:528)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.printAln(Sam2Tsv.java:326)
        at com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.scan(Sam2Tsv.java:468)
        ... 4 more
[INFO][Launcher]sam2tsv Exited with failure (-1)
```

**Comment by lindenb** [comment]
thanks for the report. It's hard to answer without seing the bam. Can you please try to isolate a section of the bad reads of the bam (using for example `samtools view -o bad.sam sample.sorted.bam "chr12:345-567") and then attach the bad file to this issue. Thanks.

**Comment by weir12** [comment]
Thanks for your help!
Here is bad.sam.  
[bad.zip](https://github.com/lindenb/jvarkit/files/2893701/bad.zip)

**Comment by lindenb** [comment]
sorry, my bad, I also need the header of the sam, so it should be `samtools view -h -o bad.sam sample.sorted.bam "chr12:345-567" `

**Comment by lindenb** [comment]
with  a fake header, I don't have a problem with your sam (howebver I must say changed a few minor things in the last 30'... )

```
 java -jar dist/sam2tsv.jar bad.sam  > /dev/null 
[INFO][Sam2Tsv]. Completed. N=488. That took:0 second
```

**Comment by lindenb** [comment]
so may be I need your `./Araport11_genes.201606.cdna.fasta` too

**Comment by weir12** [comment]
This's sam file with intact header and my ref.fasta
[sam_fasta.zip](https://github.com/lindenb/jvarkit/files/2893842/sam_fasta.zip)

**Comment by lindenb** [comment]
works on my machine : `$ java -jar dist/sam2tsv.jar -R  ~/Araport11_genes.201606.cdna.fasta  ~/jeter.bam > /dev/null && echo OK
[INFO][Sam2Tsv]. Completed. N=488. That took:0 second
OK

**Comment by lindenb** [comment]
@weir12 I [pushed](https://github.com/lindenb/jvarkit/commit/9b4d964a56fd6695ae07849bdc0b962cc4cb1613) some minor (?) changes since your issue: can you please try again ? :thinking:

**Comment by weir12** [comment]
Alright,then I did the following :

1. `rm -rf ,/jvarkit `
2. `git clone "https://github.com/lindenb/jvarkit.git"`
3. `cd  jvarkit`
4. .`/gradlew sam2tsv`

Here is Information during compilation:
```
[ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 8
[ant:javac] 1 warning
 
 > Task :sam2tsv
 jar file generated :/home/weir/Epinano/jvarkit/dist/sam2tsv.jar
 Test will be executed in /home/weir/Epinano/jvarkit/tests-output/sam2tsv/index.html
 
 [ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 8
 [ant:javac] 1 warning
 
 BUILD SUCCESSFUL in 13s
1 actionable task: 1 executed
```

Then,I retry ` java -jar /home/weir/Epinano/jvarkit/dist/sam2tsv.jar -r ./Araport11_genes.201606.cdna.fasta ./"$sample".sorted.bam > "$sample".bam.tsv`

Wth the screen scrolling quickly,I see countless similar warning message:
```
[WARN][Sam2Tsv]Ignoring read without sequence: 6529bddf-67b9-45e8-916e-dcd73c6e9c4c_Basecall_1D_template
[WARN][Sam2Tsv]Ignoring read without sequence: 033a0a9b-b4d1-48c3-a192-27e24a5d51c0_Basecall_1D_template
[WARN][Sam2Tsv]Ignoring read without sequence: 033a0a9b-b4d1-48c3-a192-27e24a5d51c0_Basecall_1D_template
[WARN][Sam2Tsv]Ignoring read without sequence: 033a0a9b-b4d1-48c3-a192-27e24a5d51c0_Basecall_1D_template
[WARN][Sam2Tsv]Ignoring read without sequence: 033a0a9b-b4d1-48c3-a192-27e24a5d51c0_Basecall_1D_template
[WARN][Sam2Tsv]Ignoring read without sequence: 033a0a9b-b4d1-48c3-a192-27e24a5d51c0_Basecall_1D_template
...
```
I got few Large  tsv files after a period time (The file size is growing so fast that I have to stop the program):
```
#READ_NAME      FLAG    CHROM   READ_POS        BASE    QUAL    REF_POS REF     OP
3bb5f9cf-0451-4f91-9639-781a47a90825_Basecall_1D_template       0       AT1G20696.5     0       T       *300     T       S
3bb5f9cf-0451-4f91-9639-781a47a90825_Basecall_1D_template       0       AT1G20696.5     1       T       )301     C       S
3bb5f9cf-0451-4f91-9639-781a47a90825_Basecall_1D_template       0       AT1G20696.5     2       T       '302     T       S
3bb5f9cf-0451-4f91-9639-781a47a90825_Basecall_1D_template       0       AT1G20696.5     3       C       &303     T       S
3bb5f9cf-0451-4f91-9639-781a47a90825_Basecall_1D_template       0       AT1G20696.5     4       A       '304     C       S
```
Despite errors reported during compilation and run,but I seem obtained correct output file?

**Comment by lindenb** [comment]
read named '6529bddf-67b9-45e8-916e-dcd73c6e9c4c_Basecall_1D_template' was not present in your attached bam (?!)

what is the output of

` samtools view your.bam | grep -F 6529bddf `

My guess is it contains a read **without** SEQ and so, of course, it cannot be displayed (the warning was my fix in my last commit.)

**Comment by weir12** [comment]
Sorry, I didn’t respond in time.
After running `samtools view my.bam | grep -F 6529bddf`, I got this result:
```
6529bddf-67b9-45e8-916e-dcd73c6e9c4c_Basecall_1D_template       0       AT3G22235.1     155     0       9M3D7M1I1M1I19M1D7M1I10M1D15M1D4M2I8M1I4M1D42M1D5M2I4M1D26M1D49M1D23M1D11M1I56M2D11M4I7M1D7M1I12M1D22M61S  * 00       ACTCCTCAGCTCAAATACAAGAATGAATCAATCCGCGCAAATTACTTTTTCCGTGCAAAACCTTCAGAGACTCATTCCAGGGCCGTTTCAAAGTCCGCCACCAATTGGTTATCCGACTAGAGATGCGGTGGTAGTGAATTCCTCGGCAGCAGCAGTGGAGACAAACTCCTGGGCGTCAACCCCGAAGGATGTTGTGCTGCCATATGCTGCTGTTGTGTCTGGATGCATGCTTTATAGACTTAGAATTAACGATTTTCATGCAAATTATTGATGTAATAAAAGAGTATTTGATGCTAGTCATGTTACCTACTCTGTTTGGAATATATATACTTGTGGATCGGTTGTTACTATTGTTATGTAAGTGATTATATATTCCGTGAAAAAATCCCTACCCATCCCATCATCCATTATCATCATCCCTACCATCCTAATCC  '))&.(()(**();0,,,.+.892.,5*/.*&)+&()(,9-+)***11.,+3+/0//<6,,*$#'((++++.)))&(&'4403,',(&&+-..,-3-2/)*/+-3-6485.,-620,+*)*(***'/.,00*&.*12*)'$''''3*)*-)'(*+,/3*+++0:0'')(&$+1&)-,0..73+'/(.,,,,&-,.10/11.()(*-5521***/).,%'&%-&%$"$)+&*)*&%%)*%+'(-/-.,.--/18-1-((+,,/821/-,1,-01464/6/5/%))(*.0-**--23+-,#$&$$'%+())'(&(),//.2.1+.,+-,,+%')%(+,**'(+7/.+/'%+')(&*0*++-30,/011-,+&(')/1+*+*-586.,$-3-((-1'%$&'&%%$$%&'%'&&'&%'&&&&((#$&'&#(*$'($'*  NM:i:39 ms:i:258        AS:i:258        nn:i:0  ts:A:+  tp:A:P  cm:i:43 s1:i:194  s2:i:194 de:f:0.0814
6529bddf-67b9-45e8-916e-dcd73c6e9c4c_Basecall_1D_template       256     AT3G22235.2     58      0       9M3D7M1I1M1I19M1D7M1I10M1D15M1D4M2I8M1I4M1D42M1D5M2I4M1D26M1D49M1D23M1D11M1I56M2D11M4I7M1D7M1I12M1D22M61S  * 00       *       *       NM:i:39 ms:i:258        AS:i:258        nn:i:0  ts:A:+  tp:A:S  cm:i:43 s1:i:194  de:f:0.0814
```
Obviously，this read do present in my bam file and be mapped to two transcript isoforms. Your guess is right that second mapping record is missing 10th col.

So,will this problem affect my downstream processing(e.g variant calling)?
Many thanks!

**Comment by lindenb** [comment]
> So,will this problem affect my downstream processing(e.g variant calling)?

well there will be nothing to call :-)

I'm closing this issue.
