### ISSUE TITLE
deletion shown by lowresbam2raster

### ISSUE THREAD

**Issue by shannjiang** [lindenb/jvarkit#126]
Hi Pierre Lindenbaum,

I am using the lowresbam2raster to visually check some structural variant events in my samples but I am a little bit confused about how to understand the figures.
Attached figure is the region (chr13: 21736017-21742126) of deletion identified by structural variant calling algorithms LUMPY and DELLY. The algorithms showed that there are some reads were broken (or some other ways to describe the deletion event). And the deleted region just corresponds to these red lines shown on the graph. Can I say that the red lines indicate the deletion? Or do you have any document I can read to understand how do these symbols or signs on the graph mean?

![s1329_trio1_C_DNcnv_chr13_21736017-21742126](https://user-images.githubusercontent.com/31867080/56378344-69595780-61d2-11e9-8fb5-63b4d3d4fe88.png)

thanks,

Shan

**Comment by lindenb** [comment]
the yellow parts are the clip. The red arcs are the links to the supplementary alignments contained in the "SA:Z" tag of the reads.

**Comment by shannjiang** [comment]
Thank you @lindenb . I would close the issue.
