### ISSUE TITLE
New release for bioconda?

### ISSUE THREAD

**Issue by guillaumecharbonnier** [lindenb/jvarkit#127]
Dear Pierre,

I have tried some functions from jvarkit recently and the master branch build correctly with conda:
https://anaconda.org/guillaumecharbonnier/jvarkit-bam2wig

Could you tag a release to add some of your functions to bioconda ?

**Comment by lindenb** [comment]
looks cool. ( however your project is bam2wig and the home is  http://lindenb.github.io/jvarkit/Sam2Tsv.html ?)

My previous experience with conda was rather poor . I started a project https://github.com/lindenb/bioconda-recipes/tree/jvarkit a few monthes ago but I had some problems with java.

> Could you tag a release to add some of your functions to bioconda ?

https://github.com/lindenb/jvarkit/releases/tag/201904251722

**Comment by guillaumecharbonnier** [comment]
Thanks. I have added two of your tools to bioconda. If most of them only rely on openjdk it can be relatively fast to make them available.
