### ISSUE TITLE
vcf2mongo.xslt missing

### ISSUE THREAD

**Issue by darked89** [lindenb/jvarkit#132]
Hello,

I have compiled vcf2.xml.jar, but to use the following command to insert it it into mongodb: 

java -jar vcf2.xml.jar < file.vcf | xsltproc vcf2mongo.xslt - | mongo

I cannot find vcf2mongo.xslt anywhere neither inside the jvarkit directory tree nor by googling it.

Is this an obsolete/unsupported vcf->mongodb route, or one can obtain the vcf2mongo.xslt file?

Many thanks for your help

Darek Kedra

**Comment by lindenb** [comment]
I haven't used vcf2xml for years but the vcf2mongo.xsl is in the doc : https://github.com/lindenb/jvarkit/blob/95c9069a5029319d7baa69dfa9c1d11772f0895c/docs/Vcf2Xml.md#example-2-inserting-into-mongodb just copy + paste the code in a text file ' vcf2mongo.xslt'.

**Comment by darked89** [comment]
Thank you very much. 

The example works fine with openjdk version "12.0.1", mongodb 4.0.11 & mongodb-compass 1.18 on Linux Manjaro. 
I have to play with vcf2mongo.xsl to get few versions of it compatible with VCFs types I have.   

Best,

Darek Kedra
