### ISSUE TITLE
no reads output with bamslicebed 

### ISSUE THREAD

**Issue by vibansal** [lindenb/jvarkit#136]
### Subject of the issue
bamslicebed.jar does not output reads for PacBio bam file. 

### Your environment
version = 89cee26

### Steps to reproduce
download and index bam file:

samtools view -b ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG004_NA24143_mother/PacBio_MtSinai_NIST/PacBio_minimap2_bam/HG004_PacBio_GRCh38.bam chr20:1505170-1505198 > HG004_PacBio_GRCh38.bam
samtools index HG004_PacBio_GRCh38.bam

java -jar jvarkit/dist/bamslicebed.jar --region chr20:1505170-1505198 HG004_PacBio_GRCh38.bam --bai 

### Expected behaviour
Reads should be output 

### Actual behaviour
[INFO][BamSliceBed]. Completed. N=22. That took:0 second

**Comment by lindenb** [comment]
Thanks for the report. The file is huge, can you please attach here the section of the bam please.

```
samtools view -o tmp.bam HG004_PacBio_GRCh38.bam "chr20:1505170-1505198"
```

**Comment by lindenb** [comment]
Ok, I can reproduce the bug. I'm gonna explore this.

**Comment by lindenb** [comment]
Ok for now I know why it fails. The program ignores the read missing a QUALITY string but your reads  in the region are missing this information:

```
$ samtools view jeter.bam | cut -f 11
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
```

I'm going to see if I can use those reads...

**Comment by lindenb** [comment]
I fixed it in https://github.com/lindenb/jvarkit/commit/aa9cce813068f9716c771ee7a3cd98f0b9b10f2a . The program now handles the NULL qualities. Tell me if it works on your side please.
