### ISSUE TITLE
Vcfrebase requires "ENZ" to be defined in VCF header and unsure of ENZ field format

### ISSUE THREAD

**Issue by jelber2** [lindenb/jvarkit#137]
### Subject of the issue

    Vcfrebase requires "ENZ" to be defined in VCF header and not sure how to interpret ENZ filed format as it differs from documentation
    

### Your environment
* version of jvarkit

    `java -jar /genetics/elbers/jvarkit/dist/vcfrebase.jar --version`
    `b2284f5`

* version of java

  ` java -version`
    `openjdk version "1.8.0_222"
    OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
    OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)`

* the value of `${JAVA_HOME}`
    
    `echo ${JAVA_HOME}`
    `/usr/lib/jvm/java-1.8.0-openjdk-amd64`

* which OS
    
    `lsb_release -a`
    `LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security- 
    9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch`
    `Distributor ID: Ubuntu`
    `Description:    Ubuntu 16.04.6 LTS`
    `Release:        16.04`
    `Codename:       xenial`

### Steps to reproduce

The two main files CamFer2.fa and WC_DC_merged_different_genotypes.vcf I can send  to you privately if needed.

    cd /genetics/elbers
    git clone "https://github.com/lindenb/jvarkit.git"
    cd /genetics/elbers/jvarkit
    ./gradlew vcfrebase # not vcfrefbase as in documentation
    
    cd /genetics/elbers/rflps
    java -jar /genetics/elbers/picard-2.20.4.jar CreateSequenceDictionary R=CamFer2.fa O=CamFer2.dict
    samtools faidx CamFer2.fa
    
    cd /genetics/elbers/rflps/test
    
    cat WC_DC_merged_different_genotypes.vcf |java -jar /genetics/elbers/jvarkit/dist/vcfrebase.jar -R ../CamFer2.fa |grep -E '(#|ENZ=)' > enzyme.vcf
    [SEVERE][Launcher]Key ENZ found in VariantContext field INFO at 10:59252584 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.
    java.lang.IllegalStateException: Key ENZ found in VariantContext field INFO at 10:59252584 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.
            at htsjdk.variant.vcf.VCFEncoder.fieldIsMissingFromHeaderError(VCFEncoder.java:213)
            at htsjdk.variant.vcf.VCFEncoder.write(VCFEncoder.java:146)
            at htsjdk.variant.variantcontext.writer.VCFWriter.add(VCFWriter.java:250)
            at com.github.lindenb.jvarkit.util.vcf.DelegateVariantContextWriter.add(DelegateVariantContextWriter.java:56)
            at com.github.lindenb.jvarkit.tools.vcfrebase.VcfRebase.doVcfToVcf(VcfRebase.java:231)
            at com.github.lindenb.jvarkit.util.jcommander.Launcher.doVcfToVcf(Launcher.java:563)
            at com.github.lindenb.jvarkit.util.jcommander.Launcher.doVcfToVcf(Launcher.java:583)
            at com.github.lindenb.jvarkit.tools.vcfrebase.VcfRebase.doWork(VcfRebase.java:290)
            at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:742)
            at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:905)
            at com.github.lindenb.jvarkit.tools.vcfrebase.VcfRebase.main(VcfRebase.java:305)
    [INFO][Launcher]vcfrefbase Exited with failure (-1)
    
    grep "##fileformat=VCFv4.2" WC_DC_merged_different_genotypes.vcf > header1
    grep "^##" WC_DC_merged_different_genotypes.vcf |grep -v "##fileformat=VCFv4.2" > header2
    echo -e '##INFO=<ID=ENZ,Number=.,Type=String,Description="Enzyme overlapping: Format: (Name,Site,Sequence,pos-1,strand)"' > header3
    cat header2 header3|sort > header4
    cat header1 header4 > header5
    grep "^#CHR" WC_DC_merged_different_genotypes.vcf > header6
    grep -v "^#" WC_DC_merged_different_genotypes.vcf > WC_DC_merged_different_genotypes.tailer
    
    cat header5 header6 WC_DC_merged_different_genotypes.tailer > WC_DC_merged_different_genotypes2.vcf
    cat WC_DC_merged_different_genotypes2.vcf |java -jar /genetics/elbers/jvarkit/dist/vcfrebase.jar -R ../CamFer2.fa |grep -E '(#|ENZ=)' |grep -v "contig" > enzyme.vcf
    [INFO][VcfRebase]. Completed. N=88. That took:0 second
    
    cut -f 8 enzyme.vcf |grep -Po "ENZ=\S+;HMP" |perl -pe "s/HMP//g" > col8
    grep "^#CHR\|;ENZ" enzyme.vcf |cut -f 1-7 > col1-7
    sed -i '1i FORMAT' col8
    paste col1-7 col8 |column -tx
    
    #CHROM    POS        ID  REF  ALT  QUAL   FILTER  FORMAT
    10        59252584   .   C    T    999    PASS    ENZ=(MboII|GAAGA(8/7)|GAAGA|59252585|+);
    10        65195174   .   C    T    999    PASS    ENZ=(BbvI|GCAGC(8/12)|GCTGC|65195175|-);
    12        13709923   .   G    T    999    PASS    ENZ=(PstI|CTGCA^G|CTgCAG|13709921|+),(Sse8387I|CCTGCA^GG|CCTgCAGG|13709920|+);
    12        13710143   .   G    T    33.21  PASS    ENZ=(BsgI|GTGCAG(16/14)|GTGCAg|13710138|+);
    15        40480157   .   A    G    999    PASS    ENZ=(StyI|C^CWWGG|CCAaGG|40480154|+);
    19        11217629   .   C    T    999    PASS    ENZ=(PcsI|WCGNNNN^NNNCGW|ACGGAAGCTTcGA|11217619|+);
    2         99605950   .   C    A    50.21  PASS    ENZ=(HindIII|A^AGCTT|AAGcTT|99605947|+);
    2         118308747  .   C    G    999    PASS    ENZ=(FokI|GGATG(9/13)|CATCc|118308743|-),(EciI|GGCGGA(11/9)|TCcGCC|118308745|-);
    21        20449581   .   G    A    999    PASS    ENZ=(MslI|CAYNN^NNRTG|CACTGCAgTG|20449574|+),(PstI|CTGCA^G|CTGCAg|20449576|+),(AlfI|(10/12)GCANNNNNNTGC(12/10)|GCACTGCAgTGC|20449573|+),(BtsIMutI|CAGTG(2/0)|CAgTG|20449579|+),(BtsI|GCAGTG(2/0)|GCAgTG|20449578|+),(OliI|CACNN^NNGTG|CACTGCAgTG|20449574|+);
    22        21341467   .   T    C    999    PASS    ENZ=(TspDTI|ATGAA(11/9)|TTCAt|21341463|-);
    25        13481156   .   T    C    51.15  PASS    ENZ=(BtsIMutI|CAGTG(2/0)|CACtG|13481153|-);
    25        13481319   .   C    T    999    PASS    ENZ=(TspDTI|ATGAA(11/9)|TTcAT|13481317|-);
    25        37193389   .   A    G    999    PASS    ENZ=(BtsI|GCAGTG(2/0)|CaCTGC|37193388|-),(BtsIMutI|CAGTG(2/0)|CaCTG|37193388|-);
    28        14665426   .   C    T    999    PASS    ENZ=(TatI|W^GTACW|TGTAcT|14665422|+),(BseMII|CTCAG(10/8)|cTGAG|14665426|-);
    3         6309457    .   T    C    999    PASS    ENZ=(BsrI|ACTGG(1/-1)|ACTGG|6309458|+);
    3         102461279  .   G    T    999    PASS    ENZ=(NheI|G^CTAGC|gCTAGC|102461279|+),(BglI|GCCNNNN^NGGC|GCCTCTCAGgC|102461270|+);
    31        25832      .   T    C    51.14  PASS    ENZ=(OliI|CACNN^NNGTG|CACCTCTGtG|25824|+),(MslI|CAYNN^NNRTG|CACCTCTGtG|25824|+);
    4         1613598    .   T    G    999    PASS    ENZ=(SapI|GCTCTTC(1/4)|GCTCTtC|1613593|+),(MboII|GAAGA(8/7)|TCTtC|1613595|-);
    6         8250940    .   C    A    43.17  PASS    ENZ=(NspI|RCATG^Y|AcATGT|8250939|+),(AflIII|A^CRYGT|AcATGT|8250939|+),(XcmI|CCANNNNN^NNNNTGG|CCAAAcATGTTTTGG|8250935|+);
    7         4406899    .   G    A    999    PASS    ENZ=(BstXI|CCANNNNN^NTGG|CCAGGTGTCTgG|4406889|+);
    7         30577239   .   A    G    999    PASS    ENZ=(ApoI|R^AATTY|AAATTT|30577240|+);
    7         83615389   .   A    C    999    PASS    ENZ=(HaeII|RGCGC^Y|aGCGCC|83615389|+);
    9         196846     .   A    G    999    PASS    ENZ=(TspDTI|ATGAA(11/9)|TTCaT|196843|-);
    9         62359049   .   G    A    30.23  PASS    ENZ=(MboII|GAAGA(8/7)|gAAGA|62359049|+),(TspDTI|ATGAA(11/9)|ATgAA|62359047|+);
    9         74235904   .   G    T    999    PASS    ENZ=(EcoNI|CCTNN^NNNAGG|CCTCACCAAgG|74235895|+),(StyI|C^CWWGG|CCAAgG|74235900|+);
    Contig74  8268530    .   T    C    999    PASS    ENZ=(FokI|GGATG(9/13)|CAtCC|8268528|-),(SfaNI|GCATC(5/9)|GCAtC|8268527|+);
    X         7120981    .   G    C    999    PASS    ENZ=(BsaAI|YAC^GTR|TACgTA|7120978|+),(SnaBI|TAC^GTA|TACgTA|7120978|+);
    X         18694565   .   C    A    746    PASS    ENZ=(SfaNI|GCATC(5/9)|GATGc|18694561|-),(FauI|CCCGC(4/6)|GcGGG|18694564|-);
    
    grep "#" enzyme.vcf |grep ENZ
    ##INFO=<ID=ENZ,Number=.,Type=String,Description="Not provided in original VCF header">

    # according to documentation ##INFO=<ID=ENZ,Number=.,Type=String,Description="Enzyme overlapping: Format: (Name,Site,Sequence,pos-1,strand)">
    # in VCF file ENZ=(SfaNI|GCATC(5/9)|GATGc|18694561|-)

So input VCF file requires ENZ to be defined in the header before processing with vcfrebase and the ENZ field output is not as same as in the documentation.

So how do I interpret `ENZ=(SfaNI|GCATC(5/9)|GATGc|18694561|-)` for example

**Comment by lindenb** [comment]
@jelber2 Hi, thank yo for the report, I haven't used this for years, give me 15' to check...

**Comment by lindenb** [comment]
I hope it's fixed in https://github.com/lindenb/jvarkit/commit/d8fb2034ebefb9b1a80fb70ac499394d99288e96

can you test it please ?

**Comment by jelber2** [comment]
Yes it works! Thanks.
Two things:
(1) ##INFO=<ID=ENZ,Number=.,Type=String,Description="Enzyme overlapping: Format: (Name,Site,Sequence,pos,strand)">
but there are `|` in the output and not `,`
(2) What does the `(8/7)` mean in the ouput for example `ENZ=MboII|GAAGA(8/7)|GAAGA|59252585|+`

**Comment by lindenb** [comment]
1) right, I'll fix this
2) see ftp://ftp.neb.com/pub/rebase/withrefm.txt 

```
<RECOGNITION SEQUENCE> 
                These are written from 5' to 3', only one strand being given.
                If the point of cleavage has been determined, the precise site
                is marked with ^.  For enzymes such as HgaI, MboII etc., which
                cleave away from their recognition sequence the cleavage sites
                are indicated in parentheses.  

                For example HgaI GACGC (5/10) indicates cleavage as follows:
                                5' GACGCNNNNN^      3'
                                3' CTGCGNNNNNNNNNN^ 5'
```

**Comment by jelber2** [comment]
Oh and just a minor point that http://lindenb.github.io/jvarkit/VcfRebase.html says `./gradlew vcfrefbase` and not `./gradlew vcfrebase`

**Comment by lindenb** [comment]
thanks :+1: ! it's fixed.
