### ISSUE TITLE
vcf2table output files problem

### ISSUE THREAD

**Issue by motutaj** [lindenb/jvarkit#142]
Hello,

I have vcf files that were  **annotated with VEP**, but instead of INFO[CSQ]  I have:

##INFO=<ID=ANN,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA
_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|CANONICAL|SIFT|HGVS_OFFSET|HGVSg">

When I run java -jar /dist/vcf2table.jar file.vcf it **works fine with output to stdout,** but when i want to save it in **txt file text is scrambled**:

java -jar /dist/vcf2table.jar file1.vcf -o file1.txt
[WARN][SnpEffPredictionParser]no INFO[EFF] or no description. This VCF was probably NOT annotated with SnpEff (old version). But it's not a problem if this tool doesn't need to access SnpEff Anotations.
[WARN][VepPredictionParser]NO INFO[CSQ] found in header. This VCF was probably NOT annotated with VEP. But it's not a problem if this tool doesn't need to access VEP Annotations.
![vcf2table_out](https://user-images.githubusercontent.com/39564256/71695409-a755d600-2d77-11ea-9790-043fee109b6b.png)

**Comment by lindenb** [comment]
I don't have any color when I use a similar command. I suspect you also added the option `--colors`.

**Comment by motutaj** [comment]
I used with --colors and without  --colors option and it didn't make difference.

Thank you,
Monika

**Comment by lindenb** [comment]
on my side:

![image](https://user-images.githubusercontent.com/33838/71696492-62e92b00-2db5-11ea-84ad-7ae2a6c731bd.png)

**Comment by motutaj** [comment]
no --colors

![vcf2table_out](https://user-images.githubusercontent.com/39564256/71696879-da01cd80-2d7b-11ea-85a3-655a6902d177.png)

**Comment by lindenb** [comment]
sorry, I still don't get the same result:

![image](https://user-images.githubusercontent.com/33838/71697121-4817b600-2db7-11ea-964e-1d6f6613e263.png)

**Comment by motutaj** [comment]
I figured it out. When I bgzip vcf file it worked correctly. Thanks for fast replies.

Monika
