### ISSUE TITLE
Biostar404363 build failing, gradle cannot download htsjdk

### ISSUE THREAD

**Issue by 690645258** [lindenb/jvarkit#145]
### Subject of the issue
When running the command ./gradlew biostar404363 to build biostar404363 it appears to be using depreciated links on maven. Manually downloading htsjdk etc allows gradle to get to the next step but each link is failing. 

As far as I can tell http://central.maven.org/ needs to be altered to https://repo1.maven.org/ and this allows me to manually download the correct .jar's and place them in the correct directory.

### Your environment
* version of jvarkit
* version of java
* the value of `${JAVA_HOME}`
* which OS

### Steps to reproduce
./gradlew biostar404363

### Expected behaviour
biostar404363 build successfully

### Actual behaviour
`Downloading https://services.gradle.org/distributions/gradle-5.1.1-bin.zip
.................................................................................

Welcome to Gradle 5.1.1!

Here are the highlights of this release:
 - Control which dependencies can be retrieved from which repositories
 - Production-ready configuration avoidance APIs

For more details see https://docs.gradle.org/5.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :biostar404363 FAILED
Downloading http://central.maven.org/maven2/com/github/samtools/htsjdk/2.20.1/htsjdk-2.20.1.jar to /home/user/bioinformatics_tools/jvarkit/lib/com/github/samtools/htsjdk/2.20.1/htsjdk-2.20.1.jar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for biostar404363 com.github.lindenb.jvarkit.tools.biostar.Biostar404363.
> Can't get http://central.maven.org/maven2/com/github/samtools/htsjdk/2.20.1/htsjdk-2.20.1.jar to /home/user/bioinformatics_tools/jvarkit/lib/com/github/samtools/htsjdk/2.20.1/htsjdk-2.20.1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
1 actionable task: 1 executed
`

**Comment by lindenb** [comment]
Ah, maven changed the URL where the libraries are downloaded. I've just fixed this. 

https://github.com/lindenb/jvarkit/commit/b3893fd3364fe8a4c13789420ed4fde26d051e86

can you try again please ?

**Comment by 690645258** [comment]
Builds perfectly now, thanks!
