### ISSUE TITLE
Is there a specifier that could be used in the BlastToSnp command line that would not eliminate perfect matches that are in the output blastn file?

### ISSUE THREAD

**Issue by deborapirespaula** [lindenb/jvarkit#146]
I'm running BlastToSnp on the output file of a BLASTn result to get the mismatch and gap positions. However, I noticed that BlastToSnp seems to report the results only for the imperfect matches (that is, the ones with mismatches and/or gaps). For my intended downstream analysis, I not only need to know the positions of the mismatches and/or gaps, but also to keep the information for the perfect matches.
Is there any specifier that can be added in the command line that would not eliminate the perfect matches from the BlastToSnp output file?
Thank you.

**Comment by lindenb** [comment]
> Is there any specifier that can be added in the command line that would not eliminate the perfect matches from the BlastToSnp output file?

short answer: i'm sorry, there is no such option.
