### ISSUE TITLE
SamViewWithMate: width one regions using BED file

### ISSUE THREAD

**Issue by daynefiler** [lindenb/jvarkit#154]
First, ***thank you*** for sharing all of your work.

### Subject of the issue
When trying to subset a bam file with a BED file containing single nucleotide regions, the program skips those regions. 

`[WARN][BedLineCodec]cannot use empty BED interval NC_000022.11	50283705	50283705 ("NC_000022.11(tab)50283705(tab)50283705"=. Skipping.`

### Your environment
* version of jvarkit: 174c887dd7d4b016fab5eb055b95d4ad8f2c98ec
* version of java:
```
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (Zulu 8.33.0.1-linux64) (build 1.8.0_192-b01)
OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-linux64) (build 25.192-b01, mixed mode)
```
* the value of `${JAVA_HOME}`
`/home/dfiler/tools/miniconda3`
* which OS
```
CentOS Linux release 7.4.1708 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core) 
CentOS Linux release 7.4.1708 (Core) 
```

### Steps to reproduce
`java -jar ~/jvarkit/dist/samviewwithmate.jar -b some.bed some.bam`
where `some.bed` contains a single nucleotide region, e.g.  NC_000022.1:50283705-50283705

**Comment by lindenb** [comment]
thanks

a BED record like 'contig(tab)50283705(tab)50283705' is **EMPTY** . A bed record is an open-ended interval. see https://www.biostars.org/p/84686/

a one base bed would be 'contig(tab)50283704(tab)50283705"'

**Comment by daynefiler** [comment]
Thanks for your quick response!
