### ISSUE TITLE
sam2tsv

### ISSUE THREAD

**Issue by mohammedmsk** [lindenb/jvarkit#159]
Hello,

I was using an old version of sam2tsv on an alignment sam file generated by a tool called paladin (https://github.com/ToniWestbrook/paladin).

## Error
With the most updated version of this tool it does not work giving an error like:
Ignoring SAM validation error due to lenient parsing:
Error parsing text SAM file. Invalid character in read bases; File some.sam; Line 1525

I believe  this is most likely because now the new tool is checking for standard bases A T G C to be present and is failing because sequences are actually amino acids.

Is it possible to have a version of the tool where read base checking is not done.

Thanks.

**Comment by lindenb** [comment]
sorry no, this is checked via the htsjdk library (not on my side).  https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/SAMLineParser.java#L378

**Comment by mohammedmsk** [comment]
Thanks for the reply.

While running the tool like above it actually does produce the output but with error complaints on every line. Which is fine. So it serves the purpose for now. Closing the issue.
