### ISSUE TITLE
Extract only the portion of read overlapping to bed

### ISSUE THREAD

**Issue by MaestSi** [lindenb/jvarkit#160]
Dear Pierre,
I am using your tool samjs as you suggested in [this post](https://www.biostars.org/p/259690/). Similarly to the person who opened the post, I would like to keep only the portion of long-reads overlapping the bed file. In particular, I have a primary and many supplementary alignments mapping to a region of interest, and I would like to extract all those reads portions. Have you planned to add an option to do this in the near future? I know an alternative might be to use a combination of pcrclipreads and samextractclip, but samjs may be more straightforward to do this.
Thanks in advance,
Simone

**Comment by lindenb** [comment]
Hi

> Have you planned to add an option to do this in the near future? 

no :-)

>  know an alternative might be to use a combination of pcrclipreads 

yes, that's what I would have suggested.

>  but samjs may be more straightforward to do this.

no, I don't think so.

**Comment by MaestSi** [comment]
Thank you for the prompt reply!
Simone
