### ISSUE TITLE
vcfpolyx counts homopolymer repeats in the wrong position

### ISSUE THREAD

**Issue by ftucos** [lindenb/jvarkit#165]
vcfpolyx is counting homopolymer one base before were the deletion happens. Probably it's not taking into account the left normalization of the VCF file thus reading the first (common) base and not the deleted one. Here an example:
![img](https://i.ibb.co/dr956HP/Screenshot-2020-10-12-at-03-56-17.png)

**Comment by lindenb** [comment]
ah yes, you're right ! I'm gonna fix this.

**Comment by lindenb** [comment]
I added a `+1` when the variant is an indel: https://github.com/lindenb/jvarkit/commit/6d7e78cc303ff2ced435750707c285d169b3fc64

tell me if it fulfills your needs.

**Comment by ftucos** [comment]
Thank you for the super quick fix. I just tested it and validated a dozen of homopolymers. It's working perfectly!
Thank you very much for this useful tool!
