### ISSUE TITLE
 Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

### ISSUE THREAD

**Issue by ASQWZXED** [lindenb/jvarkit#167]
### Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
I follow the steps but an error comes out after I typed `./gradlew vcffilterjdk`
`
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 680ms
`

### Your environment
* version of jvarkit: `git clone "https://github.com/lindenb/jvarkit.git"`
* version of java: `jdk-15.0.1`
* the value of `${JAVA_HOME}` : `C:\Program Files\Java\jdk-15.0.1`
* which OS: `Windows 10`

### Steps to reproduce
Tell us how to reproduce this issue. Please provide an example.

After setting JAVA_HOME, I opend Git Bash
Then entered
`$ git clone "https://github.com/lindenb/jvarkit.git"`
`$ cd jvarkit`
`$ ./gradlew vcffilterjdk`

**Comment by lindenb** [comment]
Hi, thank you for the report.
I've never compiled my tools with such recent version of java.
Can you please try this solution : https://stackoverflow.com/questions/62315496/ ?

**Comment by ASQWZXED** [comment]
That solves the problem.

Thank you very much.
