### ISSUE TITLE
Couldn't open vcffilterjdk.jar

### ISSUE THREAD

**Issue by ASQWZXED** [lindenb/jvarkit#168]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

### Subject of the issue
`I have installed JDK 11 and installed  java runtime environment.`
`I installed Jvarkit properly using Git Bash.`
`The vcffilterjdk.jar file has been created, but it couldn't be opened !`

### Your environment
* version of jvarkit: `from Git Bash` 
* version of java:  `JDK 11.0.9`
* the value of `${JAVA_HOME}`: `C:\Program Files\Java\jdk-11.0.9`
* which OS: `Windows 10`

### Steps to reproduce
Tell us how to reproduce this issue. Please provide an example.
`I installed JDK 11.0.9 and java runtime environment. After that, I setup JAVA_HOME.`
`Next, I downloaded Jvarkit using Git Bash. `
`The vcffilterjdk.jar file has been created. But it couldn't be opened !`

### Expected behaviour
`Couldn't open vcffilterjdk.jar file.` 

### Actual behaviour
Tell us what happens instea.
 `No thing happen`

**Comment by lindenb** [comment]
from the jvarkit  directory. What is the output of

```
ls dist
```

**Comment by ASQWZXED** [comment]
dist directory just has this file 
`vcffilterjdk.jar`

**Comment by lindenb** [comment]
so the file is here... what do you mean with ` Couldn't open vcffilterjdk.jar file.` ? how did you try to 'open' the file ? what do you think is 'opening' the file ?

**Comment by ASQWZXED** [comment]
I thought it is like an exe file that I can inter commands and run it.

How can I run commands like this one.
`java -jar dist/vcffilterjdk.jar \
  -e 'return variant.isSNP() && variant.isBiallelic() && VariantContextUtils.isTransition(variant);' \
  input.vcf`

**Comment by lindenb** [comment]
> How can I run commands like this one:

I do not understand. Did you only just try to type the command ` java -jar dist/vcffilterjdk.jar ...`  ?

and what are those `\` ?

**Comment by ASQWZXED** [comment]
I have a csv file that has SNPs and I want to extract SNP mutations. 

I don't know I found it in this website 
`https://www.biostars.org/p/287667/`

**Comment by lindenb** [comment]
I cannot understand your problem if you don't show me the exact commands you're using.

**Comment by lindenb** [comment]
>  https://www.biostars.org/p/287667/

`\` at the end of line: https://stackoverflow.com/a/3871336/58082

**Comment by ASQWZXED** [comment]
Okay, where can I found documents on how to use jvarkit?

**Comment by lindenb** [comment]
> Okay, where can I found documents on how to use jvarkit?

http://lindenb.github.io/jvarkit/VcfFilterJdk.html#about-the-script

**Comment by lindenb** [comment]
Closing. There is no such problem `Couldn't open vcffilterjdk.jar`.
