### ISSUE TITLE
gridsspostprocessvcf estimates Breakpoint INS like DEL.

### ISSUE THREAD

**Issue by gmgs-999** [lindenb/jvarkit#171]
Hi, I ran gridsspostporcessvcf and I saw a lot of DEL. I checked them in IGV and in vcf output of gridss, and all of them (I think) were INS of two breakends.
Before running gridsspostprocessvcf(output of gridss)
![ins_example_1](https://user-images.githubusercontent.com/60798957/106032596-6b429100-60af-11eb-9254-1adc924e3bbe.png)
After running it
![ins_example_2](https://user-images.githubusercontent.com/60798957/106032610-71387200-60af-11eb-9b57-81adc63a871b.png)
In IGV
![ins_example_3](https://user-images.githubusercontent.com/60798957/106032761-a5ac2e00-60af-11eb-88df-c7bf5ca4436b.png)

All INS marked as DEL I saw had svlen = 0. All single breakend INS (REF:A, ALT: .AAGG etc..) were well estimated.
Is it a bug? Can I use the empirical rule that if an DEL has svlen=0 it's an insertion?
Thanks!

**Comment by lindenb** [comment]
sorry, I'm afraid I don't support this tool : It's not even listed in http://lindenb.github.io/jvarkit/

**Comment by gmgs-999** [comment]
Sorry, I explained myself wrong. You can find gridsspostprocessvcf here: https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/tools/structvar/gridss/GridssPostProcessVcf.java , it's a vcfpostprocesssv variation. Actually, I found it searching in the  support software list that yourself share it(in vcfpostprocess appears "gidss"). I tried first vcfpostprocess but it didn't work well. For these reason I searched vcfpostprocesssv gridss in google and gridsspostprocesssv appears. I installed using ./gradlew gridsspostprocessvcf (like vcfpostprocess).
gridsspostprocessvcf works like vcfpostprocess, input file is a vcf and the output file is an annotated vcf.
It works better than vcfpostprocess for the gridss vcf file, but I found an error on it: all two-breakend INS was annotated like DEL, and I found that SVLEN=0 in these wrong annotated variants.
Thank you and sorry if I was not clear in the post.
