### ISSUE TITLE
central maven error

### ISSUE THREAD

**Issue by PhilliVanilli** [lindenb/jvarkit#172]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

### Subject of the issue
If I run ./gradlew sam4weblogo after downloading an earlier version of jvarkit repo, I get a central maven error. Apparently during installation a file is downloaded from the web and this location changed to http://maven.org/maven2. If I change this location in the build.gradle file, then it finds that file again. However, this solution isn't stable as long as the install remains dependent on web location of file. Isn't there a way to include this file into the repo permanently?

#

### Your environment
* version of jvarkit
* commit f39087b
* version of java
* 11.0.9.1 openjdk 64bit
* the value of `${JAVA_HOME}`
* which OS
ubuntu BB 18.04 LTS

### Steps to reproduce
clone the repo at f39087b
run ./gradlew sam4weblogo inside jvarkit folder

### Expected behaviour
jvarkit should be installed

### Actual behaviour

(nanop) pselhorst@linuxlaptop:~/nanopore_pipeline_wrapper/jvarkit$ ./gradlew sam4weblogo

> Task :sam4weblogo FAILED
Downloading http://central.maven.org/maven2/com/github/samtools/htsjdk/2.19.0/htsjdk-2.19.0.jar to /home/pselhorst/nanopore_pipeline_wrapper/jvarkit/lib/com/github/samtools/htsjdk/2.19.0/htsjdk-2.19.0.jar

FAILURE: Build failed with an exception.

* Where:
Build file '/home/pselhorst/nanopore_pipeline_wrapper/jvarkit/build.gradle' line: 106

* What went wrong:
Execution failed for sam4weblogo com.github.lindenb.jvarkit.tools.sam4weblogo.SAM4WebLogo.
> java.net.UnknownHostException: central.maven.org

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by lindenb** [comment]
> Isn't there a way to include this file into the repo permanently?

Hi, I'm afraid I won't fix this. You can always fork the old commit, change the URL in `build.gradle`and use this private fork for your needs.

**Comment by PhilliVanilli** [comment]
Well, that's the thing, that won't work, since even that fork will be dependent on the future web location of these file(s) making the install unstable over the years. I don't even know what central maven is, just tried my luck by changing the link but next time that might not work. But I don't know how difficult this all is. Anyway, thanks for providing these tools! Very useful
