### ISSUE TITLE
MantaMerger running time too long and potential speeding up methods?

### ISSUE THREAD

**Issue by zjgbz** [lindenb/jvarkit#173]
Hi jvarkit team,

I am running MantaMerger for merging genome-wide structural variants of multiple ~6000 individuals to population-level SVs. However, it has been running since about three days ago. Is it a reasonable merging time? Besides, is it possible to utilize multiple CPUs to speed it up? Thank you very much.

Best regards,
zjgbz

**Comment by lindenb** [comment]
I agree my tool is quite poor and is just to slow. I strongly suggest  you use CNVNator https://github.com/abyzovlab/CNVnator

**Comment by zjgbz** [comment]
Hi @lindenb ,

No no, it is not poor at all. Your tool is the only merging tool we found for Manta at least for me. We are just wondering if 3-day running means we did anything wrong or else. Since you suggest CNVNator, I checked that, but do you mean that CNVNator also has merging tool for merging SVs from multiple samples? Because now I did not find such function, but if you have used that before, I should go deeper into CNVNator. Thank you very much!

Best regards,
zjgbz
