### ISSUE TITLE
Are there default filters in sam2tsv? (general question; not an issue)

### ISSUE THREAD

**Issue by kac2053** [lindenb/jvarkit#174]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

java version "1.7.0_221"
OpenJDK Runtime Environment (rhel-2.6.18.0.el7_6-x86_64 u221-b02)
OpenJDK 64-Bit Server VM (build 24.221-b02, mixed mode)

### Subject of the issue

Are there default filters in sam2tsv?

We have previously published data using Rsamtools pileup to generate counts for mutations.
We are now using sam2tsv to index which read IDs belong to which counts. However when I count up the number of reads to the mutation in the sam2tsv data, the counts are not matching up with pileup counts, despite filtering the sam2tsv data based on pileup default filters.
I don't have a bioinformatics background, so I'm sorry if I answered any tech questions below wrong.

Thank you.

Edit: Is base quality in pileup correspond to the read quality column in sam2tsv?

### Your environment
* version of jvarkit

$ java -jar bin/jvarkit/dist/sam2tsv.jar --version
2b40bcc06

* version of java 

java version "1.7.0_221"
OpenJDK Runtime Environment (rhel-2.6.18.0.el7_6-x86_64 u221-b02)
OpenJDK 64-Bit Server VM (build 24.221-b02, mixed mode)

* the value of `${JAVA_HOME}`

-bash: /opt/common/CentOS_7/java/jdk1.8.0_131: Is a directory

* which OS

Linux 3.10.0-957.12.2.el7.x86_64 x86_64

### Steps to reproduce
N/A because general question.

### Expected behaviour
N/A

### Actual behaviour
N/A

**Comment by lindenb** [comment]
> Are there default filters in sam2tsv?

there is none while mpileup will remove duplicates, secondary etc...
