### ISSUE TITLE
Settings.gradle empty

### ISSUE THREAD

**Issue by AndModica** [lindenb/jvarkit#185]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

### Subject of the issue
The file settings.gradle is empty but the line

rootProject.name = 'jvarkit'

### Your environment
update-java-alternatives --list
java-1.11.0-openjdk-amd64      1111       /usr/lib/jvm/java-1.11.0-openjdk-amd64
java-1.16.0-openjdk-amd64      1611       /usr/lib/jvm/java-1.16.0-openjdk-amd64* version of java
* the value of `${JAVA_HOME}`: empty
* Ubuntu 20

### Steps to reproduce
./gradlew blastn2snp

### Expected behaviour
Install Blastn2snp

### Actual behaviour
FAILURE: Build failed with an exception.

* Where:
Settings file '/home/pc/Documenti/FagusLab/jvarkit/settings.gradle'

* What went wrong:
Could not compile settings file '/home/pc/Documenti/FagusLab/jvarkit/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 60

**Comment by lindenb** [comment]
java JDK 16 is not yet supported.
Closing.
