### ISSUE TITLE
Task 'gephicmd' not found in root project 'jvarkit'

### ISSUE THREAD

**Issue by yangzuokun** [lindenb/jvarkit#195]
./gradlew gephicmd procudes an error - see output from command line:
FAILURE: Build failed with an exception.

* What went wrong:
Task 'gephicmd' not found in root project 'jvarkit'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 630ms

**Comment by lindenb** [comment]
ah yes you're right, this is a very old tool that was just designed to play with the gex api. But I won't spend some time to fix this.

you can always try to use this old makefile:

```
make -f Makefile.legacy  gephicmd
```

but sorry, I won't fix anything.
