### ISSUE TITLE
Launcher unable to close index

### ISSUE THREAD

**Issue by DcornishUCL** [lindenb/jvarkit#197]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

### Subject of the issue
Hi, I am having a slight problem using your tool vcfancestralalleles.jar to fill ancestral alleles into a VCF file. My script is erroring with the message:

**[SEVERE][Launcher]Unable to close index for file://files/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes_fillAA.vcf.gz**

### Your environment
* I am using jvarkit commit 3f7bba5f9
* I am using Java version openjdk version "1.8.0_212"

### Steps to reproduce
The script I tried to obtain this error was:
N.B. I have already removed the ancestral alleles from the input with BCFtools and validated this myself. 

java -jar /.../jvarkit/dist/vcfancestralalleles.jar \
	-m /.../human_ancestor_GRCh37_e59/manifest.mf \
	-o /.../ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes_fillAA.vcf.gz \
	/.../ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes_rmAA.vcf.gz

I wondered if this means I am required to index the input VCF: ..._rmAA.vcf.gz any help to rectify this issue would be much appreciated. Thank you.

**Comment by lindenb** [comment]
yes ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes_rmAA.vcf.gz should be indexed using `bcftools index -t ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes_rmAA.vcf.gz`

**Comment by lindenb** [comment]
also, can you please try without specifying the output file but redirect into bcftools

```
java -jar /.../jvarkit/dist/vcfancestralalleles.jar \
-m /.../human_ancestor_GRCh37_e59/manifest.mf \
/.../ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes_rmAA.vcf.gz |\
   bcftools view -O z -o  ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes_fillAA.vcf.gz
```

**Comment by DcornishUCL** [comment]
This works perfectly, thank you!
