### ISSUE TITLE
fixvcfmissinggenotypes.jar does not actually fix missing genotypes

### ISSUE THREAD

**Issue by Giuseppe1995** [lindenb/jvarkit#198]
Hi,
I am running, on a merged vcf - let's call it "merged.vcf.gz" (it has also an index) - the fixvcfmissinggenotypes.jar java script as follows

`java -jar fixvcfmissinggenotypes.jar  --bams bam.list -d 8 --output fixed.merged.vcf merged.vcf.gz`

It goes with no error or warnings, but it gives me a file ("fixed.merged.vcf") with the same missingness of the "merged.vcf.gz" (basically are the same file).

Note that to rule out that this could be due to the low coverage of bams I run the command above but with the option `-d 1`, but it resulted in no different outcome.

Thank you in advance, peppe

**Comment by lindenb** [comment]
thank you for this report. Please, give me a valid vcf file with only one variant and one subset of bam file overlapping that variant.

**Comment by Giuseppe1995** [comment]
Oh, apparently the name of the chromosomes are different in bam and in vcf (bam=chrN,; vcf=N), so this was the problem.
I'm sorry have bothered you with such stupid question, but I assumed that there was no discrepancy on the chromosome nomenclature between the two files (this is a dataset I downloaded, sorry again).
Thank you for your help!
