### ISSUE TITLE
Minicaller OutOfBoundsException

### ISSUE THREAD

**Issue by fernanarr** [lindenb/jvarkit#203]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

### Subject of the issue

Executing minicaller after obtaining the .dic file from picard, we are getting this failure

`[SEVERE][MiniCaller]offset 83, count 84, length 151
java.lang.StringIndexOutOfBoundsException: offset 83, count 84, length 151
        at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
        at java.base/java.lang.String.<init>(String.java:591)
        at com.github.lindenb.jvarkit.tools.calling.MiniCaller.doWork(MiniCaller.java:433)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:796)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:959)
        at com.github.lindenb.jvarkit.tools.calling.MiniCaller.main(MiniCaller.java:681)
[INFO][Launcher]minicaller Exited with failure (-1)`

### Your environment
* version of jvarkit
*Obtained yesterday from:
  git clone "https://github.com/lindenb/jvarkit.git"

* version of java
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

* the value of `${JAVA_HOME}`

* which OS
WSL2 Ubuntu 20

### Steps to reproduce

`java -jar ./jvarkit/dist/minicaller.jar -R ./jvarkit/dist/Carrera29062022/plasmid_COL7A1/plasmid_COL7A1-BSaI.fa -r "U6927FI290-3:1-15000" ./jvarkit/dist/Carrera29062022/pCOL7A_S1/COL7A.bam > prueba.vcf`

### Expected behaviour
output prueba.vcf

### Actual behaviour

`[INFO][MiniCaller]Scanning ./jvarkit/dist/Carrera29062022/pCOL7A_S1/COL7A.bam
WARNING: BAM index file /home/fer/./jvarkit/dist/Carrera29062022/pCOL7A_S1/COL7A.bam.bai is older than BAM /home/fer/./jvarkit/dist/Carrera29062022/pCOL7A_S1/COL7A.bam
WARNING: BAM index file /home/fer/./jvarkit/dist/Carrera29062022/pCOL7A_S1/COL7A.bam.bai is older than BAM /home/fer/./jvarkit/dist/Carrera29062022/pCOL7A_S1/COL7A.bam
[INFO][MiniCaller]Using default parameter for 'min.read.length'.
[SEVERE][MiniCaller]offset 83, count 84, length 151
java.lang.StringIndexOutOfBoundsException: offset 83, count 84, length 151
        at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
        at java.base/java.lang.String.<init>(String.java:591)
        at com.github.lindenb.jvarkit.tools.calling.MiniCaller.doWork(MiniCaller.java:433)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:796)
        at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:959)
        at com.github.lindenb.jvarkit.tools.calling.MiniCaller.main(MiniCaller.java:681)
[INFO][Launcher]minicaller Exited with failure (-1)`

We don't know what could be happening. Might be because of the warning about the bam file?

Thanks in advance

**Comment by lindenb** [comment]
hi thanks for using this tool and thank you for submitting this issue. I wrote this mostly for fun. May I ask why do you use it instead of bcftools or gatk ?

**Comment by fernanarr** [comment]
Hi!

We are trying to use it because we've read your article and your tool's features seems to suit to our needings and our data volume. 

We haven't tried bcftools or gatk

**Comment by lindenb** [comment]
@fernanarr I think I found the bug. I recently rewrote a large part of this software but my test was too simple. The bug is here:

https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/tools/calling/MiniCaller.java#L433


replace `+ new String(bases,readpos0,readpos0+len);`

with `+ new String(bases,readpos0,len);`

this fix is still in my dev branch (https://github.com/lindenb/jvarkit/tree/dev) , I'll move into master later.

**Comment by fernanarr** [comment]
great @lindenb!

It worked.

Thanks a lot for your help and for taking time to develop this tool.

Regards
