### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by SergeyBaikal** [lindenb/jvarkit#204]
Hello! I did everything as described in the manual.

**(base) sergey@debian:~/WGSCoveragePlotter$ git clone "https://github.com/lindenb/jvarkit.git"**
Cloning into 'jvarkit'...
remote: Enumerating objects: 74714, done.
remote: Counting objects: 100% (6740/6740), done.
remote: Compressing objects: 100% (2545/2545), done.
remote: Total 74714 (delta 2898), reused 6676 (delta 2838), pack-reused 67974
Receiving objects: 100% (74714/74714), 58.21 MiB | 6.16 MiB/s, done.
Resolving deltas: 100% (42097/42097), done.
**(base) sergey@debian:~/WGSCoveragePlotter$ cd jvarkit**
**(base) sergey@debian:~/WGSCoveragePlotter/jvarkit$ ./gradlew wgscoverageplotter**

> Task :wgscoverageplotter
Downloading https://repo1.maven.org/maven2/com/github/samtools/htsjdk/2.24.1/htsjdk-2.24.1.jar to /home/sergey/WGSCoveragePlotter/jvarkit/lib/com/github/samtools/htsjdk/2.24.1/htsjdk-2.24.1.jar

> Task :wgscoverageplotter FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/sergey/WGSCoveragePlotter/jvarkit/build.gradle' line: 109

* What went wrong:
Execution failed for wgscoverageplotter com.github.lindenb.jvarkit.tools.bam2graphics.WGSCoveragePlotter.
> java.net.ConnectException: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s
1 actionable task: 1 executed

**Comment by lindenb** [comment]
Hi, I suppose you're working behind a server proxy. Please see https://stackoverflow.com/a/22666646 to fix this.

**Comment by SergeyBaikal** [comment]
Yes, I specified my ports and proxies. But I get the same result.

./gradlew -Dhttp.proxyHost=100.0.0.1 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=100.0.0.1 -Dhttps.proxyPort=3128 "-Dhttp.nonProxyHosts=*.nonproxyrepos.com|localhost"

**Comment by lindenb** [comment]
@SergeyBaikal Hum.. I'm afraid it will be hard to debug :-)

what's the output of 

```
wget -O - "https://repo1.maven.org/maven2/com/github/samtools/htsjdk/2.24.1/htsjdk-2.24.1.jar " | file -
```

**Comment by lindenb** [comment]
anyway, I uploaded a fresh copy of the tool in https://uncloud.univ-nantes.fr/index.php/s/4sL77oWR2BFzSBH

**Comment by SergeyBaikal** [comment]
The program started, but swears at the input files. I am doing something wrong.

**java -jar dist/wgscoverageplotter.jar --dimension 1500x500 -C -1 --clip -R /home/sergey/WGSCoveragePlotter/jvarkit/575.fasta /home/sergey/WGSCoveragePlotter/jvarkit/aln_sort.bam --percentile median  > /home/sergey/WGSCoveragePlotter/jvarkit/plot.svg**
[SEVERE][WGSCoveragePlotter]Error opening file: /home/sergey/WGSCoveragePlotter/jvarkit/575.fasta
htsjdk.samtools.SAMException: Error opening file: /home/sergey/WGSCoveragePlotter/jvarkit/575.fasta


There are 3 files in the data folder.
Reference  575.fasta
575.fasta.fai
aln_sort.bam

**Comment by lindenb** [comment]
-R is for the fasta reference genome.

**Comment by lindenb** [comment]
575.dict is missing
al_sort.bam should be indexed

**Comment by lindenb** [comment]
that's a strange error anyway... what is the output of the following commands:

```
file  /home/sergey/WGSCoveragePlotter/jvarkit/*
head  /home/sergey/WGSCoveragePlotter/jvarkit/575.fasta
head  /home/sergey/WGSCoveragePlotter/jvarkit/575.fasta.fai
```

**Comment by SergeyBaikal** [comment]
How to get the file 575.dict?

**Comment by lindenb** [comment]
samtools dict or picard  CreateSequenceDictionary

but please, show me the output of the commands above please.

**Comment by SergeyBaikal** [comment]
```
file  /home/sergey/WGSCoveragePlotter/jvarkit/*
/home/sergey/WGSCoveragePlotter/jvarkit/575.fasta:        ASCII text, with very long lines, with CRLF line terminators
/home/sergey/WGSCoveragePlotter/jvarkit/575.fasta.fai:    ASCII text
/home/sergey/WGSCoveragePlotter/jvarkit/aln_sort.bam:     gzip compressed data, extra field, original size 0
/home/sergey/WGSCoveragePlotter/jvarkit/aln_sort.bam.bai: SAMtools BAI (BAM indexing format), with 1 reference sequences
/home/sergey/WGSCoveragePlotter/jvarkit/articles:         directory
/home/sergey/WGSCoveragePlotter/jvarkit/build.gradle:     C++ source, ASCII text
/home/sergey/WGSCoveragePlotter/jvarkit/CITATION.cff:     ASCII text
/home/sergey/WGSCoveragePlotter/jvarkit/conda:            directory
/home/sergey/WGSCoveragePlotter/jvarkit/dist:             directory
/home/sergey/WGSCoveragePlotter/jvarkit/doc:              directory
/home/sergey/WGSCoveragePlotter/jvarkit/docs:             directory
/home/sergey/WGSCoveragePlotter/jvarkit/gradle:           directory
/home/sergey/WGSCoveragePlotter/jvarkit/gradlew:          a /usr/bin/env sh script, ASCII text executable
/home/sergey/WGSCoveragePlotter/jvarkit/gradlew.bat:      DOS batch file, ASCII text, with CRLF line terminators
/home/sergey/WGSCoveragePlotter/jvarkit/jfx.mk:           HTML document, ASCII text
/home/sergey/WGSCoveragePlotter/jvarkit/lib:              directory
/home/sergey/WGSCoveragePlotter/jvarkit/LICENSE.txt:      ASCII text
/home/sergey/WGSCoveragePlotter/jvarkit/Makefile:         ASCII text
/home/sergey/WGSCoveragePlotter/jvarkit/Makefile.legacy:  ASCII text, with very long lines
/home/sergey/WGSCoveragePlotter/jvarkit/maven.mk:         ASCII text, with very long lines
/home/sergey/WGSCoveragePlotter/jvarkit/My_data:          directory
/home/sergey/WGSCoveragePlotter/jvarkit/NEWS.md:          ASCII text
/home/sergey/WGSCoveragePlotter/jvarkit/plot.svg:         empty
/home/sergey/WGSCoveragePlotter/jvarkit/README.md:        ASCII text
/home/sergey/WGSCoveragePlotter/jvarkit/settings.gradle:  ASCII text
/home/sergey/WGSCoveragePlotter/jvarkit/src:              directory
/home/sergey/WGSCoveragePlotter/jvarkit/tmp:              directory

```
```
head  /home/sergey/WGSCoveragePlotter/jvarkit/575.fasta
>MN940575.1 Dishui Lake viropahge 8, complete genome
ATGAATACTTCTATTCCCGATAAAGCAATTTTGAAAGACATGGCGGATGCCTCTTATCAAAATAATTATAGCGATACAATAGACGGGTTCAACCTTGTTCTTCAAACTGATACTTTAAAGTTTTTTCAATCTACATATCAACCTTTTTTCGTTGTTTCAGTAAGAGGCACAGCAGACTTCCAAGACTTCCAAGCATGGATTCCAAGTGCTATAAATAATATTCAAAATACAGAAAGATATAAAATTGATACTGACGAGTTGCTAAACTTCCAGCAACAGAATCCAACCAATATTTACACATATTATGCCGTAGGTCATTCACTAGCAGGAGCAATAATAGACGCATGGTTGAAAGCAGGTTATATTACAGAAGCAAGGACATATAATCCAGCAGTATCATATACAGATCTTAATAATGAAAATATAAATAATTACAGAGTTTATAGCGACGGAGACCCTTTGTATAACATTATGGGTAGATTTGTAAAAGGTAGAAAAGAAGTAAGATCATATGTCGTTCCAAATGTTAGATGGTGGAACATAAAGGATAGGATCTTGAA
```

```
head  /home/sergey/WGSCoveragePlotter/jvarkit/575.fasta.fai
MN940575.1	26605	54	26605	26606

```

**Comment by SergeyBaikal** [comment]
head 575.dist
@HD	VN:1.0	SO:unsorted
@SQ	SN:MN940575.1	LN:26605	M5:e3cb46cbb391cd7da2274f48249023af	UR:file:///home/sergey/samtools-1.9/My_data/575.fasta

**Comment by lindenb** [comment]
looks fine , although the fasta is a one line long, but it shouldn't be a problem (?)

isn't there any error message after

>  [SEVERE][WGSCoveragePlotter]Error opening file: /home/sergey/WGSCoveragePlotter/jvarkit/575.fasta
> htsjdk.samtools.SAMException: Error opening file: /home/sergey/WGSCoveragePlotter/jvarkit/575.fasta 
 
?

**Comment by SergeyBaikal** [comment]
Full output:
**java -jar dist/wgscoverageplotter.jar --dimension 1500x500 -C -1 --clip -R /home/sergey/WGSCoveragePlotter/jvarkit/My_data/575.fasta /home/sergey/WGSCoveragePlotter/jvarkit/My_data/aln_sort.bam --percentile median  > /home/sergey/WGSCoveragePlotter/jvarkit/My_data/plot.svg
[SEVERE][WGSCoveragePlotter]Could not find dictionary next to reference file file:///home/sergey/WGSCoveragePlotter/jvarkit/My_data/575.fasta**
htsjdk.samtools.SAMException: Could not find dictionary next to reference file file:///home/sergey/WGSCoveragePlotter/jvarkit/My_data/575.fasta
	at htsjdk.variant.utils.SAMSequenceDictionaryExtractor$TYPE$1.extractDictionary(SAMSequenceDictionaryExtractor.java:58)
	at htsjdk.variant.utils.SAMSequenceDictionaryExtractor.extractDictionary(SAMSequenceDictionaryExtractor.java:170)
	at com.github.lindenb.jvarkit.util.bio.SequenceDictionaryUtils.extractRequired(SequenceDictionaryUtils.java:184)
	at com.github.lindenb.jvarkit.tools.bam2graphics.WGSCoveragePlotter.doWork(WGSCoveragePlotter.java:289)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:795)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:958)
	at com.github.lindenb.jvarkit.tools.bam2graphics.WGSCoveragePlotter.main(WGSCoveragePlotter.java:617)
[INFO][Launcher]wgscoverageplotter Exited with failure (-1)

**Comment by lindenb** [comment]
> Could not find dictionary next to reference 

yeah... the dict file was missing....

**Comment by SergeyBaikal** [comment]
I added the file but the output is the same. Not sure how it should look right.
head 575.dist
@hd VN:1.0 SO:unsorted
https://github.com/sq SN:MN940575.1 LN:26605 M5:e3cb46cbb391cd7da2274f48249023af UR:file:///home/sergey/samtools-1.9/My_data/575.fasta

**Comment by lindenb** [comment]
the 575.dict should be in the same folder than 575.fa.

your command shows that the 575.fa was in home/sergey/samtools-1.9/My_data/ not in  /home/sergey/WGSCoveragePlotter/jvarkit/My_data/

?

**Comment by SergeyBaikal** [comment]
Sorry. I'm stupid. Instead of dict, I wrote dist...
Everything worked out! Great picture to post! Thank you!
