### ISSUE TITLE
Error while installing -- Running Javac

### ISSUE THREAD

**Issue by Auradhir** [lindenb/jvarkit#208]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

### Subject of the issue
I am trying to install BAMSTATS05 package which looks really cool but it is not possible. It stops at 
` Error running javac compiler`

I have come to know that I will not able to install any tool that uses JAVAC unfortunately since it is restricted access and sudo does not solve my issue as well.

Is there anyways to obtain the jar file for BAMSTATS05 or isntall it another way? 

### Your environment
* version of java- 11-0-13
* which OS UBUNTU

**Comment by lindenb** [comment]
sure, here is a link to a jar: https://uncloud.univ-nantes.fr/index.php/s/4sL77oWR2BFzSBH

**Comment by Auradhir** [comment]
This is very useful,

thanks!

Anu
________________________________
