### ISSUE TITLE
vcf2tab

### ISSUE THREAD

**Issue by mushalallam** [lindenb/jvarkit#211]
Hi, 
Do you aware about any tool which can convert the whole vcf file to tab or csv file.
Thanks

**Comment by lindenb** [comment]
VCF is a tab file. It's unrelated to jvarkit: for such questions ask [biostars.org](https://www.biostars.org/) or https://bioinformatics.stackexchange.com/ please.

**Comment by mushalallam** [comment]
Thanks @lindenb, I meant if one of the jvarkit tools can do the conversion.
