### ISSUE TITLE
./gradlew mapuniprot install error

### ISSUE THREAD

**Issue by wunalahu2** [lindenb/jvarkit#216]
### Subject of the issue
when I install mapuniprot as the methods described below:
http://lindenb.github.io/jvarkit/MapUniProtFeatures.html
the error has occured like this :
'
FAILURE: Build failed with an exception.
* Where:
Build file '/home/wunalahu/software/jvarkit/build.gradle' line: 343

* What went wrong:
Execution failed for mapuniprot com.github.lindenb.jvarkit.tools.misc.MapUniProtFeatures.
> Java returned: 255

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
'
and I debug it with the scripts "./gradlew mapuniprot --info > log"and the info written in log is 
'
[ant:java] [ERROR] The markup in the document preceding the root element must be well-formed.
[ant:java]   line 1 of https://www.uniprot.org/docs/uniprot.xsd
[ant:java] 
[ant:java] Failed to parse a schema.

> Task :mapuniprot FAILED
'

I'm wondering if the link 'https://www.uniprot.org/docs/uniprot.xsd' has been deprecated ?

### Your environment
my java version:
java -version
openjdk version "11.0.15" 2022-04-19
javac -version
javac 11.0.15
* the value of `${JAVA_HOME}`
JAVA_HOME="/usr/lib/jvm/java-11-openjdk-11.0.15.0.10-3.el8.x86_64/"
export PATH=${JAVA_HOME}/bin:${PATH}
* which OS
centos8

hope reply asap,thank you

**Comment by lindenb** [comment]
yes, you're right, the doc has moved . I changed it in the `dev` branch a few days ago: https://github.com/lindenb/jvarkit/commit/c3183aab41ff841e0d43bfab93f0f508426bfb49

**Comment by lindenb** [comment]
I've just merged `dev` into `master`. It should work now.

**Comment by wunalahu2** [comment]
> I've just merged `dev` into `master`. It should work now.

Thank you for your prompt reply.It has been built succesfully.
‘> Task :mapuniprot
jar file generated :/home/wunalahu/software/jvarkit/dist/mapuniprot.jar
No Test will be executed for mapuniprot

BUILD SUCCESSFUL in 22s’
