### ISSUE TITLE
Is it possible to add the 'Gene' and peptide 'POSITION(S)' info corresponding to each genomic coordinate using MapUniProtFeatures

### ISSUE THREAD

**Issue by wunalahu2** [lindenb/jvarkit#217]
Hi , lindenb
    I've successfully run MapUniProtFeatures ,and the top 10 line is exactly the same as in Example shown in http://lindenb.github.io/jvarkit/MapUniProtFeatures.html.
My question is 'is it possible to add the 'Gene' and peptide 'POSITION(S)' info corresponding to each genomic coordinate , I want the result to be formatted like the following
Gene	POSITION(S)	chr	start	          end	 TYPE                                     ....
OR4F5	1-18	               chr1	69090	69144	topological_domain              ....
OR4F5	19-42	       chr1	69144	69216	transmembrane_region         ....
OR4F5	43-50	       chr1	69216	69240	topological_domain              ....
The 'Gene' and peptide 'POSITION(S)' info should come from https://www.uniprot.org/
waiting for your reply ,thanks

**Comment by lindenb** [comment]
Hi,
how about using `bedtools intersect` ?

**Comment by wunalahu2** [comment]
Thank you for your prompt reply.
Using bedtools intersect may only get gene info for each genomic coordinate ,when I using WES bed as input .
But I cannot get the peptide positions .
My WES bed looks like as :
chr1	69090	69240	target1	OR4F5:exon1
chr1	69240	69390	target2	OR4F5:exon1
chr1	69390	69540	target3	OR4F5:exon1
chr1	69540	69690	target4	OR4F5:exon1
chr1	69690	69840	target5	OR4F5:exon1
chr1	69840	69990	target6	OR4F5:exon1
chr1	69990	70008	target7	OR4F5:exon1

**Comment by wunalahu2** [comment]
Actually ,I want to add the genomic coordinates to each protein domain

**Comment by lindenb** [comment]
Sorry, I won't have the time to work on this.

**Comment by wunalahu2** [comment]
That's all right. Thank you all the same
by the way ,can you share me your email address ?i want to ask some info about  MapUniProtFeatures

**Comment by wunalahu2** [comment]
it doesn't matter，thank you very much for your prompt reply.
