### ISSUE TITLE
PreCompiled binaries?

### ISSUE THREAD

**Issue by apelin20** [lindenb/jvarkit#22]
Any chance you can precompile this for a few OS systems? Getting ant to work is a pain. I know I spend a day getting it right on one machine but forgot what was the fix and now have to do it again.

**Comment by lindenb** [comment]
I switched from Ant to Make yesterday...  https://github.com/lindenb/jvarkit/commit/c9671c904fe8e56e36e71ef81b6dfcb423523dc1

**Comment by apelin20** [comment]
I really want to believe you:) Really really want to....

http://pastebin.com/ri3mfzxG

**Comment by lindenb** [comment]
>  Suggestion, maybe a ./configure implementation to check for dependencies?

this is a problem with the htsjdk library, not from my program.

Your last error is in:

```
/home/adrian/programs/jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/backlocate
        private Map<String,Set<String>> geneSymbol2kg=new HashMap<>();
````

instead of `java -v` , show me `javac -version` . (java != javac)  I'm pretty sure that your javac is outdated.

**Comment by apelin20** [comment]
Yeah you are right I fixed that, see EDIT3. Now I have this problem:
@BioPower3-IBM ~/programs/jvarkit $ make bamsnvwig
make: *** No rule to make target `/home/adrian/programs/jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/mem/BWAMemScan.java', needed by `bamsnvwig'.  Stop.

make seems to run into that after compiling banrenamechr:
http://pastebin.com/sCw4ZVvZ

**Comment by lindenb** [comment]
As I said in https://github.com/lindenb/jvarkit/wiki/Compilation

> the target 'all' exists in the Makefile but it will generate a large number of tools I don't use/maintain anymore.

don't try to build all tools, just build what you need.

**Comment by lindenb** [comment]
I've pushed a message about this: https://github.com/lindenb/jvarkit/commit/95427139ae896b3d582ba046943aff22425f4c8d

**Comment by apelin20** [comment]
Good one :) Thanks for the help!
