### ISSUE TITLE
questions about sam2tsv output file

### ISSUE THREAD

**Issue by seven1112233** [lindenb/jvarkit#224]
Dear author:
Your tool-sam2tsv is helpful. I try to convert bam file to tsv with this tool and something strange happen. The same output tsv files have some lines not be seen in the linux platform but be seen in the windows(or R) as the figure shows. Why? i am so confused. I am looking forward to your reply! Thank you very much!
same file in linux
![1670381744268](https://user-images.githubusercontent.com/71070001/206077033-6de6cbd2-eae8-4ddb-a312-3515803b8718.png)

same file in windows(wps)(line 62 can not be seen in linux)
![1670381767649](https://user-images.githubusercontent.com/71070001/206077061-5eb70c83-46f9-400c-a772-2de7951897c6.png)

**Comment by lindenb** [comment]
> The same output tsv files have some lines not be seen in the linux platform but be seen in the windows(or R) as the figure shows. Why? 

problem of delimiter when importing in excel.

don't use excel.

**Comment by seven1112233** [comment]
Thanke you for your reply. But actually I need work with these bam2sv files using R. I use read.csv(sep="\t") to read bam2tsv files in R, which showing the same problem as in the excel. How I solve this problem?

**Comment by seven1112233** [comment]
I find the reason why the problem happens. ref_QUAL have some records including double quatation marks. Quotation marks(") which make "\tvalue\tvalue" as one character. So when I using R or python work with this file I get something wrong.


Dinasour
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lindenb/jvarkit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月8日(星期四) 凌晨0:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lindenb/jvarkit] questions about sam2tsv output file (Issue #224)





 
it might be a bug ?
 
what is the output of
 awk -F '\t' '{print NF}' sam2tsv.output.tsv | sort | uniq   
?
