### ISSUE TITLE
Biostar139647 : documentation issues

### ISSUE THREAD

**Issue by blinard-BIOINFO** [lindenb/jvarkit#227]
### Subject of the issue
Biostar139647 : documentation issues
- Documentation should comment that the format conversion does not allow to select a reference from inside the clustal alignment
- Documentation should comment that Insertions are not handled, only matches and Deletions
- Documentation should comment that heading and trailing gaps are NOT consider as real indels (compared to a virtual reference genome) but start/ends of mapped reads

### Steps to reproduce
If one of the alignment sequence is considered as the reference genome, then the output sam is incorrect (because no alignment sequence can be selected as reference)? In particular, insertions  to the reference are not handled.

### Expected behaviour
This is fine, but should be clarified in the documentation.

**Comment by lindenb** [comment]
Thanks feel , that was a tool made quickly for biostars.org , but fell free to submit a PR to insert all those informations.

**Comment by blinard-BIOINFO** [comment]
Answer in PR #228
