### ISSUE TITLE
jvarkit as conda package

### ISSUE THREAD

**Issue by ausserh** [lindenb/jvarkit#230]
Dear Pierre,

thank you for your great tool! 

Are there any current plans to release the full tool, with all available functions, as conda package, or within a singularity container?

Thank you and many wishes,
Markus

**Comment by lindenb** [comment]
@ausserh Hi, I wrote the singularity def here: https://github.com/lindenb/jvarkit/blob/master/singularity.def  . It works, but for now it's not available for download anywhere. Where should I upload this ?

I would love to see it in conda but I'm too old to understand how to package it :-P

**Comment by lindenb** [comment]
I tried this today: https://hub.docker.com/repository/docker/lindenb/jvarkit/general

**Comment by DrYak** [comment]
Hi!

> I would love to see it in conda but I'm too old to understand how to package it :-P

I happen to not be _too old for conda packaging_, but I am too much of a C/C++ and Perl guy to be fluent in Java ;-)  so I might need your help to package it.

### First question

Could you tag the latest version? 
- (bioconda only accept tagged tarballs, you're not supposed to clone random commits)
- from what I see, the last tag (2021.10.13)  is from ages ago.
- the latest master commit 3d336e522b2862e7f9490bbdfc80b219e68532e2 fails to build, complaining about _vcfregulomedb_-something
- the one before 5218c135534921738e254c94c411126d15b9594c seems to build
- the latest dev commit (713d5cf46a39ceaa295528c77199825f39c87b9a, from sep 4th) seems to build.

### Context

in [our virus pipeline](https://github.com/cbg-ethz/V-pipe), some of [our haplotype tools](https://github.com/LaraFuhrmann/VILOCA) don't scale very well to extremely high coverage, and we would like to use [Biostar154220](https://lindenb.github.io/jvarkit/Biostar154220.html) to cap coverage, and bioconda is a hard requirement for us.

### PS

Je suis aussi francophone si c'est plus simple.

**Comment by lindenb** [comment]
@DrYak thanks ! I'm away from my code but I'll add a tag tomorrow.
( The current working  branch is `dev` , I will merge into master too).

**Comment by lindenb** [comment]
@DrYak and here is a new release: https://github.com/lindenb/jvarkit/releases/tag/v2023.09.07

**Comment by DrYak** [comment]
Thanks! I'll take it from there...

**Comment by DrYak** [comment]
Here is the pull request:
https://github.com/bioconda/bioconda-recipes/pull/42902

I'll see what the reviewers advise:
- I don't have that much experience with Java
- The bioconda devs should also think what they do with the old "jvarkit-_{xxx}_" packages back from when each tool was its own jar.

Note:
-  I'm adding also per-tool wrapper that map "_{tool}_" to "jvarkit _{tool}_", e.g., `biostar154220` wraps `jvarkit biostar154220`
- I am doing the simple `--help` tests in the meta.yaml.
- I've left  the `-Xms512m -Xmx2g` memory settings that already existed in piccardtools' wrapper as-is (I'm not fluent in Java enough to understand if that should have been changed).

**Comment by lindenb** [comment]
thanks, best luck with that !

**Comment by DrYak** [comment]
Forgot to mention,  but the pull request got merged.
It's now possible to install `jvarkit` from bioconda with, e.g.:

```bash
# create an environment called 'jvkenv', and put jvarkit in it
conda create -n jvkenv -c conda-forge -c bioconda jvarkit

# activate the environmnet
conda activate jvkenv

# run
jvarkit --help
```

**Comment by DrYak** [comment]
As of note for the future:
Bioconda has a bot that automatically looks at tagged releases and suggest pull-requests to bump the package recipes to the newest version.
So whenever a new version is tagged, and if the package successfully build with this new version (e.g. there isn't a new dpendency that needs to be added to the recipe), the bioconda reviewer will get an update to check and merge, without any upstream intervention.

**Comment by lindenb** [comment]
@DrYak wonderful ! Thank you so much !
