### ISSUE TITLE
Task 'sortsamrefname' not found in root project 'jvarkit'.

### ISSUE THREAD

**Issue by Leo-ccc** [lindenb/jvarkit#231]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java
 openjdk version "11.0.9.1-internal" 2020-11-04

### Subject of the issue
Task 'sortsamrefname' not found in root project 'jvarkit'.

### Your environment
* version of jvarkit
The latest, version : ff1864e17 
* version of java
openjdk version "11.0.9.1-internal" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.9.1-internal+0-adhoc..src, mixed mode)
* the value of `${JAVA_HOME}`
/work/my-account/miniconda3
* which OS
Linux

### Steps to reproduce
./gradlew sortsamrefname

### Expected behaviour
Tell us what should happen

### Actual behaviour
FAILURE: Build failed with an exception.

* What went wrong:
Task 'sortsamrefname' not found in root project 'jvarkit'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Thank you!

**Comment by lindenb** [comment]
It's available in the `dev` branch of jvarkit:

```
$ java -jar dist/jvarkit.jar sortsamrefname -h
Usage: sortsamrefname [options] Files
  Options:
    --bamcompression
      Compression Level. 0: no compression. 9: max compression;
      Default: 5
    -h, --help
      print help and exit
    --helpFormat
      What kind of help. One of [usage,markdown,xml].
    --maxRecordsInRam
      When writing  files that need to be sorted, this will specify the number 
      of records stored in RAM before spilling to disk. Increasing this number 
      reduces the number of file  handles needed to sort a file, and increases 
      the amount of RAM needed
      Default: 50000
    -o, --out
      Output file. Optional . Default: stdout
    -R, --reference
      Indexed fasta Reference file. This file must be indexed with samtools 
      faidx and with picard CreateSequenceDictionary
    --regions
      Limit analysis to this interval. A source of intervals. The following 
      suffixes are recognized: vcf, vcf.gz bed, bed.gz, gtf, gff, gff.gz, 
      gtf.gz.Otherwise it could be an empty string (no interval) or a list of 
      plain interval separated by '[ \t\n;,]'
    --samoutputformat
      Sam output format.
      Default: SAM
      Possible Values: [BAM, SAM, CRAM]
    --tmpDir
      tmp working directory. Default: java.io.tmpDir
      Default: []
    --validation-stringency
      SAM Reader Validation Stringency
      Default: LENIENT
      Possible Values: [STRICT, LENIENT, SILENT]
    --version
      print version and exit

```

**Comment by lindenb** [comment]
and it's now in the 'master' branch.

**Comment by Leo-ccc** [comment]
I found it! Thank you so much !!! 👍
