### ISSUE TITLE
Build error: failed to create jvarkit.jar object

### ISSUE THREAD

**Issue by Gilquin** [lindenb/jvarkit#238]
### Subject of the issue
Error encountered during compilation when running:
```java
./gradlew jvarkit
```

### Your environment
* version of jvarkit: 
[https://github.com/lindenb/jvarkit/tree/3d336e522b2862e7f9490bbdfc80b219e68532e2](https://github.com/lindenb/jvarkit/tree/3d336e522b2862e7f9490bbdfc80b219e68532e2)
* version of java: 
 ```bash
 $ java --version
 openjdk 11.0.16 2022-07-19
 OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb11u1)
 OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb11u1, mixed mode, sharing)
 ```
* the value of `${JAVA_HOME}`: undefined.
* which OS:
```bash
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

### Steps to reproduce
Follow the [documentation steps](https://jvarkit.readthedocs.io/en/latest/JvarkitCentral/#download-and-compile).

### Expected behaviour
The `jvarkit.jar` should be created without errors.

### Actual behaviour
Build fails with error:
```
[ant:javac] ./jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/tbi2bed/VcfTbiToBed.java:216:
error: package com.github.lindenb.jvarkit.tools.vcfregulomedb does not exist
```
See [corresponding scan](https://gradle.com/s/esdaruxt4nrim) for complete report and log.

**Comment by lindenb** [comment]
@Gilquin hi laurent.

It works on my machine using the branch 'dev' and a fresh install:

```
git clone -b dev "https://github.com/lindenb/jvarkit.git"
```

could you please try with this branch ?

**Comment by Gilquin** [comment]
Hello,

Unfortunately, I get two new errors this time:
```
[ant:javac] /home/lgilquin/softwares/jvarkit/src/main/java/com/github/lindenb/jvarkit/variant/VcfSpringBeanVariantAnnotator.java:35: error: cannot access ApplicationContext
[ant:javac] import org.springframework.context.ApplicationContext;
[ant:javac]                                   ^
[ant:javac]   bad class file: /home/lgilquin/softwares/jvarkit/lib/org/springframework/spring-context/6.0.9/spring-context-6.0.9.jar(/org/springframework/context/ApplicationContext.class)
[ant:javac]     class file has wrong version 61.0, should be 55.0
[ant:javac]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ant:javac] /home/lgilquin/softwares/jvarkit/src/main/java/com/github/lindenb/jvarkit/variant/VcfSpringBeanVariantAnnotator.java:36: error: cannot access FileSystemXmlApplicationContext
[ant:javac] import org.springframework.context.support.FileSystemXmlApplicationContext;
[ant:javac]                                           ^
[ant:javac]   bad class file: /home/lgilquin/softwares/jvarkit/lib/org/springframework/spring-context/6.0.9/spring-context-6.0.9.jar(/org/springframework/context/support/FileSystemXmlApplicationContext.class)
[ant:javac]     class file has wrong version 61.0, should be 55.0
[ant:javac]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Here is the [new scan](https://scans.gradle.com/s/5mxvf5wtnucwc)

**Comment by Gilquin** [comment]
> BTW a pre-compiled jar is available at https://uncloud.univ-nantes.fr/index.php/s/4sL77oWR2BFzSBH .

Yes, I saw that option, thanks!

> yes please, try with java 17:
> 
> https://stackoverflow.com/questions/74648576/spring-class-file-has-wrong-version-61-0-should-be-55-0

I will try with java 17 later on. I will close the issue.
