### ISSUE TITLE
BamStats04 does not recognize IN= or I=

### ISSUE THREAD

**Issue by apelin20** [lindenb/jvarkit#24]
Hello,
This is a bit odd:

@BioPower3-IBM ~/Rozella/mapping $ ll
total 17G
drwxrwxr-x. 2 adrian adrian 4.0K Mar 26 15:15 .
drwxrwxr-x. 6 adrian adrian 4.0K Mar 26 12:33 ..
-rw-rw-r--. 1 adrian adrian    0 Mar 26 15:18 Contig_coverage.table
-rw-rw-r--. 1 adrian adrian  23K Mar 26 14:39 Contig_ranges2.bed
-rw-rw-r--. 1 adrian adrian  25K Mar 26 14:34 Contigs.stats
-rw-rw-r--. 1 adrian adrian 6.5G Mar 26 13:39 Rozella.bam
-rw-rw-r--. 1 adrian adrian 5.1G Mar 26 14:16 Rozella.sort.bam
-rw-rw-r--. 1 adrian adrian 5.1G Mar 26 14:57 Rozella.sort.grp.bam
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 15:22:35
@BioPower3-IBM ~/Rozella/mapping $ ~/programs/jvarkit/dist-1.128/bamstats04 IN=Rozella.sort.grp.bam BED=Contig_ranges2.bed VALIDATION_STRINGENCY=LENIENT > Contig_coverage.table
ERROR: Option 'IN' is required.
...
@BioPower3-IBM ~/Rozella/mapping $ ~/programs/jvarkit/dist-1.128/bamstats04 IN=Rozella.sort.grp.bam BED=Contig_ranges2.bed 
ERROR: Option 'IN' is required.
...
@BioPower3-IBM ~/Rozella/mapping $ ~/programs/jvarkit/dist-1.128/bamstats04 IN="Rozella.sort.grp.bam" BED=Contig_ranges2.bed VALIDATION_STRINGENCY=LENIENT > Contig_coverage.table
ERROR: Option 'IN' is required.
...
@BioPower3-IBM ~/Rozella/mapping $ ~/programs/jvarkit/dist-1.128/bamstats04 I=Rozella.sort.grp.bam BED=Contig_ranges2.bed VALIDATION_STRINGENCY=LENIENT > Contig_coverage.table
ERROR: Option 'IN' is required.
...

Any idea what could be going on? I tried other BAM files too, same issue.
Adrian

**Comment by lindenb** [comment]
yes there was a bug in my Makefile creating the bash wrapper, I fixed it a few days ago: https://github.com/lindenb/jvarkit/commit/fe6480ef56d91e683467200bbe805a726c4c6457

you could also just use the jar command:
```java -jar ~/programs/jvarkit/dist-1.128/bamstats04.jar I=Rozella.sort.grp.bam BED=Contig_ranges2.bed VALIDATION_STRINGENCY=LENIENT
```

tell me if that works.

**Comment by apelin20** [comment]
It does indeed! I also recompiled and the binary also works now. Thanks!
