### ISSUE TITLE
[minicaller] error message of too many open files 

### ISSUE THREAD

**Issue by tingchenlrx** [lindenb/jvarkit#248]
I followed the instruction to compile the latest Version of jvarkit and called minicaller to call variants from a bam file. Error of too many open files popped up. We set the ulimit -n 32766 in the Linux sever. 

We had an older version of minicaller which is a standalone java tool (minicaller version 6d7e78cc3) and we ran the same bam file using this minicaller and it went through very smoothly.

The bam file is about 400MB with 26240456 alignments. 

My question is:
1. For the latest version of minicaller, how can we resolve the “open too many files” issue? Shall we need to continue to increase the number of open file descriptors? If so, can you please advise?

2. for the old minicaller version we had, is that possible that we can re-download it from your repository? We need to validate this version so a known link for the download is required here. Actually we would prefer the old version. 

### Our environment
* the latest version of jvarkit ( 69ca18e)
* openJDK Java Version 22
* REHL9

Thanks!  

Best,
Ting

**Comment by lindenb** [comment]
@tingchenlrx Hi, I'm sorry for that error. You should work on small intervals and then concatenate all the resulting VCFs, you can also play with     --maxRecordsInRam . If you really want the old version you can extract your version using git. But , sorry, I won't spend some time on this barely used  tool .

(closing)
