### ISSUE TITLE
[Feature Request] Change to REF using Biostar404363

### ISSUE THREAD

**Issue by Shians** [lindenb/jvarkit#254]
I am in a situation where I have a ClinVar VCF and I want to change all pathological variants in my BAM files into the REF (or N if possible) in order to not reveal any genomic vulnerabilities not relevant to my study. I think the tool currently only changes REF to ALT, would it be possible to go backwards?

I tried switching the REF and ALT columns for this purpose, but there are multiple entires where the there are multiple lines with the same position and different ALT, this seems to trigger an error. I can manually split out any multi-rows and do multiple passes, but I am hoping this could become a tool feature.

**Comment by lindenb** [comment]
Hi,
how about 'just' swapping REF and ALT ?
`
 bcftools view in.vcf -G  |  bcftools annotate -x 'QUAL,INFO,FILTER,ID' | awk '/^#/ {print;next;} {OFS="\t";$5=$4;$4="N";print;}'`

**Comment by Shians** [comment]
The issue (I think) from switching columns is that ClinVar may have multiple SNPs on the same position on different rows. I don't think the program liked the duplicate positions or the conflicting REFs.

I was going to remove all duplicate positions but I realised that will only mask one of the SNPs. I think I will end up having to create 4 VCFs with all 4 bases as REF and N as ALT then run the program 4 times.

**Comment by lindenb** [comment]
in my command above, there is just one REF used as ALT. Just use sort|uniq if there is any dup.

**Comment by Shians** [comment]
Oh I see, I didn't realize that you set REF to N which covers all cases. This solves the problem of me having to rerun multiple times with the different possible REF. Thanks!
