### ISSUE TITLE
no valid chromosome was found in ./D***_HiFi01_hifiasm.bp.p_ctg.fa

### ISSUE THREAD

**Issue by jiangqiuqiuu** [lindenb/jvarkit#255]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

### Subject of the issue
I was planning to plot the coverage of the largest 10 contigs, however I keep getting message like no valid chromosome was found in ./D***_HiFi01_hifiasm.bp.p_ctg.fa file. 

### Your environment
* version of jvarkit: d7e61cd3b
* version of java : openjdk 22.0.1-internal 2024-04-16
* the value of `${JAVA_HOME}`: /*****/users/********/miniforge3/lib/jvm
* which OS: CentOS Linux release 8.4.2105

### Steps to reproduce
My shell script here:
reference=./***_HiFi01_hifiasm.bp.p_ctg.fa
bam=./****_HiFi01_HiFi.p_ctg.sorted.bam
chr=(ptg002626c|ptg000396l|ptg000019l|ptg000227l|ptg001209l|ptg000088l|ptg001063l|ptg000810l|ptg000615l|ptg000445l)

java -jar /****/users/****/jvarkit.jar wgscoverageplotter \
    -W 10000 \
    --dimension 1500x500 \
    -C -1 \
    --clip \
    -R $reference \
    $bam \
    --include-contig-regex $chr \
    --percentile median \
    -o ~/jeter_3.svg

### Expected behaviour
I should be able to get a plot.

### Actual behaviour
[SEVERE][WGSCoveragePlotter]no valid chromosome was found in ./D***_HiFi01_hifiasm.bp.p_ctg.fa
[INFO][Launcher]wgscoverageplotter Exited with failure (-1)

Thanks for your help!

**Comment by lindenb** [comment]
hi,
try to quote  --include-contig-regex

not

`--include-contig-regex $chr`

but

 

`--include-contig-regex "$chr" `


if it still not works, please show me the output of

`grep -E '(ptg002626c|ptg000396l|ptg000019l|ptg000227l|ptg001209l|ptg000088l|ptg001063l|ptg000810l|ptg000615l|ptg000445l)' ./_HiFi01_hifiasm.bp.p_ctg.fa.fai`

**Comment by jiangqiuqiuu** [comment]
Hi,

Thanks a lot for your reply! Here I paste the output of request here:

```
grep -E '(ptg002626c|ptg000396l|ptg000019l|ptg000227l|ptg001209l|ptg000088l|ptg001063l|ptg000810l|ptg000615l|ptg000445l)' ./Dpor_HiFi01_hifiasm.bp.p_ctg.fa.fai
ptg000019l	516761	1411551	516761	516762
ptg000088l	413904	8865903	413904	413905
ptg000227l	451020	22859987	451020	451021
ptg000396l	576288	38171781	576288	576289
ptg000445l	388490	42771556	388490	388491
ptg000615l	396544	60277029	396544	396545
ptg000810l	402924	77839206	402924	402925
ptg001063l	404744	99962683	404744	404745
ptg001209l	415159	112044763	415159	415160
ptg002626c	643513	217388934	643513	643514



```

I got a new error message when I adopted your suggestion using "$chr" instead of $chr;
```
./plot.sh: line 4: syntax error near unexpected token `|'
./plot.sh: line 4: `chr=(ptg002626c|ptg000396l|ptg000019l|ptg000227l|ptg001209l|ptg000088l|ptg001063l|ptg000810l|ptg000615l|ptg000445l)'
[INFO][WGSCoveragePlotter]Will plot the following contigs:ptg000001l, ptg000002l, ptg000003l, ptg000004l, ptg000005l, ptg000006l, ptg000007l, ptg000008l, ptg00........................... ptg005455l, ptg005456l, ptg005457l, ptg005458l, ptg005459l, ptg005460l, ptg005461l, ptg005462l, ptg005463l, ptg005464l, ptg005465l, ptg005466l, ptg005467l, ptg005468l, ptg005469l, ptg005470l, ptg005471l, ptg005472l, ptg005473l, ptg005474l, ptg005475l, ptg005476l, ptg005477l, ptg005478l
[SEVERE][WGSCoveragePlotter]pixel per base <=0 with drawing-width:1390.0 distance-between-contigs:1.0 n-chromosomes:5478 genome-length:328139589
java.lang.IllegalStateException: pixel per base <=0 with drawing-width:1390.0 distance-between-contigs:1.0 n-chromosomes:5478 genome-length:328139589
	at com.github.lindenb.jvarkit.tools.bam2graphics.WGSCoveragePlotter.doWork(WGSCoveragePlotter.java:359)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:735)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:898)
	at com.github.lindenb.jvarkit.tools.bam2graphics.WGSCoveragePlotter.main(WGSCoveragePlotter.java:651)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral$Command.execute(JvarkitCentral.java:355)
	at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.run(JvarkitCentral.java:911)
	at com.github.lindenb.jvarkit.tools.jvarkit.JvarkitCentral.main(JvarkitCentral.java:922)
[INFO][Launcher]wgscoverageplotter Exited with failure (-1)
```
I do appreciate your help!

Best
Qiuyu

**Comment by lindenb** [comment]
>  pixel per base <=0 with drawing-width:1390.0

you have one or more chromosome that cannot be displayed it would be less than one pixel wide.

increase the dimension of the drawing using option: 

    --dimension
      a dimension can be specified as '[integer]x[integer]' 


but there is an error in your script:

`./plot.sh: line 4: syntax error near unexpected token `|'`

you'd better add `set -eo pipefail` at the top of your script

**Comment by jiangqiuqiuu** [comment]
Hi,

I was able to get the plot! Thanks for your help.

Best
Qiuyu
