### ISSUE TITLE
blastn2snp problem

### ISSUE THREAD

**Issue by mrb20045** [lindenb/jvarkit#26]
Hi
when  two or more SNPs are beside each other, blastn2snp reports them in one line like this:

No definition line    Homo sapiens chromosome 6, alternate assembly CHM1_1.1    1    9    21    74567818    -    TAG    ATC    18    A TC   TAG    .|.

Is it possible blastn2snp reports each snp separately ? I really need it.
Thanks

Best

**Comment by lindenb** [comment]
I'm away from my code: try to change '3' to '2' (or "1" ?) in https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/tools/blast/BlastNToSnp.java#L175 and recompile

**Comment by mrb20045** [comment]
Thanks. I modified the BlastNToSnp.java based on your suggestion and recompiled. But the problem is not fixed. there is another way ?

Best

**Comment by lindenb** [comment]
I've added a new option `-n (int)` try to run this tool with `-n 0` https://github.com/lindenb/jvarkit/commit/19072426981ab0f13e61755012a4a35da591cc95

**Comment by mrb20045** [comment]
Dear Pierre 
Thanks for your great support. the problem is not fixed yet with your improvement. I recompiled and ran the software with -n 0. but in some cases mismatches are reported as two or three like:

1:213087129-213087330(+)  gi|229627866  298        1          101        298      +       T          A           97                  T              A                .
1:213087129-213087330(+)  gi|229628918  115        1          101        113      +       C          A           159                 C              A                .
1:213087129-213087330(+)  gi|229630731  7          1          101        262      -       TG         CT          192                 CA             AG               ..
1:213087129-213087330(+)  gi|229631360  26         1          101        200      -       TGG        CCT         201                 CCA            AGG              ...

Can you fixed the problem please ?
Thanks again for your help.

Best

**Comment by lindenb** [comment]
No, sorry I won't fix this; this is clearly not a SNV but a di/tri nucleotide change. 
You can always try to remove the lines 204-209 https://github.com/lindenb/jvarkit/blob/19072426981ab0f13e61755012a4a35da591cc95/src/main/java/com/github/lindenb/jvarkit/tools/blast/BlastNToSnp.java#L204-L209

**Comment by mrb20045** [comment]
Thanks for your help. I removed the mentioned lines but the problem was not fixed. however i fixed it by my script. Thanks again for your support.

Best
