### ISSUE TITLE
Error building 'mapuniprot'

### ISSUE THREAD

**Issue by marc-sturm** [lindenb/jvarkit#27]
Hi Pierre,

I get the error below when I try to build the mapuniprot tool. Other tools can be built.
I'm behind a proxy, which might be the problem, but I could not find the local.mk file referenced by the documentation...

Cheers,
  Marc

>make mapuniprot
mkdir -p /mnt/SRV017/share/data/dbs/UniProt/jvarkit/src/main/generated-sources/java
xjc -d /mnt/SRV017/share/data/dbs/UniProt/jvarkit/src/main/generated-sources/java -p org.uniprot  "http://www.uniprot.org/support/docs/uniprot.xsd"
parsing a schema...

(process:3234): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
//bin/dbus-launch terminated abnormally with the following error: Autolaunch error: X11 initialization failed.

GConf Error: No D-BUS daemon running

**Comment by lindenb** [comment]
I cannot do much without any error message....

**Comment by marc-sturm** [comment]
Hi Pierre,

sorry, accidentally hit the enter button.
I updated the issue now :)

Cheers,
  Marc

>>> Pierre Lindenbaum <notifications@github.com> 04.05.2015 15:21 >>>

I cannot do much without any error message....

**Comment by lindenb** [comment]
are you running inside docker ?  see http://stackoverflow.com/questions/29794731/running-jaxb-xjc-in-dockerfile-yields-in-gconf-error  . Anyway, this is an error related to your system. I can't do much about this.

if you're working behind a proxy , you've to write the local.mk yourself.

something like:
```
$ cat ~/src/jvarkit-git/local.mk
http.proxy.port=1234
http.proxy.host=somewhere.org
```

**Comment by marc-sturm** [comment]
Hi Pierre,

thanks, it was the proxy config that was missing and the wrong version or xjc.

Thanks for the help!

>>> Pierre Lindenbaum <notifications@github.com> 04.05.2015 15:49 >>>

are you running inside docker ? see http://stackoverflow.com/questions/29794731/running-jaxb-xjc-in-dockerfile-yields-in-gconf-error . Anyway, this is an error related to your system. I can't do much about this.
if you're working behind a proxy , you've to write the local.mk yourself.
something like:
$ cat ~/src/jvarkit-git/local.mk
http.proxy.port=1234
http.proxy.host=somewhere.org

**Comment by lindenb** [comment]
I'm glad it works now.
