### ISSUE TITLE
Feature request Biostar77288 - different visualisation possible ?

### ISSUE THREAD

**Issue by colindaven** [lindenb/jvarkit#28]
Hi,

thanks for the nice tools.

I wonder if it would be easy to implement a different visualisation for this tool. At the moment it is a 3D cylinder shape, yet in my view a 2D shape (i.e. similar to the ncbiblast visualisation bars) would be more effective at data display.

For example, with indel rich data (eg pacbio before quiver) the 3d ends really overexaggerate the 1bp tiny indels even when looking at long alignments, and thereby obscure other data.

Thanks,
Colin

**Comment by lindenb** [comment]
fixed in https://github.com/lindenb/jvarkit/commit/e10fc9d73c4156d1047670df50078eaf1e6242c9
there's now a new option : `-r` to disable styling.

note: I've changed the command line: it's more standard now.

**Comment by colindaven** [comment]
Wow, that went quick. Thank you very much. We'll download and try it out.

Best wishes,
Colin

**Comment by lindenb** [comment]
Hoops, I forgot to commit the right file ! Fixed now: https://github.com/lindenb/jvarkit/commit/4e10a0934f4a75b88c802583a8e19b1c228438fc
