### ISSUE TITLE
biostart94573.jar appears to hang (S+ state)

### ISSUE THREAD

**Issue by djrotenberg** [lindenb/jvarkit#29]
We have recently installed jvarkit, specifically to utilize biostart94573 to convert files. 

However, in our case the program appears to hang, remaining in the S+ state.

We just wanted to check whether this program does indeed require a good deal of time and memory, or if there is likely something wrong with our installation/implementation, or further if we are using this tool incorrectly.

 Our system in a 12 core, 200GB RAM, CENTOS 6.0 Linux system.

Example:

[root@dev01]$ /quarantine/BioStar/java_1.7/jdk1.7.0_79/bin/java -jar /quarantine/BioStar/build/jvarkit/dist-1.133/biostar94573.jar euro_samples_fasta_clustalw.aln  [INFO/Biostar94573] 2015-07-14 16:45:47 "Starting JOB at Tue Jul 14 16:45:47 EDT 2015 com.github.lindenb.jvarkit.tools.biostar.Biostar94573 version=ee95fe6971b5655c61d7feb22e8fa877201a9ca6  built=2015-07-06:11-07-10"
[INFO/Biostar94573] 2015-07-14 16:45:47 "Command Line args : euro_samples_fasta_clustalw.aln"
[INFO/Biostar94573] 2015-07-14 16:45:47 "Executing as root@dev01 on Linux 2.6.32-504.12.2.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.7.0_79-b15"
[INFO/Biostar94573] 2015-07-14 16:45:47 "Reading from euro_samples_fasta_clustalw.aln"
[INFO/Biostar94573] 2015-07-14 16:45:47 "format : Clustal"

**Comment by lindenb** [comment]
it should be OK ?
could you please show me the file "euro_samples_fasta_clustalw.aln"   ? my mail is "plindenbaum yahoo fr" if you want to send it by mail

**Comment by lindenb** [comment]
ok, your input doesn't look like the files I've tested before : numbers at the end of the lines, last entry NC_01xxx is not padded and no consensus as the last line. Could you please try to get a file like https://raw.github.com/biopython/biopython/master/Tests/Clustalw/opuntia.aln ?

**Comment by djrotenberg** [comment]
The file to which you directed us works well, with very quick output! In this case it would appear that it is indeed our input file that is causing the issue. Thank you so much for your assistance!
