### ISSUE TITLE
Genotyping of all positions

### ISSUE THREAD

**Issue by Coryza** [lindenb/jvarkit#30]
Hi Pierre,

Thanks for this! Would it be possible to output EVERY position on the reference as VCF format? (no coverage = ./., and if same as reference = 0/0)? Otherwise I can't merge VCF files of different samples together....

**Comment by Coryza** [comment]
Besides this: Is it possible to treat ONE 'clustalo' file as 1 sample? So lets say a MSA of 5 sequences gives only 1 genotype per position.

**Comment by lindenb** [comment]
I've added an option '-a' to print all sites : https://github.com/lindenb/jvarkit/commit/23fba7842bcbe1b02bcb58ebfe8f9210faaa1d73 . Tell me if it works please.

Not sure I understand your second comment; why don't you just concatenate all your fasta files ?

P.
