### ISSUE TITLE
biostar94573 reference sequence reading issue

### ISSUE THREAD

**Issue by vfgoliveira** [lindenb/jvarkit#33]
Hi Pierre,

The option -c to specify the name of the sequence to be used as reference to biostar94573 is working ok. However, I still have a issue. For my reference sequence I don't have insertions and the script is reading several positions as insertions. It is creating me problems... is it possible to read all nucleotides in the reference sequence as single SNP only? 

For example:
For position 8 I got as ref allele "GGT" and as alt allele "GTC". Reading in this way, I am missing variants at position 9 G/T and position 10 T/C. Furthermore, the position 8 (indeed) has no variation in my set of sequences.

Many thanks in advance,

Vanessa

**Comment by lindenb** [comment]
the option -f can be used to save the alignments as fasta; can you please use this option to show me the alignments in that region please.

**Comment by vfgoliveira** [comment]
exactly the same command but adding -f?

**Comment by vfgoliveira** [comment]
Hi Pierre,

I am running this command:

biostar94573 -f gi_0.fasta -c "NC_012920" > test.fasta


is that right?

many thanks

vanessa

2015-09-11 16:12 GMT-04:00 Pierre Lindenbaum <notifications@github.com>:

**Comment by lindenb** [comment]
so, what's the content of gi_0.fasta in the region ~8 ?

**Comment by lindenb** [comment]
ok, I see.

```
$ cut -c1-11 jeter.fasta  | grep -v "[0-9]" | sort | uniq
GACCACAGGTC
GATCACAGGTC
GATCACAGTCC
```

That would require too much work for a little result. I'm sorry but you'll have to do the transformation of this VCF by yourself.
