### ISSUE TITLE
Issues making Jvarkit

### ISSUE THREAD

**Issue by X-24** [lindenb/jvarkit#34]
Here it s, 
i REALLY REALLY need to use Biostar 94573 to convert some FASTA files into VCF so i will try again cause i have no other choices (even top Bioinformatics software like Artemis or Geneious cannot accept FASTA as an input and produce VCF as an output). I succesfully installed make, and successfully "made" curl. 

When i run the first command line of your example: 

$ curl https://raw.githubusercontent.com/biopython/biopython/master/Tests/Clustalw/opuntia.aln

(Actually in the example you provide in "https://github.com/lindenb/jvarkit/wiki/Biostar94573"
the adress is 
https://raw.github.com/biopython/biopython/master/Tests/Clustalw/opuntia.aln
and i had to change it to https://raw.githubusercontent.com/biopython/biopython/master/Tests/Clustalw/opuntia.aln
but that's just a detail !)

I get the same output as you : 
CLUSTAL W (1.81) multiple sequence alignment

gi|6273285|gb|AF191659.1|AF191      TATACATTAAAGAAGGGGGATGCGGATAAATGGAAAGGCGAAAGAAAGAA
gi|6273284|gb|AF191658.1|AF191      TATACATTAAAGAAGGGGGATGCGGATAAATGGAAAGGCGAAAGAAAGAA
gi|6273287|gb|AF191661.1|AF191      TATACATTAAAGAAGGGGGATGCGGATAAATGGAAAGGCGAAAGAAAGAA
gi|6273286|gb|AF191660.1|AF191      TATACATAAAAGAAGGGGGATGCGGATAAATGGAAAGGCGAAAGAAAGAA
gi|6273290|gb|AF191664.1|AF191      TATACATTAAAGGAGGGGGATGCGGATAAATGGAAAGGCGAAAGAAAGAA
gi|6273289|gb|AF191663.1|AF191      TATACATTAAAGGAGGGGGATGCGGATAAATGGAAAGGCGAAAGAAAGAA
gi|6273291|gb|AF191665.1|AF191      TATACATTAAAGGAGGGGGATGCGGATAAATGGAAAGGCGAAAGAAAGAA
                                    ******* **** *************************************

gi|6273285|gb|AF191659.1|AF191      TATATA----------ATATATTTCAAATTTCCTTATATACCCAAATATA
gi|6273284|gb|AF191658.1|AF191      TATATATA--------ATATATTTCAAATTTCCTTATATACCCAAATATA
gi|6273287|gb|AF191661.1|AF191      TATATA----------ATATATTTCAAATTTCCTTATATATCCAAATATA
gi|6273286|gb|AF191660.1|AF191      TATATA----------ATATATTTATAATTTCCTTATATATCCAAATATA
gi|6273290|gb|AF191664.1|AF191      TATATATATA------ATATATTTCAAATTCCCTTATATATCCAAATATA
gi|6273289|gb|AF191663.1|AF191      TATATATATA------ATATATTTCAAATTCCCTTATATATCCAAATATA
gi|6273291|gb|AF191665.1|AF191      TATATATATATATATAATATATTTCAAATTCCCTTATATATCCAAATATA
                                    ******          ********  **** ********* *********

gi|6273285|gb|AF191659.1|AF191      AAAATATCTAATAAATTAGATGAATATCAAAGAATCCATTGATTTAGTGT
gi|6273284|gb|AF191658.1|AF191      AAAATATCTAATAAATTAGATGAATATCAAAGAATCTATTGATTTAGTGT
gi|6273287|gb|AF191661.1|AF191      AAAATATCTAATAAATTAGATGAATATCAAAGAATCTATTGATTTAGTGT
gi|6273286|gb|AF191660.1|AF191      AAAATATCTAATAAATTAGATGAATATCAAAGAATCTATTGATTTAGTGT
gi|6273290|gb|AF191664.1|AF191      AAAATATCTAATAAATTAGATGAATATCAAAGAATCTATTGATTTAGTGT
gi|6273289|gb|AF191663.1|AF191      AAAATATCTAATAAATTAGATGAATATCAAAGAATCTATTGATTTAGTAT
gi|6273291|gb|AF191665.1|AF191      AAAATATCTAATAAATTAGATGAATATCAAAGAATCTATTGATTTAGTGT
                                    ************************************ *********** *

gi|6273285|gb|AF191659.1|AF191      ACCAGA
gi|6273284|gb|AF191658.1|AF191      ACCAGA
gi|6273287|gb|AF191661.1|AF191      ACCAGA
gi|6273286|gb|AF191660.1|AF191      ACCAGA
gi|6273290|gb|AF191664.1|AF191      ACCAGA
gi|6273289|gb|AF191663.1|AF191      ACCAGA
gi|6273291|gb|AF191665.1|AF191      ACCAGA
                                    ******
But when i try to make any tool, i still got an error message saying :
 
makefile:167: multiple target patterns.   Stop.

I made sure i had Java 1.7, when i run "java -version" i get :

Java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) Client VM (build 24.51-b03, mixed mode, sharing)

 I also added every single possible required folder to my PATH to make
sure i had all the requisite folders in it. Here is my PATH : 

C:\ProgramFiles\OpenVPN\bin;C:\;C:\mingw\msys\1.0\bin;C:\mingw\msys\1.0\lib;C:\mingw\bin;C:\mingw\lib;C:\Perl\bin;C:\Perl\lib;C:\Perl;C:\mingw\msys;C:\mingw;C:\curl-7.43.0;C:\Program Files\Git\bin;C:\Program Files\Git\lib;C:\Program Files\Git;C:\Program Files\Java\jdk.1.7.0_79;C:\Program Files\Java\jdk.1.7.0_79\bin;C:\Program Files\Java\jdk.1.7.0_79\Git\bin;C:\Program Files\Java\jdk.1.7.0_79\Git;C:\Program Files\Java\jdk.1.7.0_79\apache-ant-1.9.5;C:\Program Files\Java\jdk.1.7.0_79\Git;C:\Program Files\Java\jdk.1.7.0_79/bin;C:\Program Files\Java\jdk.1.7.0_79\Git;C:\Program Files\Java\jre7;C:\Program Files\Java\jre7/bin;C:\Program Files\Java\jre7/lib;

and finally, googling my error i was told by two different websites to check for colons
in target names so i copied and pasted the makefile in word and searched for colons
but word did not found a single one. I re downloaded jvarkit using the git clone command : 

$ git clone "https://github.com/lindenb/jvarkit.git"

a few days ago so i guess i have the latest version of javrkit. 

Please, could you try to help me ?

**Comment by lindenb** [comment]
* what's your OS
* what's your version of GNU make ?

**Comment by X-24** [comment]
OS is Windows 7 Edition Starter 
GNU Make is version 3.81

**Comment by X-24** [comment]
OS is Windows 7 Edition Starter

GNU Make is version 3.81


Cordialement,


Xavier Olessa-Daragon






On Wed, Nov 18, 2015 at 8:33 AM -0800, "Pierre Lindenbaum" <notifications@github.com> wrote:





* what's your OS
* what's your version of GNU make ?

---

**Comment by lindenb** [comment]
what do you mean with

>  But when i try to make any tool

**Comment by X-24** [comment]
when i either try to run just 

$ make 

from the jvarkit directory, or when y try 

$ make biostar94573 

or any other tool instead of biostar94573 (like the vcffilterjs of your example)

**Comment by lindenb** [comment]
```
$ make
```

should print:

> This  is the top target. Run 'make name-of-target' to build the desired target. Run 'make all' if you're Pierre Lindenbaum

also, you should have:

```
$ shasum Makefile 
716b85b0bb39557e49cfb752bb15aca07ddf080e  Makefile
```

**Comment by lindenb** [comment]
ah, I think I've got it: http://stackoverflow.com/questions/14514086/make-multiple-target-patterns-stop

because you're using windows, Make inserts some ':' in the file full paths, and a colon is a reserved word for GNU make, it breaks everything. 

I'm sorry, I won't fix this.

**Comment by X-24** [comment]
Well, all i get is 

makefile:167:   multiple target patterns.   Stop

And when i tried to run 

$ shasum Makefile 

i got 

shasum : Unable to find Digest ::SHA or Digest::SHA::PurePerl

**Comment by X-24** [comment]
Euh Okay, people who successfuly run it are on Linux i guess, do you think it might work on Mac Os ?

**Comment by lindenb** [comment]
MacOs / Linux: yes
