### ISSUE TITLE
Biostar94573 : Need some additional Informations regarding Input/Output

### ISSUE THREAD

**Issue by X-24** [lindenb/jvarkit#35]
Hi, sorry i know i need a lot of help but this time it should be far more easier.

 After your so fast and so accurate answer of yesterday as to why i could not make and run jvarkit on windows, i switched for a mac and was able to both make and run jvarkit, and especially the tool i deeply need, biostar 94573. The only issue i have is that i am absolutely not familiar with command line applications, and so i struggle a bit with the input and the output. Even reading your example multiple times, i struggle to understand how i should type my input before i type the command to activate the tool, : 

java -jar dist/biostar94573.jar

Because when i try to run this command with nothing before, the program seem to run, some text appear ending with "reading stdin" and after that i can type whenever i want, even enter or seemingly any sign or touch of the key board it continue to appear but nothing happen, it is like i cannot validate the input and tell the program that the input is over

So let's say i have a "seq.fas" or "seq.aln" file and i copied it in the jvarkit-master directory, what should be my script to convert it in vcf ? Should i just run the program with no input before, then type or paste my input and end it with a command or a sign that tells the computer that it is over ?

And the second part of my question concern the output, will i get a new "seq.vcf" file somewhere in the jvarkit-master directory or in another directory or will i have to copy the whole text starting with "##VCF 4.0" or something close to that appearing in the shell, paste it in a new text file and name the file "seq.vcf" to get my vcf file ? 

Again, really sorry to bother, i fully realize how stupid or trivial this might seem to people familiar with a command line environment but this is a real concern for me and i feel so close that i truly hope this is the last !

**Comment by lindenb** [comment]
it's a basic linux usage: http://www.linfo.org/standard_input.html

```
java -jar xxxxx.jar input.file
```

or 

```
java -jar xxxxx.jar < input.file
```

or

```
cat input.file |  java -jar xxxxx.jar
```

**Comment by X-24** [comment]
Okay,


sorry but again i am not at all familiar with linux. Is Input the name of my input file or file ? If my input file is named "seq.fas" should i type


input.seq (the one i would bet on) or seq.file ?


And really sorry to insist about it, but how should i process my output ? by copying what the shell prints in a new text file and save it as .vcf ?





On Thu, Nov 19, 2015 at 8:07 AM -0800, "Pierre Lindenbaum" <notifications@github.com> wrote:





it's a basic linux usage: http://www.linfo.org/standard_input.html

```
java -jar xxxxx.jar input.file
```

or

```
java -jar xxxxx.jar < input.file
```

or

```
cat input.file |  java -jar xxxxx.jar
```


---

**Comment by lindenb** [comment]
You should learn linux or ask a bioinformatician/IT-guy.
I'm sorry, I've got no time for this.
