### ISSUE TITLE
SamToPsl adds the flag to the bed name field

### ISSUE THREAD

**Issue by maximilianh** [lindenb/jvarkit#38]
this is not documented and I don't see where it makes sense to do this.

**Comment by lindenb** [comment]
I don't even remember why I wrote this tool :-) , I suppose I wrote this option in the case where the SAM is a secondary/supplementary alignment; it is used to make a difference with the primary alignment.

**Comment by maximilianh** [comment]
I see. thanks! Maybe it's easier to mark this tool as deprecated and refer
people to bedtools?

**Comment by lindenb** [comment]
that what i wrote  in the doc https://github.com/lindenb/jvarkit/wiki/SamToPsl ! :-)
I'm going to add a 'deprecated' flag.

Thanks.

**Comment by maximilianh** [comment]
Wait! I don't think bedtools supports the PSL format. PSL is the only
alignment format that I know is useful, apart from SAM...

**Comment by lindenb** [comment]
ok... ok.. I removed the "deprecated" in the doc..

**Comment by maximilianh** [comment]
Sorry, yes, didn't realize that this tool is really about PSL.

bedtools is by far not as good, as it removes the whole alignment. the PSL
format keeps the whole alignment, and then all the UCSC pslTools can be
used (pslFilter, pslReps, pslCdnaFilter, pslSwap, pslCheck, pslScore,
pslToChain, pslSort, pslPretty, pslPairs, pslHisto, etc etc)
