### ISSUE TITLE
Curl issue in Makefile when downloading htsjdk

### ISSUE THREAD

**Issue by xchrom** [lindenb/jvarkit#42]
Hi Pierre,

While using jvarkit for the first time, I ran into an issue when compiling sam2tsv and wanted to let others know the solution in case they encountered a similar issue. 

I kept getting an error with curl and ca certificates when trying to compile sam2tsv 

$ make sam2tsv

mkdir -p /home4/user/software/jvarkit/
rm -rf /home4/user/software/jvarkit/2.0.1.zip /home4/user/software/jvarkit/htsjdk-2.0.1/ 
echo "Downloading HTSJDK 2.0.1 with curl"
Downloading HTSJDK 2.0.1 with curl
curl   -o /home4/user/software/jvarkit/2.0.1.zip -L "https://github.com/samtools/htsjdk/archive/2.0.1.zip"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
make: *** [home4/user/software/jvarkit/htsjdk-2.0.1/build.xml] Error 77

I went and looked Makefile and found that by adding the -k option (allows insecure transfers), everything worked great. Every other time curl was in used Makefile it had the -k option.

line 589:  curl -k ${curl.proxy} -o $(dir ${htsjdk.home})${htsjdk.version}.zip -L "https://github.com/samtools/htsjdk/archive/${htsjdk.version}.zip"

**Comment by lindenb** [comment]
thanks ! I'll had the -k for downloading htsjdk.

**Comment by lindenb** [comment]
done: https://github.com/lindenb/jvarkit/commit/d0200d5e4e653bfdeadbb40efa588d4fd31706fe
