### ISSUE TITLE
feature request: PcrClipReads based on a flag

### ISSUE THREAD

**Issue by avilella** [lindenb/jvarkit#43]
Hi Pierre,

This is a feature request for the very useful pcrclipreads module. How would you envision being able to run it on a bed file, but only for reads that have a certain flag?

I am thinking an extra flag that if it's present and has a certain value, it means the read is flagged to be clipped according to the regions defined in the bed file.

Thx

**Comment by lindenb** [comment]
do you mean a SAM flag ?

**Comment by avilella** [comment]
Yes, an inoffensive sam flag that would split the reads into clippable or
non-clippable.

On Wed, Feb 24, 2016 at 4:09 PM, Pierre Lindenbaum <notifications@github.com

**Comment by lindenb** [comment]
I've updated the code: https://github.com/lindenb/jvarkit/wiki/PcrClipReads with a new option `-flag` 

https://github.com/lindenb/jvarkit/commit/5beeda137042c132e892129c8cd57af8a6d1a129

I don't have tests (...). Tell me if it works please.

P.
