### ISSUE TITLE
sam validation error from pcrclipreads

### ISSUE THREAD

**Issue by avilella** [lindenb/jvarkit#47]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

### Subject of the issue
```
NS500125:197:H7LJJAFXX:3:11406:4401:11023_1:N:0:GCCAAT:TTACCT, 
Soft clipping CIGAR operator can only be inside of hard clipping operator
```
### Your environment
* version of jvarkit: master branch
* version of java: jdk1.8.0_72
* the value of `${JAVA_HOME}`: $HOME/java/jdk1.8.0_72
* which OS

### Steps to reproduce
I ran PcrClipReads followed by samtools view and samtools sort. I then ran Picard alignment summary and got the error above for one of the reads.

### Expected behaviour
No issues

### Actual behaviour
Got SAM validation error. The full line of the read in question is below:

```
NS500125:197:H7LJJAFXX:3:11406:4401:11023_1:N:0:GCCAAT:TTACCT   0       chr8    95836647        23      92M1S1D51S      *       0       0       ATAGTAGTTGTTTAAAGTAAGTTAGAGAAATGTAGTAATAGTAATGTTTATTTATGTGGTTGGTTATTTTTTTTTGTAATGTAAAGAAATAATTAAGAAATGGAGTTAGGGTTTTTATAGTTGTTTTGAGAAATTTTGAAGATA EE<A/A<E/A/EAEEAAEEEA<AAAAAEAEAA6AAAEAAAA<EAEEEEEEEEEAAAAAA/AA6AEEAEEAEEEEEEAEEEEEEEEEEEE6EEEEEEEEEEE<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEE        MD:Z:1C2C7C4C4C12C2C2C4C0C0C2C11C0C5C0C4C16^TAA0C11C6C0C1C1C2C2C11C6C1  XG:Z:CT NM:i:30 XM:Z:.x..x.......h....h....x............h..x..h....hhh..h...........hh.....hh....h................h...........h......hh.h.x..x..h...........x......h.    XR:Z:GA
```

**Comment by lindenb** [comment]
can you please send me the BED line(s) that would overlap this read please.

**Comment by lindenb** [comment]
... and the original SAM line containing "NS500125:197:H7LJJAFXX:3:11406:4401:11023_1:N:0:GCCAAT:TTACCT" please

**Comment by avilella** [comment]
The original line is below:

```
NS500125:197:H7LJJAFXX:3:11406:4401:11023_1:N:0:GCCAAT:TTACCT   0
chr8    95836647        23      93M3D51M        *       0       0
ATAGTAGTTGTTTAAAGTAAGTTAGAGAAATGTAGTAATAGTAATGTTTATTTATGTGGTTGGTTATTTTTTTTTGTAATGTAAAGAAATAATTAAGAAATGGAGTTAGGGTTTTTATAGTTGTTTTGAGAAATTTTGAAGATA
EE<A/A<E/A/EAEEAAEEEA<AAAAAEAEAA6AAAEAAAA<EAEEEEEEEEEAAAAAA/AA6AEEAEEAEEEEEEAEEEEEEEEEEEE6EEEEEEEEEEE<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEE
       NM:i:30
MD:Z:1C2C7C4C4C12C2C2C4C0C0C2C11C0C5C0C4C16^TAA0C11C6C0C1C1C2C2C11C6C1
 XM:Z:.x..x.......h....h....x............h..x..h....hhh..h...........hh.....hh....h................h...........h......hh.h.x..x..h...........x......h.
   XR:Z:GA XG:Z:CT
```

So I presume what's happening is that PcrClipReads is turning all those 3'
Ms into Ss, but then that leaves a 3D+51S tail, which I presume is
incorrect, and should rather be 54S.

On Tue, Mar 1, 2016 at 11:10 AM, Pierre Lindenbaum <notifications@github.com

**Comment by avilella** [comment]
Maybe the same should be avoided on the 5' end: a XXS+YYD+ZZM should be (XX+YY)S+ZZM when soft-clipped.

**Comment by lindenb** [comment]
thanks, I need the bed lines overlapping this SAM record too, please.

**Comment by avilella** [comment]
The bed entries around the one overlapping that read were:

```
chr8    95627640        95640877                1
chr8    95640927        95721207                1
chr8    95721257        95732059                1
chr8    95732109        95732810                1
chr8    95732860        95785123                1
chr8    95785173        95836738                1
chr8    95836788        95890034                1
chr8    95890084        95890242                1
chr8    95890292        96055860                1
chr8    96055910        96096059                1
chr8    96096109        96096933                1
chr8    96096983        96104157                1

```

**Comment by lindenb** [comment]
I think it's a bug when I scan on the 3' side. I pushed a fix. It works here with your one and only record.

```
$ make pcrclipreads &&   java -jar dist/pcrclipreads.jar -largest -B jeter.bed jeter.sam > jeter2.sam && java -jar /commun/data/packages/picard/picard-tools-2.0.1/picard.jar ValidateSamFile I=jeter2.sam IGNORE=MISSING_READ_GROUP IGNORE=RECORD_MISSING_READ_GROUP
(....)
No errors found
[Tue Mar 01 15:51:16 CET 2016] picard.sam.ValidateSamFile done. Elapsed time: 0.01 minutes.
```
can you please tell me if it works with a larger dataset ?

**Comment by avilella** [comment]
No complains from Picard AlignmentSummary as far as I can see now.

Can close ticket.

Thanks again, Pierre, PcrClipReads is really useful.
