### ISSUE TITLE
boum ### vs ### error when running blastn2snp

### ISSUE THREAD

**Issue by hhoughwsu** [lindenb/jvarkit#51]
[~]>java -jar /usr/local/jvarkit/dist/blastn2snp.jar < /main/data/tmp/infilem7.out |column -t
[main] INFO jvarkit - Starting JOB at Tue May 03 16:16:59 PDT 2016 com.github.lindenb.jvarkit.tools.blast.BlastNToSnp version=undefined  built=2016-05-03:11-05-55
[main] INFO jvarkit - Command Line args : (EMPTY/NO-ARGS)
[main] INFO jvarkit - Executing as hhough@compute2 on Linux 3.2.0-89-generic amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_77-b03
[main] INFO jvarkit - Reading from stdin
[main] INFO jvarkit - resolveEntity:-//NCBI//NCBI BlastOutput/EN/http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd/null
java.lang.IllegalStateException: boum 406 vs 1
        at com.github.lindenb.jvarkit.tools.blast.BlastNToSnp.run(BlastNToSnp.java:282)
        at com.github.lindenb.jvarkit.tools.blast.BlastNToSnp.call(BlastNToSnp.java:338)
        at com.github.lindenb.jvarkit.tools.blast.AbstractBlastNToSnp.call(AbstractBlastNToSnp.java:274)
        at com.github.lindenb.jvarkit.tools.blast.AbstractBlastNToSnp.call(AbstractBlastNToSnp.java:32)
        at com.github.lindenb.jvarkit.util.command.Command.instanceMainWithExceptions(Command.java:549)
        at com.github.lindenb.jvarkit.util.command.Command.instanceMain(Command.java:586)
        at com.github.lindenb.jvarkit.util.command.Command.instanceMainWithExit(Command.java:592)
        at com.github.lindenb.jvarkit.tools.blast.BlastNToSnp.main(BlastNToSnp.java:357)
#query               hit   hit-index  hsp-index  query-POS  hit-POS   STRAND  REF(hit)  ALT(query)  blast.align_length  blast.hit.var  blast.query.var  blast.mid.                     var
[main] ERROR jvarkit - boum 406 vs 1
scaffold_1:46694924  Pp01  1          1          304        43120910  +       C         Y           203                 C              Y                .
[main] ERROR jvarkit - Command failed

java version "1.8.0_77"
$JAVA_HOME : /usr/local/java
Ubuntu 12.04

I'm unsure why the boum error is being thrown.  We've tried to use different input files and the result is the same, though the values for boum and vs differ.  Is something missing that is causing this?

**Comment by lindenb** [comment]
can I see the first lines of  /main/data/tmp/infilem7.out please ?

**Comment by hhoughwsu** [comment]
Of course; let me know if you need more than this.

<?xml version="1.0"?>
<!DOCTYPE BlastOutput PUBLIC "-//NCBI//NCBI BlastOutput/EN" "http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd">
<BlastOutput>
  <BlastOutput_program>blastn</BlastOutput_program>
  <BlastOutput_version>blastn 2.2.24 [Aug-08-2010]</BlastOutput_version>
  <BlastOutput_reference>~Reference: Altschul, Stephen F., Thomas L. Madden, Alejandro A. Schaffer, ~Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997), ~&quot;Gapped BLAST and PSI-BLAST: a new generation of protein database search~programs&quot;,  Nucleic Acids Res. 25:3389-3402.</BlastOutput_reference>
  <BlastOutput_db>Prunus_persica_v2.0.a1_scaffolds.fasta.Pp01</BlastOutput_db>
  <BlastOutput_query-ID>lcl|1_0</BlastOutput_query-ID>
  <BlastOutput_query-def>scaffold_1:46694924</BlastOutput_query-def>
  <BlastOutput_query-len>203</BlastOutput_query-len>
  <BlastOutput_param>
    <Parameters>
      <Parameters_expect>1e-06</Parameters_expect>
      <Parameters_sc-match>1</Parameters_sc-match>
      <Parameters_sc-mismatch>-3</Parameters_sc-mismatch>
      <Parameters_gap-open>5</Parameters_gap-open>
      <Parameters_gap-extend>2</Parameters_gap-extend>
      <Parameters_filter>F</Parameters_filter>
    </Parameters>
  </BlastOutput_param>
  <BlastOutput_iterations>
    <Iteration>
      <Iteration_iter-num>1</Iteration_iter-num>
      <Iteration_query-ID>lcl|1_0</Iteration_query-ID>
      <Iteration_query-def>scaffold_1:46694924</Iteration_query-def>
      <Iteration_query-len>203</Iteration_query-len>
      <Iteration_hits>
        <Hit>
          <Hit_num>1</Hit_num>
          <Hit_id>gnl|BL_ORD_ID|0</Hit_id>
          <Hit_def>Pp01</Hit_def>
          <Hit_accession>0</Hit_accession>
          <Hit_len>47851208</Hit_len>
          <Hit_hsps>

Regards,
Heidi

**Comment by lindenb** [comment]
yes more please ! :-)
I would be interested in the  Hit containing the error (may be it's the first Hit ?)

**Comment by hhoughwsu** [comment]
This is not a very large file we’re using to test with.  Here it is in its entirety.  Thank you so much for your prompt response and assistance.


<?xml version="1.0"?>
<!DOCTYPE BlastOutput PUBLIC "-//NCBI//NCBI BlastOutput/EN" "http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd">
<BlastOutput>
  <BlastOutput_program>blastn</BlastOutput_program>
  <BlastOutput_version>blastn 2.2.24 [Aug-08-2010]</BlastOutput_version>
  <BlastOutput_reference>~Reference: Altschul, Stephen F., Thomas L. Madden, Alejandro A. Schaffer, ~Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997), ~&quot;Gapped BLAST and PSI-BLAST: a new generation of protein database search~programs&quot;,  Nucleic Acids Res. 25:3389-3402.</BlastOutput_reference>
  <BlastOutput_db>Prunus_persica_v2.0.a1_scaffolds.fasta.Pp01</BlastOutput_db>
  <BlastOutput_query-ID>lcl|1_0</BlastOutput_query-ID>
  <BlastOutput_query-def>scaffold_1:46694924</BlastOutput_query-def>
  <BlastOutput_query-len>203</BlastOutput_query-len>
  <BlastOutput_param>
    <Parameters>
      <Parameters_expect>1e-06</Parameters_expect>
      <Parameters_sc-match>1</Parameters_sc-match>
      <Parameters_sc-mismatch>-3</Parameters_sc-mismatch>
      <Parameters_gap-open>5</Parameters_gap-open>
      <Parameters_gap-extend>2</Parameters_gap-extend>
      <Parameters_filter>F</Parameters_filter>
    </Parameters>
  </BlastOutput_param>
  <BlastOutput_iterations>
    <Iteration>
      <Iteration_iter-num>1</Iteration_iter-num>
      <Iteration_query-ID>lcl|1_0</Iteration_query-ID>
      <Iteration_query-def>scaffold_1:46694924</Iteration_query-def>
      <Iteration_query-len>203</Iteration_query-len>
      <Iteration_hits>
        <Hit>
          <Hit_num>1</Hit_num>
          <Hit_id>gnl|BL_ORD_ID|0</Hit_id>
          <Hit_def>Pp01</Hit_def>
          <Hit_accession>0</Hit_accession>
          <Hit_len>47851208</Hit_len>
          <Hit_hsps>
            <Hsp>
              <Hsp_num>1</Hsp_num>
              <Hsp_bit-score>400.248</Hsp_bit-score>
              <Hsp_score>201</Hsp_score>
              <Hsp_evalue>2.9023e-111</Hsp_evalue>
              <Hsp_query-from>203</Hsp_query-from>
              <Hsp_query-to>1</Hsp_query-to>
             <Hsp_hit-from>43120809</Hsp_hit-from>
              <Hsp_hit-to>43121011</Hsp_hit-to>
              <Hsp_query-frame>1</Hsp_query-frame>
              <Hsp_hit-frame>-1</Hsp_hit-frame>
              <Hsp_identity>202</Hsp_identity>
              <Hsp_positive>202</Hsp_positive>
              <Hsp_align-len>203</Hsp_align-len>
              <Hsp_qseq>CAAATGGTTCGACGATGTAGTGGCTGCTGGCTTGAGGGAACCAAATGCTATGGCCTTGTCAACTGCTAGCAAGAATGGAAAACCGTAATATCTGTTTCCTTYGTTACTATGCATCTTTTATTAATACTAAGCTATGTTTCACATATTGTTCTTGCATGTTAGATGAAATTTTATTGGTTTCACTATAGTTTCTAAATTTCTTT</Hsp_qseq>
              <Hsp_hseq>CAAATGGTTCGACGATGTAGTGGCTGCTGGCTTGAGGGAACCAAATGCTATGGCCTTGTCAACTGCTAGCAAGAATGGAAAACCGTAATATCTGTTTCCTTCGTTACTATGCATCTTTTATTAATACTAAGCTATGTTTCACATATTGTTCTTGCATGTTAGATGAAATTTTATTGGTTTCACTATAGTTTCTAAATTTCTTT</Hsp_hseq>
              <Hsp_midline>||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||</Hsp_midline>
            </Hsp>
          </Hit_hsps>
        </Hit>
      </Iteration_hits>
      <Iteration_stat>
        <Statistics>
          <Statistics_db-num>1</Statistics_db-num>
          <Statistics_db-len>47851208</Statistics_db-len>
          <Statistics_hsp-len>0</Statistics_hsp-len>
          <Statistics_eff-space>0</Statistics_eff-space>
          <Statistics_kappa>0.7113</Statistics_kappa>
          <Statistics_lambda>1.37856</Statistics_lambda>
          <Statistics_entropy>1.31082</Statistics_entropy>
        </Statistics>
      </Iteration_stat>
    </Iteration>
    <Iteration>
      <Iteration_iter-num>2</Iteration_iter-num>
      <Iteration_query-ID>lcl|2_0</Iteration_query-ID>
      <Iteration_query-def>scaffold_1:42975469</Iteration_query-def>
      <Iteration_query-len>203</Iteration_query-len>
      <Iteration_hits>
        <Hit>
          <Hit_num>1</Hit_num>
          <Hit_id>gnl|BL_ORD_ID|0</Hit_id>
          <Hit_def>Pp01</Hit_def>
          <Hit_accession>0</Hit_accession>
          <Hit_len>47851208</Hit_len>
          <Hit_hsps>
            <Hsp>
              <Hsp_num>1</Hsp_num>
              <Hsp_bit-score>400.248</Hsp_bit-score>
              <Hsp_score>201</Hsp_score>
              <Hsp_evalue>2.9023e-111</Hsp_evalue>
              <Hsp_query-from>203</Hsp_query-from>
              <Hsp_query-to>1</Hsp_query-to>
              <Hsp_hit-from>46840557</Hsp_hit-from>
              <Hsp_hit-to>46840759</Hsp_hit-to>
              <Hsp_query-frame>1</Hsp_query-frame>
              <Hsp_hit-frame>-1</Hsp_hit-frame>
              <Hsp_identity>202</Hsp_identity>
              <Hsp_positive>202</Hsp_positive>
              <Hsp_align-len>203</Hsp_align-len>
              <Hsp_qseq>GTCCCAATTAGCATCCAACAACTAGTTTATTACCAGTCATGTAAGCTCTCAATTTATTTCACTTATACTAATTAAAAGGCATAGTTAATTGATAGCAGCACYGAAAAAGGTACACACAGAAAGCAGTGTGTTAAATGCAACTTACCCTCAGAGGACTTGATGATGACAAAGCATAATCTTTTTCAAGATCATCAGAAAGAATA</Hsp_qseq>
              <Hsp_hseq>GTCCCAATTAGCATCCAACAACTAGTTTATTACCAGTCATGTAAGCTCTCAATTTATTTCACTTATACTAATTAAAAGGCATAGTTAATTGATAGCAGCACCGAAAAAGGTACACACAGAAAGCAGTGTGTTAAATGCAACTTACCCTCAGAGGACTTGATGATGACAAAGCATAATCTTTTTCAAGATCATCAGAAAGAATA</Hsp_hseq>
              <Hsp_midline>||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||</Hsp_midline>
            </Hsp>
          </Hit_hsps>
        </Hit>
      </Iteration_hits>
      <Iteration_stat>
        <Statistics>
          <Statistics_db-num>1</Statistics_db-num>
          <Statistics_db-len>47851208</Statistics_db-len>
          <Statistics_hsp-len>0</Statistics_hsp-len>
          <Statistics_eff-space>0</Statistics_eff-space>
          <Statistics_kappa>0.7113</Statistics_kappa>
          <Statistics_lambda>1.37856</Statistics_lambda>
          <Statistics_entropy>1.31082</Statistics_entropy>
        </Statistics>
      </Iteration_stat>
    </Iteration>
    <Iteration>
      <Iteration_iter-num>3</Iteration_iter-num>
      <Iteration_query-ID>lcl|3_0</Iteration_query-ID>
      <Iteration_query-def>scaffold_1:14849516</Iteration_query-def>
      <Iteration_query-len>203</Iteration_query-len>
      <Iteration_hits>
        <Hit>
          <Hit_num>1</Hit_num>
          <Hit_id>gnl|BL_ORD_ID|0</Hit_id>
          <Hit_def>Pp01</Hit_def>
          <Hit_accession>0</Hit_accession>
          <Hit_len>47851208</Hit_len>
          <Hit_hsps>
            <Hsp>
              <Hsp_num>1</Hsp_num>
              <Hsp_bit-score>400.248</Hsp_bit-score>
              <Hsp_score>201</Hsp_score>
              <Hsp_evalue>2.9023e-111</Hsp_evalue>
              <Hsp_query-from>1</Hsp_query-from>
              <Hsp_query-to>203</Hsp_query-to>
              <Hsp_hit-from>15823716</Hsp_hit-from>
              <Hsp_hit-to>15823918</Hsp_hit-to>
              <Hsp_query-frame>1</Hsp_query-frame>
              <Hsp_hit-frame>1</Hsp_hit-frame>
              <Hsp_identity>202</Hsp_identity>
              <Hsp_positive>202</Hsp_positive>
              <Hsp_align-len>203</Hsp_align-len>
              <Hsp_qseq>AGAAACATCATGTCTGAATCGGATCATCAATCCCCTGCTTTTACCTCCCCAAAAATGGTGGTCAAGAAGATCCTCGCCAAGTCCCAATCTGAGGGCGATGGYGCTACTGTCAGGAGAGCCATTGGAAGGTTTGGTTCATGGTTTTTTGCCCATTTGATATTTTTTTCATATTTCCTCTGCTCTGTTTTGGGATTTCAAATCCT</Hsp_qseq>
              <Hsp_hseq>AGAAACATCATGTCTGAATCGGATCATCAATCCCCTGCTTTTACCTCCCCAAAAATGGTGGTCAAGAAGATCCTCGCCAAGTCCCAATCTGAGGGCGATGGCGCTACTGTCAGGAGAGCCATTGGAAGGTTTGGTTCATGGTTTTTTGCCCATTTGATATTTTTTTCATATTTCCTCTGCTCTGTTTTGGGATTTCAAATCCT</Hsp_hseq>
             <Hsp_midline>||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||</Hsp_midline>
            </Hsp>
          </Hit_hsps>
        </Hit>
      </Iteration_hits>
      <Iteration_stat>
        <Statistics>
          <Statistics_db-num>1</Statistics_db-num>
          <Statistics_db-len>47851208</Statistics_db-len>
          <Statistics_hsp-len>0</Statistics_hsp-len>
          <Statistics_eff-space>0</Statistics_eff-space>
          <Statistics_kappa>0.7113</Statistics_kappa>
          <Statistics_lambda>1.37856</Statistics_lambda>
          <Statistics_entropy>1.31082</Statistics_entropy>
        </Statistics>
      </Iteration_stat>
    </Iteration>
    <Iteration>
      <Iteration_iter-num>4</Iteration_iter-num>
      <Iteration_query-ID>lcl|4_0</Iteration_query-ID>
      <Iteration_query-def>scaffold_1:8783331</Iteration_query-def>
      <Iteration_query-len>203</Iteration_query-len>
      <Iteration_hits>
        <Hit>
          <Hit_num>1</Hit_num>
          <Hit_id>gnl|BL_ORD_ID|0</Hit_id>
          <Hit_def>Pp01</Hit_def>
          <Hit_accession>0</Hit_accession>
          <Hit_len>47851208</Hit_len>
          <Hit_hsps>
            <Hsp>
              <Hsp_num>1</Hsp_num>
              <Hsp_bit-score>400.248</Hsp_bit-score>
              <Hsp_score>201</Hsp_score>
              <Hsp_evalue>2.9023e-111</Hsp_evalue>
              <Hsp_query-from>1</Hsp_query-from>
              <Hsp_query-to>203</Hsp_query-to>
              <Hsp_hit-from>9232590</Hsp_hit-from>
              <Hsp_hit-to>9232792</Hsp_hit-to>
              <Hsp_query-frame>1</Hsp_query-frame>
              <Hsp_hit-frame>1</Hsp_hit-frame>
              <Hsp_identity>202</Hsp_identity>
              <Hsp_positive>202</Hsp_positive>
              <Hsp_align-len>203</Hsp_align-len>
              <Hsp_qseq>CATTTATATCACCAAACAACGTAAACAAAACAAAATAGAGGATCAATTTTTCCTCGAGGACATCAAAACCCGGGGAAATTTCAAATACGGACAAGAAATGGRATCCCAGAAAAGGAACCAAACAGCGGATCTCGTAATCGATGGCTGTTAGTTGGAGGGTCAACCGGAAATAGTAGAAGGAGAGGAATTGGAGTTTACCTGTG</Hsp_qseq>
              <Hsp_hseq>CATTTATATCACCAAACAACGTAAACAAAACAAAATAGAGGATCAATTTTTCCTCGAGGACATCAAAACCCGGGGAAATTTCAAATACGGACAAGAAATGGGATCCCAGAAAAGGAACCAAACAGCGGATCTCGTAATCGATGGCTGTTAGTTGGAGGGTCAACCGGAAATAGTAGAAGGAGAGGAATTGGAGTTTACCTGTG</Hsp_hseq>
              <Hsp_midline>||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||</Hsp_midline>
            </Hsp>
          </Hit_hsps>
        </Hit>
      </Iteration_hits>
      <Iteration_stat>
        <Statistics>
          <Statistics_db-num>1</Statistics_db-num>
          <Statistics_db-len>47851208</Statistics_db-len>
          <Statistics_hsp-len>0</Statistics_hsp-len>
          <Statistics_eff-space>0</Statistics_eff-space>
          <Statistics_kappa>0.7113</Statistics_kappa>
          <Statistics_lambda>1.37856</Statistics_lambda>
          <Statistics_entropy>1.31082</Statistics_entropy>
        </Statistics>
      </Iteration_stat>
    </Iteration>
  </BlastOutput_iterations>
</BlastOutput>


Regards,
Heidi

**Comment by hhoughwsu** [comment]
Hello Pierre

My researcher says she’s resolved the problem.  The file we had been using was generated using Blastall.  She created a new one using Blast+.  Is there specific software that should be used?  Is Blast+ the only format that is correct for use with blastn2snp?  Are there others?  What are they?

Regards,
Heidi

**Comment by lindenb** [comment]
> My researcher says she’s resolved the problem. The file we had been using was generated using Blastall. She created a new one using Blast+. 

cool, thanks for the information.
I've never tested the old blastall with my tools. I wouldn't be surprised if the two XML are not the using the same the schema.

Closing this issue now.
