### ISSUE TITLE
MIN_COVERAGE doesn't seem to work

### ISSUE THREAD

**Issue by hamidhamzeiy** [lindenb/jvarkit#52]
java version "1.8.0_91" - Ubuntu 14.04

### MIN_COVERAGE doesn't seem to work
When I give a BAM file as input along with a BED file with my regions of interest and choose MIN_COVERAGE as 5, I still get results with min of 0.

**Comment by lindenb** [comment]
which tool ? what is your command line ?

**Comment by hamidhamzeiy** [comment]
Sorry, here it is:

java -jar bamstats04.jar \                                                                                                                                                 
BED='path' \
I='path' \
MIN_COVERAGE=5 \
>'result.txt'

**Comment by hamidhamzeiy** [comment]
#chrom	start	end	length	mincov	maxcov	mean	nocoveragepb	percentcovered
chr1	66999065	67210057	210992	0	980	17.1119995071	167596	20

**Comment by lindenb** [comment]
Ah, I see.

The min coverage in chr1 66999065 67210057  is zero  = there are some bases that were not covered, _and you cannot do anything about it_. But the fields/columns  **nocoveragepb** **percentcovered** take into account the parameters MIN_COVERAGE. If a position is covered less than MIN_COVERAGE then this position is considered as not coverage

**Comment by hamidhamzeiy** [comment]
Thank you so much for the quick reply. It was very helpful :)
