### ISSUE TITLE
Biostar78400.jar , Bug, regarding PU and PL values in RG tags 

### ISSUE THREAD

**Issue by muhammadsohailraza** [lindenb/jvarkit#59]
### Subject of the issue
I used Biostar78400.jar in order to replace the Read groups (RGs) in my BAM file but Platformunit (PU) and platform (PL ) assigned with same values.

### Your environment
recent directly cloned by GIT *java version "1.8.0_45"
the value of ${JAVA_HOME}: /software/biosoft/software/jdk1.8/jdk1.8.0_45/bin/java :

### Steps to reproduce
java -Xmx10g -jar $JVARKIT \
-o $OUTPUT/sohail2-modify.bam \
-formatout bam \
-p "([a-zA-Z0-9_\-]+):([0-9]):[0-9]+:[0-9]+:[0-9]+.". \
-x $INPUT/input1.xml \
$INPUT/sohail2.sam

my XML file was look like (please see attached file in txt format):

### Expected behaviour
In the the output file, PlatformUnit (PU) and Platform (PL) fields should be assigned with the values that were given in the input XML file. 

### Actual behaviour
Instead assigning separate values, in output file RG tag has same PU value as PL, for example (results):

@RG     ID:LP6005619-DNA_A01.L2 LB:LP6005619-DNA-PE     PL:HiSeq2000    SM:LP6005619-DNA_A01    PU:HiSeq2000    CN:Illumina-ltd DS:blabla
@RG     ID:LP6005619-DNA_A01.L3 LB:LP6005619-DNA-PE     PL:HiSeq2000    SM:LP6005619-DNA_A01    PU:HiSeq2000    CN:Illumina-ltd DS:blabla
@RG     ID:LP6005619-DNA_A01.L4 LB:LP6005619-DNA-PE     PL:HiSeq2000    SM:LP6005619-DNA_A01    PU:HiSeq2000    CN:Illumina-ltd DS:blabla

I tried to remove the "platformunit" tag from XML file in order to avoid this situation but still it outputs always PL and PU values same.

Please help me to resolve this, we cannot afford same PU values in RG tag, because recently GATK uses PU information rather than ID information to MarkDuplicates and BQSR if in case both ID and PU fields RG are present. so PU should be lane specific and cannot be the same.

Thanks!

**Comment by muhammadsohailraza** [comment]
[asw.txt](https://github.com/lindenb/jvarkit/files/382878/asw.txt)

**Comment by lindenb** [comment]
ah yes, I see. I've fixed this https://github.com/lindenb/jvarkit/commit/8b78fc53d6b40eb0b32264b05fd9d465467eaa94
thanks for the report

**Comment by muhammadsohailraza** [comment]
how can i update the biostar78400.jar to fix the bug or i have to install again?

**Comment by lindenb** [comment]
```
cd jvarkit
git pull origin master
make biostar78400
```

**Comment by muhammadsohailraza** [comment]
Fixed... Thanks!
