### ISSUE TITLE
bam2raster:  genome coordinates shifted by 1 base

### ISSUE THREAD

**Issue by jfx319** [lindenb/jvarkit#60]
### Subject of the issue
genome coordinates shifted by 1 in labels

### Your environment
* version of jvarkit
```
commit: f9842fcf255e7b7f3468ca5e2abf947f9c8dd9e3
```
* version of java
```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14
```
* the value of `${JAVA_HOME}`
```
/share/apps/java/1.8.0_45/
```
* which OS
```
Linux 2.6.32-573.12.1.el6.x86_64 amd64
```

### Steps to reproduce
bwa-mem was used to align reads to the same reference
bam header contains: 
```
@SQ     SN:12   LN:133851895
```

```
java -jar bam2raster.jar \
    -o chr12-48238837.png \
        -r 12:48238827-48238847 \
        -printBases \
        -w 500 \
        -R  human_g1k_v37_decoy.fasta \
        alignment.bam
```

### Expected behaviour
chr12:48238837 should be the SNP site (verified on UCSC genome browser)

![capture](https://cloud.githubusercontent.com/assets/20694664/18020510/b2f508b0-6baf-11e6-9819-607160cdb627.PNG)

### Actual behaviour
Instead, position chr12:48238837  is labeled upstream 1 base

![chr12-48238837](https://cloud.githubusercontent.com/assets/20694664/18020062/5ca73520-6bad-11e6-91b3-92587b2bfec9.png)

**Comment by lindenb** [comment]
Thank you for the report.
I'm away from my code for now , I'll look at this next week.

**Comment by lindenb** [comment]
Thank you for the report. I've updated the code: https://github.com/lindenb/jvarkit/commit/b51fe8f30c1ab3f7ec477a95786a5359f3e078a3

can you please confirm it works now ? thanks.

**Comment by jfx319** [comment]
Thanks for looking into this! 

I just ran the new commit, and looks like it's fixed! merci :)

![chr12-48238837](https://cloud.githubusercontent.com/assets/20694664/18065927/045b4718-6e04-11e6-85e6-1561560d8162.png)
