### ISSUE TITLE
sam2tsv bug error 

### ISSUE THREAD

**Issue by WinterLi1993** [lindenb/jvarkit#61]
HI,
  when I  installed  sam2tsv ,   reported the following error :  
jvarkit/src/main/java/com/github/lindenb/jvarkit/util/command/Command.java:566: error: cannot find symbol
						if(args!=null) dumpF.println(String.join(" ", args));

what happened ?

**Comment by lindenb** [comment]
what's your version of javac ?

```
javac -version
```

java 1.8 (aka 8) is required.

**Comment by WinterLi1993** [comment]
java version is 1.8 , and other error information :     
   warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/Cigar.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/CigarElement.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.

**Comment by lindenb** [comment]
what's the complete output of  `make sam2tsv` 
please.

**Comment by WinterLi1993** [comment]
I use 
make sam2tsv standalone=yes .
and complete output as the below : 
$ make sam2tsv standalone=yes
mkdir -p lib/com/github/samtools/htsjdk/2.6.1/ && curl -Lk  -o "lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar" "http://central.maven.org/maven2/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1516k  100 1516k    0     0   280k      0  0:00:05  0:00:05 --:--:--  339k
mkdir -p lib/commons-logging/commons-logging/1.1.1/ && curl -Lk  -o "lib/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar" "http://central.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 60686  100 60686    0     0  61409      0 --:--:-- --:--:-- --:--:-- 82008
mkdir -p lib/gov/nih/nlm/ncbi/ngs-java/1.2.4/ && curl -Lk  -o "lib/gov/nih/nlm/ncbi/ngs-java/1.2.4/ngs-java-1.2.4.jar" "http://central.maven.org/maven2/gov/nih/nlm/ncbi/ngs-java/1.2.4/ngs-java-1.2.4.jar"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 74133  100 74133    0     0  71845      0  0:00:01  0:00:01 --:--:-- 99507
mkdir -p lib/org/apache/commons/commons-compress/1.4.1/ && curl -Lk  -o "lib/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar" "http://central.maven.org/maven2/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  235k  100  235k    0     0   155k      0  0:00:01  0:00:01 --:--:--  186k
mkdir -p lib/org/apache/commons/commons-jexl/2.1.1/ && curl -Lk  -o "lib/org/apache/commons/commons-jexl/2.1.1/commons-jexl-2.1.1.jar" "http://central.maven.org/maven2/org/apache/commons/commons-jexl/2.1.1/commons-jexl-2.1.1.jar"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  261k  100  261k    0     0   169k      0  0:00:01  0:00:01 --:--:--  201k
mkdir -p lib/org/tukaani/xz/1.5/ && curl -Lk  -o "lib/org/tukaani/xz/1.5/xz-1.5.jar" "http://central.maven.org/maven2/org/tukaani/xz/1.5/xz-1.5.jar"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 99555  100 99555    0     0  81495      0  0:00:01  0:00:01 --:--:--   99k
mkdir -p lib/org/xerial/snappy/snappy-java/1.0.3-rc3/ && curl -Lk  -o "lib/org/xerial/snappy/snappy-java/1.0.3-rc3/snappy-java-1.0.3-rc3.jar" "http://central.maven.org/maven2/org/xerial/snappy/snappy-java/1.0.3-rc3/snappy-java-1.0.3-rc3.jar"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  967k  100  967k    0     0   289k      0  0:00:03  0:00:03 --:--:--  314k
mkdir -p /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/
echo "package com.github.lindenb.jvarkit.util.htsjdk;" > /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo '@javax.annotation.Generated("jvarkit")' >> /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo 'public class HtsjdkVersion{ private HtsjdkVersion(){}' >> /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo 'public static String getVersion() {return "2.6.1";}' >> /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo 'public static String getHash() {return "2.6.1";}' >> /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo 'public static String getHome() {return "lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar";}' >> /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo 'public static String getJavadocUrl(Class<?> clazz) {return "https://samtools.github.io/htsjdk/javadoc/htsjdk/"+clazz.getName().replaceAll("\\.","/")+".html";}' >> /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo '}'  >> /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
mkdir -p lib/commons-cli/commons-cli/1.3.1/ && curl -Lk  -o "lib/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar" "http://central.maven.org/maven2/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 52988  100 52988    0     0  50667      0  0:00:01  0:00:01 --:--:-- 70650
mkdir -p lib/org/slf4j/slf4j-api/1.7.13/ && curl -Lk  -o "lib/org/slf4j/slf4j-api/1.7.13/slf4j-api-1.7.13.jar" "http://central.maven.org/maven2/org/slf4j/slf4j-api/1.7.13/slf4j-api-1.7.13.jar"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33088  100 33088    0     0  43527      0 --:--:-- --:--:-- --:--:-- 66043
mkdir -p lib/org/slf4j/slf4j-simple/1.7.13/ && curl -Lk  -o "lib/org/slf4j/slf4j-simple/1.7.13/slf4j-simple-1.7.13.jar" "http://central.maven.org/maven2/org/slf4j/slf4j-simple/1.7.13/slf4j-simple-1.7.13.jar"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10553  100 10553    0     0  20741      0 --:--:-- --:--:-- --:--:-- 41222
echo "### COMPILING sam2tsv ######"
### COMPILING sam2tsv ######
mkdir -p /work/lidd/RD/Github/jvarkit/_tmp-2.6.1/META-INF /work/lidd/RD/Github/jvarkit/dist 
#generate java code if needed = a file with .xml exists, requires xsltproc, preprocessing file twice
if [ -e "/work/lidd/RD/Github/jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/sam2tsv/Sam2Tsv.xml"   ] ; then mkdir -p /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/tools/sam2tsv/ && xsltproc --xinclude --stringparam jarname 'sam2tsv' --stringparam githash  `cat  /work/lidd/RD/Github/jvarkit/.git/refs/heads/master ` -o "/work/lidd/RD/Github/jvarkit/src/main/generated-sources/com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.proc.xml" /work/lidd/RD/Github/jvarkit/src/main/resources/xsl/commandpreproc.xsl "/work/lidd/RD/Github/jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/sam2tsv/Sam2Tsv.xml" && xsltproc --xinclude --path "/work/lidd/RD/Github/jvarkit/src/main/resources/xml" -o /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/tools/sam2tsv/AbstractSam2Tsv.java /work/lidd/RD/Github/jvarkit/src/main/resources/xsl/command2java.xsl "/work/lidd/RD/Github/jvarkit/src/main/generated-sources/com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.proc.xml"  && xsltproc -o "/work/lidd/RD/Github/jvarkit/src/main/generated-sources/com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.elixir.jsonx" /work/lidd/RD/Github/jvarkit/src/main/resources/xsl/jsonxelixir.xsl "/work/lidd/RD/Github/jvarkit/src/main/generated-sources/com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.proc.xml" && xsltproc -o "/work/lidd/RD/Github/jvarkit/src/main/generated-sources/com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.elixir.json" /work/lidd/RD/Github/jvarkit/src/main/resources/xsl/jsonx2json.xsl "/work/lidd/RD/Github/jvarkit/src/main/generated-sources/com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.elixir.jsonx"   && mkdir -p /work/lidd/RD/Github/jvarkit/doc/wiki && xsltproc -o "/work/lidd/RD/Github/jvarkit/doc/wiki/Sam2Tsv.md" /work/lidd/RD/Github/jvarkit/src/main/resources/xsl/command2md.xsl "/work/lidd/RD/Github/jvarkit/src/main/generated-sources/com.github.lindenb.jvarkit.tools.sam2tsv.Sam2Tsv.proc.xml"   ; fi
#copy resource
cp /work/lidd/RD/Github/jvarkit/src/main/resources/messages/messages.properties /work/lidd/RD/Github/jvarkit/_tmp-2.6.1
echo '### Printing javac version : it should be 1.8. if Not, check your ${PATH}.'
### Printing javac version : it should be 1.8. if Not, check your ${PATH}.
javac -version
javac 1.7.0_101
#compile
javac -d /work/lidd/RD/Github/jvarkit/_tmp-2.6.1 -g -classpath "lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar:lib/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:lib/gov/nih/nlm/ncbi/ngs-java/1.2.4/ngs-java-1.2.4.jar:lib/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar:lib/org/apache/commons/commons-jexl/2.1.1/commons-jexl-2.1.1.jar:lib/org/tukaani/xz/1.5/xz-1.5.jar:lib/org/xerial/snappy/snappy-java/1.0.3-rc3/snappy-java-1.0.3-rc3.jar:lib/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar:lib/org/slf4j/slf4j-api/1.7.13/slf4j-api-1.7.13.jar:lib/org/slf4j/slf4j-simple/1.7.13/slf4j-simple-1.7.13.jar" -sourcepath /work/lidd/RD/Github/jvarkit/src/main/java:/work/lidd/RD/Github/jvarkit/src/main/generated-sources/java /work/lidd/RD/Github/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java /work/lidd/RD/Github/jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/sam2tsv/Sam2Tsv.java
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/reference/IndexedFastaSequenceFile.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/Cigar.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/CigarElement.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/CigarOperator.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/SAMUtils.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/SamReader.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/SAMRecord.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/SAMRecordIterator.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/util/CloserUtil.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/util/Locatable.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/SAMSequenceRecord.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/SamReaderFactory.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/SAMFileHeader.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/SAMSequenceDictionary.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/variant/variantcontext/VariantContext.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/variant/vcf/VCFHeader.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
/work/lidd/RD/Github/jvarkit/src/main/java/com/github/lindenb/jvarkit/util/command/Command.java:566: error: cannot find symbol
						if(args!=null) dumpF.println(String.join(" ", args));
						                                   ^
  symbol:   method join(String,String[])
  location: class String
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/tribble/readers/LineIterator.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/tribble/readers/LineIteratorImpl.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/tribble/readers/LineReader.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/tribble/readers/SynchronousLineReader.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/Defaults.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/util/AbstractIterator.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/util/BlockCompressedInputStream.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/util/BlockCompressedOutputStream.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/util/IOUtil.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/util/RuntimeIOException.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/ValidationStringency.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/SamInputResource.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/sra/SRAAccession.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/seekablestream/SeekableStream.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/AbstractSAMHeaderRecord.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/util/CloseableIterator.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/reference/AbstractFastaSequenceFile.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/reference/ReferenceSequenceFile.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/reference/ReferenceSequence.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/SAMException.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: lib/com/github/samtools/htsjdk/2.6.1/htsjdk-2.6.1.jar(htsjdk/samtools/util/IterableOnceIterator.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
1 error
37 warnings
make: *** [sam2tsv] Error 1

**Comment by lindenb** [comment]
As you can see, you have a **$PATH** problem as the lines

```
(...)
echo '### Printing javac version : it should be 1.8. if Not, check your ${PATH}.'
Printing javac version : it should be 1.8. if Not, check your ${PATH}.
javac -version
javac 1.7.0_101
#compile
(...)
```

clearly show that your default compiler is javac 1.7 and not 1.8

I'm closing this now.

**Comment by WinterLi1993** [comment]
yep , I just changed  java version, do not change javac version, thank you ! !!
