### ISSUE TITLE
what's the meaning cigar-op  ?

### ISSUE THREAD

**Issue by WinterLi1993** [lindenb/jvarkit#64]
Hi,
    the op at the ouput  is the cigar mark of this base ?  if I just wanna  count the number  mismatch per read  ,  just to care "M"  in the op ?

**Comment by lindenb** [comment]
it's the cigar operator, see the sam spec: https://samtools.github.io/hts-specs/SAMv1.pdf : "the CIGAR operations are given in the following table ... "

**Comment by WinterLi1993** [comment]
hi,
   how to know mismatch number for per read ?  there some mark in the bam file ?

**Comment by lindenb** [comment]
see the sam spec & NM http://samtools.github.io/hts-specs/SAMtags.pdf
