### ISSUE TITLE
Problems running bamstats05: ERROR jvarkit - null

### ISSUE THREAD

**Issue by ECGarrett** [lindenb/jvarkit#66]
### Verify
- if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
- the version of java
### Subject of the issue

I am trying to get read depth per gene for a target sequencing project. When trying to implement bamstats05, with the input of a bed file and a bam file, I receive errors related to a java.lang.NullPointerException, an error that jvarkit-NULL, and the command doesn't work. I believe the program has been correctly installed (followed instructions from the site and have not moved files around, the make also appeared to have worked). I am working on a server, and for many of my processes I need an older version of Java, but when running bamstats05 I redirect to a 1.8 version of Java (so I get pointed to the older version but I manually direct to the correct version). I'm still fairly new to bioinformatics and programming, so while I have tried to trouble shoot, I cannot find a solution. I'm sure it is a simple novice issue, but any  help would be greatly appreciated. Thank you.
### Your environment
- version of jvarkit: 59abd024cd6ae8820f76df5f876443bf88d81ea2
- version of java: openjdk version "1.8.0_77"
  OpenJDK Runtime Environment (build 1.8.0_77-b03)
  OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)
- the value of `${JAVA_HOME}`:PATH=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.99-2.6.5.0.el7_2.x86_64/jre/bin
- which OS:Linux galaxy.chgi.ucalgary.ca 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
### Steps to reproduce

/usr/bin/java -jar dist/bamstats05.jar -B ../References/targets_named_revised_722.bed ../picard_bams/113_S15.bam

First three lines of my .bed file:
chr16   86233326    86233776    Neutral1
chr10   130553949   130554469   Neutral10
chr22   49730392    49730915    Neutral11
chr16   86228649    86229176    Neutral12
### Expected behaviour

I expect to see read depth stats per gene, but this is not the case
### Actual behaviour

Here is the output after running the command:
 $ /usr/bin/java -jar dist/bamstats05.jar -B ../References/targets_named_revised_722.bed ../picard_bams/113_S15.bam

[main] INFO jvarkit - Starting JOB at Wed Oct 05 12:38:57 MDT 2016 com.github.lindenb.jvarkit.tools.bamstats04.BamStats05 version=59abd024cd6ae8820f76df5f876443bf88d81ea2  built=2016-10-04:13-10-48
[main] INFO jvarkit - Command Line args : -B ../References/targets_named_revised_722.bed ../picard_bams/113_S15.bam
[main] INFO jvarkit - Executing as <user> on Linux 3.10.0-327.13.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_77-b03
java.lang.NullPointerException
    at com.github.lindenb.jvarkit.tools.bamstats04.BamStats05.readBedFile(BamStats05.java:94)
    at com.github.lindenb.jvarkit.tools.bamstats04.BamStats05.call(BamStats05.java:282)
    at com.github.lindenb.jvarkit.tools.bamstats04.BamStats05.call(BamStats05.java:67)
    at com.github.lindenb.jvarkit.util.command.Command.instanceMainWithExceptions(Command.java:551)
    at com.github.lindenb.jvarkit.util.command.Command.instanceMain(Command.java:608)
    at com.github.lindenb.jvarkit.util.command.Command.instanceMainWithExit(Command.java:614)
    at com.github.lindenb.jvarkit.tools.bamstats04.BamStats05.main(BamStats05.java:340)
[main] ERROR jvarkit - null
[main] ERROR jvarkit - Command failed

**Comment by lindenb** [comment]
Thanks for reporting this ! My bad, I've changed the code without checking the program. I've made a fix: https://github.com/lindenb/jvarkit/commit/abee996272e161088c4fd81d4c4d36ad8c5e9f5d#diff-eb73fb09c5351b3e023b7d357a80805b 

can you tell me if it works now ? thanks !

**Comment by ECGarrett** [comment]
That worked! Thank you! You are my hero of the day.
