### ISSUE TITLE
Request: Consider neighboring nucleotides in VCFPolyX

### ISSUE THREAD

**Issue by tantrev** [lindenb/jvarkit#67]
### Verify
openjdk version "1.8.0_92"
OpenJDK Runtime Environment (Zulu 8.15.0.1-macosx) (build 1.8.0_92-b15)
OpenJDK 64-Bit Server VM (Zulu 8.15.0.1-macosx) (build 25.92-b15, mixed mode)

### Subject of the issue
I've been calling variants with FreeBayes and I frequently see variants called that are next to homopolymers (stretches > 4 bp) that I'd like to filter out.  Since it appears the variants are called according to their left-most non-repeating nucleotide, VCFPolyX doesn't filter them.  It'd just be nice if VCFPolyX had such functionality. :)

### Your environment
* master branch
* openjdk version "1.8.0_92"
* blank
* System Version: OS X 10.9.5 (13F1603)
   Kernel Version: Darwin 13.4.0

### Steps to reproduce
Here's an
[example VCF after filtering.](https://github.com/lindenb/jvarkit/files/519934/Example.vcf.zip)  The reference genome I've been using may be found at: ftp://ftp.ensembl.org/pub/release-84/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.toplevel.fa.gz

The first line of the VCF demonstrates the issue but here it is for redundancy's sake:
1       13165453        .       ATTTTTTTTTTTG   ATTTTTTTTTTTTG  41.12   .      

### Expected behaviour
Filter out the variants next to homopolymers.

### Actual behaviour
The variants next to homopolymers are currently retained.

**Comment by lindenb** [comment]
Hi, that's a nice idea but there are already some some tools to filter this: bcftools, gatk-variantfiltration+JEXL , https://github.com/lindenb/jvarkit/wiki/VCFFilterJS ...

**Comment by tantrev** [comment]
Great, thank you!
