### ISSUE TITLE
vcf2hilbert

### ISSUE THREAD

**Issue by SamMondal** [lindenb/jvarkit#69]
Hello Pierre,
Could you please point to me a sample vcf file that will work for vcf2hilbert?
I keep getting this error, for different vcf files (formats):
"The input file is missing a SAM sequence dictionary."

Thanks!

### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

### Subject of the issue
Describe your issue here.

### Your environment
* version of jvarkit
* version of java
* the value of `${JAVA_HOME}`
* which OS

### Steps to reproduce
Tell us how to reproduce this issue. Please provide an example.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by lindenb** [comment]
> The input file is missing a SAM sequence dictionary.

means that the VCF must contain a dictionary (=VCF header with lines starting with `##contig=`). see **1.2.7** in https://samtools.github.io/hts-specs/VCFv4.2.pdf
