### ISSUE TITLE
Biostar103303 output

### ISSUE THREAD

**Issue by lmanchon** [lindenb/jvarkit#75]
--Hi,

i have tested the program to calculate PSI but in the output i can't find column with PSI value:
java -jar jvarkit/dist/biostar103303.jar -g Droso.gtf < my.bam > my.tsv

#chrom;exon.start;exon.end;exon.exon_id;exon.index5_3;transcript_id;gene_name;gene_id;exon.count_prev_and_next;exon.count_prev_and_curr;exon.count_curr_and_next;exon.count_curr_only;exon.count_others
4;879;1079;FBtr0346692-E1;1/6;FBtr0346692;JYalpha;FBgn0267363;0;0;0;0;0
4;1144;1410;FBtr0346692-E2;2/6;FBtr0346692;JYalpha;FBgn0267363;0;0;0;0;0
4;1768;3851;FBtr0346692-E3;3/6;FBtr0346692;JYalpha;FBgn0267363;0;0;0;0;0
4;4353;4527;FBtr0346692-E4;4/6;FBtr0346692;JYalpha;FBgn0267363;0;0;0;0;0
4;4592;4824;FBtr0346692-E5;5/6;FBtr0346692;JYalpha;FBgn0267363;0;0;0;0;0
4;4875;5039;FBtr0346692-E6;6/6;FBtr0346692;JYalpha;FBgn0267363;0;0;0;0;0
4;5829;6041;FBtr0333684-E5;1/5;FBtr0333684;CR32011;FBgn0052011;0;0;0;10;0
4;6374;6475;FBtr0089182-E5;1/5;FBtr0089182;CR32011;FBgn0052011;0;0;5;5;0
4;6541;6723;FBtr0333684-E4;2/5;FBtr0089182;CR32011;FBgn0052011;0;5;12;26;0
4;6541;6723;FBtr0333684-E4;2/5;FBtr0333684;CR32011;FBgn0052011;0;0;12;31;0
4;7745;8281;FBtr0333684-E3;3/5;FBtr0089182;CR32011;FBgn0052011;0;12;16;121;0
4;7745;8281;FBtr0333684-E3;3/5;FBtr0333684;CR32011;FBgn0052011;0;12;16;121;0
4;8340;8675;FBtr0333684-E2;4/5;FBtr0089182;CR32011;FBgn0052011;0;16;0;97;3
4;8340;8675;FBtr0333684-E2;4/5;FBtr0333684;CR32011;FBgn0052011;0;16;0;97;3
4;8730;11765;FBtr0333684-E1;5/5;FBtr0089182;CR32011;FBgn0052011;0;0;0;660;6
4;8730;11765;FBtr0333684-E1;5/5;FBtr0333684;CR32011;FBgn0052011;0;0;0;660;6
4;12640;12825;FBtr0333683-E5;1/5;FBtr0333683;CR32010;FBgn0052010;0;0;0;8;2
4;13153;13257;FBtr0089181-E5;1/5;FBtr0089181;CR32010;FBgn0052010;0;0;5;5;2
4;13323;13505;FBtr0333683-E4;2/5;FBtr0089181;CR32010;FBgn0052010;0;5;12;26;2

Do i calculate PSI using some oh these columns ?

thank you --

**Comment by lindenb** [comment]
That's an old program I've just created for biostars. I don't really know what is the 'PSI' In the output I'm just showing the number of reads overlapping the junctions.

**Comment by lmanchon** [comment]
definition of PSI: http://geuvadiswiki.crg.es/index.php/Percentage_Splicing_Index

**Comment by lindenb** [comment]
sure, But I won't modify this old program. Feel free to calculate it by yourself.

**Comment by lmanchon** [comment]
no worries, I thought there was a new program to do that.

**Comment by lindenb** [comment]
no sorry :-)
' closing this issue for now.
