### ISSUE TITLE
SnpEff ANN annotations not implemented in SnpEffPredictionParser

### ISSUE THREAD

**Issue by Oodnadatta** [lindenb/jvarkit#76]
### Subject of the issue
SnpEff ANN annotations not implemented in [SnpEffPredictionParser](https://github.com/lindenb/jvarkit/blob/dc7f7797c60d63cd09d3b7712fb81033cd7022cb/src/main/java/com/github/lindenb/jvarkit/util/vcf/predictions/SnpEffPredictionParser.java#L80).

### Your environment
Kaamelott server from l'institut du thorax on which you work everyday. Thank you Audrey and Eric.

### Steps to reproduce
Use VcfFilterSO on a vcf annotated with SnpEff without the --formatEff option that uses the ANN field instead of the old EFF field (http://snpeff.sourceforge.net/SnpEff_manual.html and [new VCF annotation standard 'ANN' field](http://snpeff.sourceforge.net/VCFannotationformat_v1.0.pdf).

### Actual behaviour
Error message `WARNING: no INFO[EFF] or no description `.

**Comment by lindenb** [comment]
ben si: https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/util/vcf/predictions/AnnPredictionParser.java

**Comment by Oodnadatta** [comment]
Après un sed, j'ai remarqué que c'était la même chose avec EFF. Dans tous les cas, j'ai un message d'erreur.

**Comment by lindenb** [comment]
ça date de quand ta version ?

**Comment by lindenb** [comment]
paske je l'ai implémenté:  https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/tools/vcffilterso/VcfFilterSequenceOntology.java#L253

**Comment by Oodnadatta** [comment]
De jvarkit ? C'est celle qui est sur Kaamelott (jvarkit-git)

**Comment by Oodnadatta** [comment]
Le problème, c'est qu'il veut toutes les annotations et pas au moins une d'entre elles.

**Comment by lindenb** [comment]
ah, je doute de l'avoir recompilé sur le serveur. J'attends que MK finisse des analyses avant de recompiler les outils. D'autant plus que l'arbre d'ontologie SE sous-jacent à été mis à jour récement.

**Comment by lindenb** [comment]
> Le problème, c'est qu'il veut toutes les annotations et pas au moins une d'entre elles.

non. c'est just un warning https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/util/vcf/predictions/AnnPredictionParser.java#L111 .


 chz toi ça plante ?

**Comment by Oodnadatta** [comment]
Non, ça plante pas, mais j'ai cru avec les warnings. Est-ce que ce ne serait pas mieux de les retirer s'il y a au moins une annotation ?

**Comment by lindenb** [comment]
non, mais je vais changer le message pour que ça soit plus clair ( et j'ai connu une claire)

**Comment by Oodnadatta** [comment]
Super, merci !
