### ISSUE TITLE
no stats from bamstat04.jar

### ISSUE THREAD

**Issue by bertgoldphd** [lindenb/jvarkit#78]
Hi!  I am getting header but no stats.  This combination of files works using the alternative bedtools method...
___________________
[bgold@bgold-dev may17_h282_belle]$ java -jar bamstats04.jar -B NameDeleted.bed NicelyFormed.novoalign.bam
#chrom	start	end	length	mincov	maxcov	meancov	mediancov	nocoveragebp	percentcovered
[INFO][BamStats04]done
[bgold@bgold-dev may17_h282_belle]$ 

_________________________________

[bgold@bgold-dev may17_h282_belle]$ more NameDeleted.bed
1	11861219	11861219	MTHFR_c.474A>T
1	21887155	21887155	ALPL_c.98C>T
1	21887619	21887619	ALPL_c.211C>T
1	21889712	21889712	ALPL_c.407G>A
1	21890632	21890632	ALPL_c.571G>A
1	21894615	21894615	ALPL_c.667C>T
1	21894616	21894616	ALPL_c.668G>A
1	21900176	21900176	ALPL_c.881A>C
1	21900274	21900274	ALPL_c.979T>C
1	21902229	21902229	ALPL_c.1001G>A

_______________________________________

Alternative bedtools method:

[bgold@bgold-dev may17_h282_belle]$ sudo bedtools coverage -a NameDeleted.bed -b NicelyFormed.novoalign.bam -hist
1	11861219	11861219	MTHFR_c.474A>T	250	1	2	0.5000000
1	11861219	11861219	MTHFR_c.474A>T	253	1	2	0.5000000
1	21887155	21887155	ALPL_c.98C>T	351	1	2	0.5000000
1	21887155	21887155	ALPL_c.98C>T	353	1	2	0.5000000
1	21887619	21887619	ALPL_c.211C>T	320	1	2	0.5000000

**Comment by lindenb** [comment]
works for me
```

$ java -jar dist/bamstats04.jar -B ~/jeter.bed  ~/scf7180000354095.bam
#chrom	start	end	length	mincov	maxcov	meancov	mediancov	nocoveragebp	percentcovered
scf7180000354095	178	179	1	16	16	16.0	16.0	0	100
```

please, check you're running the latest version.
