### ISSUE TITLE
VCFfilterJS does not remove variants

### ISSUE THREAD

**Issue by thartwig** [lindenb/jvarkit#79]
### Verify
VCFfilterJS was installed and seems to be running without errors

### Subject of the issue
I am trying to run VCFfilterJS to filter a multi individual (around 120 samples) vcf which was generated using the GATK best practices pipeline. I am trying to filter the vcf file to only include variants for which the sample "MR1" is homozygous for the reference genome. So I trying to filter by MR1 and by the GT flag 0/0 for this individual. The output vcf (was wondering that no recode is necessary like with vcftools) should only include those variants. I am running VCFfilterJS on a slurm cluster:

java -jar ~/bin/jvarkit/dist/vcffilterjs.jar \
	-e 'variant.getGenotype("MR1").ishomRef()' \
	-o $Output_DIR/$Input_vcf"_MR1_homo_only".vcf \
	$Input_DIR/"$Input_vcf".vcf  

### Your environment
jvarkit: 59047c84a493a0269a46c5f1e3f686468eda4b38
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
OS: Linux memex.local 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Mar 10 17:01:00 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce
Tell us how to reproduce this issue. Please provide an example.

### Expected behaviour
I wanted the input vcf to be filtered and all variants for which sample MR1 is not 0/0 to be removed in the output vcf
### Actual behaviour
VCFfilterJS runs without and error, however the output and input vcf files are identical. I checked and there are many variants for which MR1 is not 0/0.

**Comment by lindenb** [comment]
please provide a minimal vcf file with one line where MR1 is not 0/0 and one line where MR1 is 0/0. Thanks.

**Comment by lindenb** [comment]
ho, I think your bug is

`ishomRef()`

should be

`isHomRef()` 

https://samtools.github.io/htsjdk/javadoc/htsjdk/htsjdk/variant/variantcontext/Genotype.html#isHomRef--

I'm sure there was an error message related to this.
```

Caused by: <eval>:1 TypeError: has no such function "ishomeref"
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
(...)


```
