### ISSUE TITLE
sortsamrefname stalling at end for hours

### ISSUE THREAD

**Issue by antmarge** [lindenb/jvarkit#83]
### Subject of the issue
`sortsamrefname` Makes consistent progress but then stalls at "1 minute remaining"

### Environment
* version of jvarkit: `2d33719edc69a979a2b6366351ca6f0b59959755`
* version of java: `1.8.0_131`
* the value of `${JAVA_HOME}`: `/share/software/user/open/java/1.8.0_131`
* which OS: `Linux 7.3.1611`

### Steps to reproduce
`input=/abs/path/to/bamfile.bam` (is a valid bam file as verified by samtools)
`output=/abs/path/to/bamfile.sorted.bam`
`SORT_SAM_REFNAME=/abs/path/to/bin/jvarkit/dist/sortsamrefname.jar`

Run ` java -jar $SORT_SAM_REFNAME $input  -o $output`

### Stalled output
Makes consistent progress for the first 45 minutes, then stalls at last chromosome, at "1 minute remaining" for  hours
`[INFO][SAMSequenceDictionaryProgress]Count: 803650002 Elapsed: 45 minutes(96.82%) Remains: 1 minute(3.18%) Last: 21:41150167`

**Comment by antmarge** [comment]
Update: It finished at about 3 hours, Staying on the last step for over 2 hours. Any idea as to why this is the case?

**Comment by lindenb** [comment]
no idea, could be a memory problem or too many files open or no more space on device ? isn't there an error message ?  Try to increase the jvm memory with xmx or maxRecordsInRam(http://lindenb.github.io/jvarkit/SortSamRefName.html) 

`java -Xmx3g -jar sortsamrefname  --maxRecordsInRam 1000000  --tmpDir .     -o out.bam in.bam`

**Comment by lindenb** [comment]
> It finished at about 3 hours

does that mean that it ends with success or with failure ?

**Comment by antmarge** [comment]
Finished with success.

**Comment by lindenb** [comment]
> Any idea as to why this is the case?

the progress bar stops after all the reads have been loaded in the temporary directory. At this point, the program looks over all the temporary files and starts writing...
