### ISSUE TITLE
-T parameter not recognized in sortsamrefname & Biostar154220

### ISSUE THREAD

**Issue by antmarge** [lindenb/jvarkit#84]
When I run `sortsamrefname` or `Biostar154220` with the `-T bam` option on my bam file as shown in the examples [here](http://lindenb.github.io/jvarkit/Biostar154220.html#example) and [here](https://www.biostars.org/p/154220/), I get an error that the `-T` option is not recognized. Indeed, it is also not included in the documentation for the either tool. I assumed it was to declare file type.

### Environment
* version of jvarkit: `2d33719edc69a979a2b6366351ca6f0b59959755`
* version of java: `1.8.0_131`
* the value of `${JAVA_HOME}`: `/share/software/user/open/java/1.8.0_131`
* which OS: `Linux 7.3.1611`

### Steps to reproduce
`input=/abs/path/to/samplename.bam` (is a valid bam file as verified by samtools)
`output=/abs/path/to/samplename.sorted.bam`
`SORT_SAM_REFNAME=/abs/path/to/bin/jvarkit/dist/sortsamrefname.jar`
`CAP_BAM_COV=/abs/path/to/bin/jvarkit/dist/biostar154220.jar`

` java -jar $SORT_SAM_REFNAME -T bam $input  -o $output`
OR
```
java -jar $SORT_SAM_REFNAME -T bam $input | \
java -jar $CAP_BAM_COV -T bam --depth 5 | \
samtools sort - -o $output
```

### Output Error

```
[SEVERE][Launcher]There was an error in the command line arguments. Please check your parameters : Expected one or zero argument but got 3 : [-T, bam, samplename.bam]
[INFO][Launcher]sortsamrefname Exited with failure (-1)
```

**Comment by lindenb** [comment]
there is no such parameter: http://lindenb.github.io/jvarkit/SortSamRefName.html
