### ISSUE TITLE
vcf2bam

### ISSUE THREAD

**Issue by TiagoSousaNeves** [lindenb/jvarkit#86]
### Subject of the issue
It doesn't accept the reference genome, it is indexed with samtools as well as Picard. I'm using it just fine in several software except in this tool. Also, I tried with different versions of samtools and Picard without success, same error!

### Steps to reproduce
Tell us how to reproduce this issue. Please provide an example.
`
$ '.../Downloads/jvarkit/dist/vcf2bam' -R '..../SNPs/fa/longest_uces_semZ.fa' '..../No_OUT/1SNPlocus_Pheugopedius-only-PASS-Q30-SNPs_maf0.014925373.vcf.gz' 2> '..../No_OUT/1SNPlocus_Pheugopedius-only-PASS-Q30-SNPs_maf0.014925373.bam' | grep -v "100="

`[SEVERE][VcfToBam]No REF defined
[INFO][Launcher]vcf2bam Exited with failure (-1)

My files, vcf and ref
[1SNPlocus_Pheugopedius-only-PASS-Q30-SNPs_maf0.014925373.vcf.gz](https://github.com/lindenb/jvarkit/files/1272552/1SNPlocus_Pheugopedius-only-PASS-Q30-SNPs_maf0.014925373.vcf.gz)
[longest_uces_semZ.fa.zip](https://github.com/lindenb/jvarkit/files/1272551/longest_uces_semZ.fa.zip)

Can you help me please?

Thanks

TSN

**Comment by lindenb** [comment]
ah yes, I can see the same bug. I have not used this program for years. Give me a few minutes...

**Comment by lindenb** [comment]
I've updated the code (I didn't test the program after I've added a line) Can you please update the code and try again ?

**Comment by TiagoSousaNeves** [comment]
Thank you, 

Now I'm getting this:

[SEVERE][VcfToBam]Variants are not ordered on sequence dictionary ([VC Unknown @ ACAexon1PhgSARMA101:117 Q230.02 of type=SNP alleles=[C*, T] attr={} GT=GT:AD:DP:GQ:PL	0/0:14,0:14:36:0,36,495	0/0:19,0:19:54:0,54,763	0/0:14,0:14:36:0,36,5100/0:14,0:14:42:0,42,582	0/0:21,0:21:57:0,57,774	0/0:10,0:10:27:0,27,383	0/0:15,0:15:45:0,45,614	0/0:34,0:34:66:0,66,924	0/0:47,0:47:99:0,111,1496	0/0:30,0:30:69:0,69,950	0/0:19,0:19:39:0,39,546	0/0:17,0:17:36:0,36,504	0/0:5,0:5:15:0,15,194	0/0:22,0:22:54:0,54,733	0/0:29,0:29:57:0,57,794	0/1:4,6:10:99:148,0,1040/1:7,5:12:99:138,0,172	0/0:16,0:16:36:0,36,477	0/0:31,0:31:75:0,75,999	0/0:21,0:21:48:0,48,652	0/0:30,0:30:72:0,72,978	0/0:3,0:3:6:0,6,76	0/0:32,0:33:75:0,75,1009	0/0:16,0:16:39:0,39,531	0/0:26,0:26:57:0,57,790	0/0:27,0:27:54:0,54,755	0/0:22,0:22:48:0,48,657	0/0:13,0:13:36:0,36,487	0/0:12,0:12:36:0,36,5050/0:10,0:10:27:0,27,378	0/0:10,0:10:27:0,27,383	0/0:20,0:20:45:0,45,608	0/0:18,0:18:39:0,39,544	0/0:17,0:17:33:0,33,469	0/0:31,0:31:66:0,66,923	0/0:14,0:14:27:0,27,384	0/0:26,0:26:60:0,60,809	0/0:47,0:48:99:0,105,1428	0/0:42,0:42:87:0,87,1214	0/0:33,0:33:75:0,75,1021	0/0:38,0:38:90:0,90,1223	0/0:14,0:14:36:0,36,473	0/0:52,0:52:99:0,102,1417	0/0:3,0:3:9:0,9,120	0/0:24,0:24:57:0,57,781	0/0:39,0:39:75:0,75,1048	0/0:23,0:23:51:0,51,7000/0:30,0:30:60:0,60,837	0/0:15,0:15:42:0,42,571	0/0:14,0:14:39:0,39,539	0/0:80,0:80:99:0,160,2217	0/0:24,0:24:48:0,48,669	0/0:28,0:28:63:0,63,870	0/0:32,0:32:78:0,78,1040	0/0:26,0:26:60:0,60,800	0/0:31,0:31:69:0,69,952	0/0:28,0:28:66:0,66,901	0/0:33,0:33:72:0,72,971	0/0:21,0:21:42:0,42,593	0/0:28,0:28:69:0,69,936	0/0:29,0:29:60:0,60,825	0/0:21,0:21:48:0,48,652	0/0:22,0:22:51:0,51,6950/0:19,0:19:39:0,39,546	0/0:27,0:27:60:0,60,811)
java.io.IOException: Variants are not ordered on sequence dictionary ([VC Unknown @ ACAexon1PhgSARMA101:117 Q230.02 of type=SNP alleles=[C*, T] attr={} GT=GT:AD:DP:GQ:PL	0/0:14,0:14:36:0,36,495	0/0:19,0:19:54:0,54,763	0/0:14,0:14:36:0,36,510	0/0:14,0:14:42:0,42,582	0/0:21,0:21:57:0,57,774	0/0:10,0:10:27:0,27,3830/0:15,0:15:45:0,45,614	0/0:34,0:34:66:0,66,924	0/0:47,0:47:99:0,111,1496	0/0:30,0:30:69:0,69,950	0/0:19,0:19:39:0,39,546	0/0:17,0:17:36:0,36,504	0/0:5,0:5:15:0,15,194	0/0:22,0:22:54:0,54,733	0/0:29,0:29:57:0,57,794	0/1:4,6:10:99:148,0,104	0/1:7,5:12:99:138,0,172	0/0:16,0:16:36:0,36,477	0/0:31,0:31:75:0,75,9990/0:21,0:21:48:0,48,652	0/0:30,0:30:72:0,72,978	0/0:3,0:3:6:0,6,76	0/0:32,0:33:75:0,75,1009	0/0:16,0:16:39:0,39,531	0/0:26,0:26:57:0,57,790	0/0:27,0:27:54:0,54,755	0/0:22,0:22:48:0,48,657	0/0:13,0:13:36:0,36,487	0/0:12,0:12:36:0,36,505	0/0:10,0:10:27:0,27,378	0/0:10,0:10:27:0,27,383	0/0:20,0:20:45:0,45,6080/0:18,0:18:39:0,39,544	0/0:17,0:17:33:0,33,469	0/0:31,0:31:66:0,66,923	0/0:14,0:14:27:0,27,384	0/0:26,0:26:60:0,60,809	0/0:47,0:48:99:0,105,1428	0/0:42,0:42:87:0,87,1214	0/0:33,0:33:75:0,75,1021	0/0:38,0:38:90:0,90,12230/0:14,0:14:36:0,36,473	0/0:52,0:52:99:0,102,1417	0/0:3,0:3:9:0,9,120	0/0:24,0:24:57:0,57,781	0/0:39,0:39:75:0,75,1048	0/0:23,0:23:51:0,51,7000/0:30,0:30:60:0,60,837	0/0:15,0:15:42:0,42,571	0/0:14,0:14:39:0,39,539	0/0:80,0:80:99:0,160,2217	0/0:24,0:24:48:0,48,669	0/0:28,0:28:63:0,63,870	0/0:32,0:32:78:0,78,1040	0/0:26,0:26:60:0,60,800	0/0:31,0:31:69:0,69,952	0/0:28,0:28:66:0,66,901	0/0:33,0:33:72:0,72,971	0/0:21,0:21:42:0,42,593	0/0:28,0:28:69:0,69,936	0/0:29,0:29:60:0,60,825	0/0:21,0:21:48:0,48,652	0/0:22,0:22:51:0,51,6950/0:19,0:19:39:0,39,546	0/0:27,0:27:60:0,60,811)
	at com.github.lindenb.jvarkit.tools.misc.VcfToBam.run(VcfToBam.java:189)
	at com.github.lindenb.jvarkit.tools.misc.VcfToBam.doWork(VcfToBam.java:396)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:1155)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:1341)
	at com.github.lindenb.jvarkit.tools.misc.VcfToBam.main(VcfToBam.java:414)
[INFO][Launcher]vcf2bam Exited with failure (-1)

**Comment by lindenb** [comment]
can you please show me the output of

```
cut -f 1 your.ref.fa
```
and the output of 

```
grep -v "#" your.vcf | cut -f 1 | uniq
```

**Comment by TiagoSousaNeves** [comment]
`cut -f 1 your.ref.fa`

>ACAexon1PhgSARMA101
GCAGCAGCAGCAGCAGCAGCAGCATGGACATTACCATCCAGCACCCCTGGTTCAAGCGTGCCCTGGGACCCCTCATTCCAAGCCGTTTGTTCGACCAGTTTTTTGGAGAGGGTCTCCTCGAGTATGACCTCCTGCCTTTGTTCTCGTCCACTATCAGCCCCTACTACAGGCAGTCCCTCTTCCGCAGCGTGCTGGAGTCAGGCATTTCAGAGGTAAGGGCCCTTTGATTTCCTCTCCCTTCCCTTCCTCTCCCTCCTGATGCCTCCAGCCGCTCCTCTGCACCCACATCTCACACTGGTGTAGCCCCGT
>ACAexon2PhgMPDS1153
GTCCCTGGGTCCCCACAATGGGAAGAAGAGCCCTGCTGAGGCCCATAGTCACAGAAGGACAAAGTGCCAGACCACCCCATTTTTGGCCTTTAATCTGTGGTGGTGCTGGCACTGCCTCCACACGGGCCTCACTGTGTGACAATGCTCCTTTCAGGTGAGGTCCGATCGGGACAAGTTCACAATCATGCTGGATGTAAAACACTTCTCTCCTGAAGACTTGAGTGTGAAGATTATTGATGACTTTGTGGAAATCCATGGCAAGCACAGTGAAAGGCAGGTAAGTGGAAGTGATGGTGATGGTGGAGCAGCTGGGGAGTCCAGCTCCGTTTCCCTTCTTTCCAACGGTTCTCAGCTGAAGGAAAAAAAAAAGAATATATCAGAAGAAGGAGTTAATTATGAATTGTCATTATTGGCATGGCCTGTTCCCATAGAGCCCCCACCTGATATCTGACAATAACAA
>ARNTLexon12PhgAMANA102
TGTGCCAAACACTGATTATCTTCAACTTGCATGGGTTTGTAGGGAACATTTGAGGTTCAGGATGGGTGAGGGAGGAATAGCATTTTTCTTGAGGGATGTGGGGAGGGATTAACTGGGTTTTCCCTGACAAGGGCTCTGTTGATGTTGTGGTGCCTGCTTGACACGAATGACTTGCTTTCTGCCTGTTTTCAGTTTTGCAGACAAGAGAAAAAATTACAACTAACTGCTACAAGTTTAAAATAAAAGATGGCTCTTTTATTACGTTGCGGAGTCGCTGGTTCAGTTTCATGAACCCTTGGACCAAAGAAGTAGAATACATTGTCTCCACAAACACCGTGGTTTCGTAAGTGCCTGGGAATGCCCAGTGCTTTGCCCTTTTCTCATGGCATGAGATTTGACCTAAATATGTGCACACCTTCTGTATGACAGTAGGTGTCTTCTCCAGATAACACCCCAGGGAGAGGAGCTTTAGTTTAACAATTGCAGTAATTTAATTTCTGGTTGTTAAACCTTGAAGGAAATAGAAATATTTTCTTTCTT
>ARNTLexon13PhgGUR235
CACTGCAACCCATGACATAGGGTTTTCTCTCACTGATTTTCCTAATCCTTGCACTCCACAGCACCACGGTCCTGGACAGTGGGGACACGGCCTTTCCCCAGCTGGCAGCGTCCCCACACAGCATGGACAGCGTGCTCCAGGCTGGAGAAGGTAACTCCTGTGCTCAGGGAATCACTGGCTGCTGTGCCTTGGGAGCAGCTCACCCTGCCTGCACACATTGGCTGCCCTTCTGCACTGAGATG
>BDNFexonPhgAMANA102
TGGTTTTAACAGTTCCACCAAGTGAGAAGAGTGATGACCATCCTTTTCTTTACTATGGTTATCTCATACTTCACTTGCATGAAAGCTGCCCCGATGAAAGAAGCTAGTCTAAGAGCACAAGGCAGCTTGGCTTACCCAGGTCTTCGGACCCACGGGACTCTTGAGAGCATAAATGGGCCCAATGCTGGTTCAAGAGGACTGACATCATTGGCAGATACTTTTGAACATGTCATAGAGGAGCTTCTAGACGAGGACCAGGACATCCAGCCCAGTGAGGGAAACAAGGATGCAGACTTGTATACATCCCGAGTCATGCTAAGCAGTCAAGTGCCTTTGGAACCCCCACTGCTCTTTCTGCTTGAGGAATACAAAAACTACTTGGATGCTGCAAACATGTCCATGAGAGTCCGGCGCCACTCTGATCCAGCTCGCCGTGGGGAACTGAGCGTGTGTGACAGCACGAGCGAGTGGGTGACAGCAGCAGAGAAAAAGACTGCAGTGGACATGTCTGGGGCAACTGTCACAGTCCTGGAGAAAGTTCCAGTACCCAAAGGCCAACTGAAGCAATACTTCTATGAGACCAAATGCAACCCTAAGGGGTACACGAAGGAGGGCTGCAGGGGCATTGACAAGAGGCACTGGAACTCACAGTGCCGAACTACCCAGTCTTACGTGAGAGCTCTCACCATGGATAATAAAAAGAGAGTTGGCTGGCGCTTTATAAGGATAGACACTTCCTGTGTATGTACATTAACCATTAAAAGGGGAAGATAGTGGGTTCATGTTGTATAGATTATATTGAGACAAATATCTATTTGTATATATACATAACAGGGTAAATTATTCGGTAAAAAATAATTTTATGGACTGCATGTATG
>CALB1exon11PhgMPDS1153
CACATGGCCATCATATGGATGCCATACAAATATATAAAAACATTTTAGTGTGTTACTGTCAGACAGGCTGAGAATACCTGGGATTTTTTTCTCATTTCCTGCCATTGGAAGTAAACTTGTTCATGCTGATAACTAAACAGGATTATAAAGCCTTATCTGTTCTTTAAATAGGAATTAGACATTACCAACCTTGCAACATACAAGAAAAGCATCATGGCCTTGTCTGATGGAGGAAAGCTTTACCGAGCAGAACTGGCTCTTATTCTCTGTGCTGAGGAAAACTAGAGCTCTTCTATCATGTCCACTTAACTAGTGATGTACTCTACACAATAACTGTGCACTATAAGGGAGTAGGCTGTATTTTTAAACTGCATATAGAAAATTAGCCAGGATGTGTGGCACATTCCTTTCAGTTTGTTTCTATACTGTTTGTAATGTACAGTTTTTGTAACAATAA
>CHCexon4PhgAMANA102
AAGCAGCATTCAAAAGTAGCATGTTCTTATCTGTGGAGGAAATATCCATATATTTTAACTGCTTTTCAAGCTCTTCATTCTGCTGTGATAGTACTGAAGTAAAAATAAAACAGCACTTCTGGCTGTCCTGAAATGGCCCAGCTGTTTGCTGAGTCTCAAAAGCACCAGCTCATTTATCCGGTGCCAAATCTGAGGAATCTATTTCTGTTTTGCAGATCAGTGACAAGCACGATGTGGTGTTCCTCATAACAAAATATGGCTACATCCACTTGTATGACCTGGAAACTGGCACCTGTATCTACATGAACAGGATCAGTGGAGAGACCATTTTTGTTACTGCACAGCACGAAGCAACAGCTGGAATTATTGGAGTCAACAGAAAGGGACAAGTAAGGAAACTTGGCCTGGGAGCCACTTCTTTATCTAATCCCACTGGCTCTTCATGATACACTGCAGGGCTCATATCTATGTCTCAAATTTTCCAGGAATGTTCACTTTGAACTCTGCCCACAACGTGTGAGGTCTGACAGTGTTGTGAGCCACAAAATAAATTTGCTGTTCTATCTCCATACACATCTAACTTAGCTACTTTAAGCAAGTTACTAATA
>CHCexon5PhgAGUAFTO058
AATACCTTAATTAAACTGTTAATTGCCTGCTTTGATGCAGGCAGTGGATGACATTGGCTCTTTCTAACCAGAGGTCTCTTTAATAACATGACAAGTAGGAGGGATGAAAAACTTCCTGTGAATACCATAACTTTCCTCTTAGAAAGGCTCACTTTGGCTGAGTTTTGATATTTGGACTAACTGGAGGTTTGCCCTGGTGGTTTATTCAGGTGCTCTCAGTGTGTGTGGAAGAGGAGAACATCATTCCCTACATCACAAACGTGCTGCAGAATCCTGACCTGGCTTTACGGATGGCTGTCCGCAACAACCTGGCGGGGGCCGAGGAGCTCTTTGCCAGGAAATTCAATGCACTCTTTGCACAAGGGAACTATTCAGAGGCAGCAAAAGTGGCAGCTAATGCCCCAAAGGTAAAGTGTTCAGAACAGCACTGAACTCTACTGGCTTCAGCTTCTTGCTTCAGGAAAGCTCAGTGAATTTTTTCTCTTGTCCCAAGGTGGTACTTTGGTGCTGGGTGCTGACACTGATTGCAGGCTGGATGATATTAGAGTTTGTAAAGCCCACAGAGGAGGGGAGGAATAAATGATGAAGTAGTGGCTTTAATTCATAATATGTCTGGTACTCATCTTT
........

`grep -v "#" your.vcf | cut -f 1 | uniq`

ACAexon1PhgSARMA101
ACAexon2PhgMPDS1153
ARNTLexon12PhgAMANA102
BDNFexonPhgAMANA102
CALB1exon11PhgMPDS1153
CHCexon4PhgAMANA102
CHCexon5PhgAGUAFTO058
CHCexon6PhgUFAC1083
CLKexon21PhgGAPTO264
CLOCKexon6PhgGAPTO264
CLOCKexon7PhgAGUAFTO058
......

**Comment by lindenb** [comment]
sorry, my bad, I wanted

```
cut -f 1 your.ref.fa.fai
```

and "`cat ref.dict`"  please

**Comment by lindenb** [comment]
and the output of

`grep $'ACAexon1PhgSARMA101\t117' -A1 -B1 your.vcf | cut -f 1,2,4,5`

please

**Comment by TiagoSousaNeves** [comment]
Sure, here they are:

`cut -f 1 ..../SNPs/longest_uces_semZ.fasta.fai' 
ACAexon1PhgSARMA101
ACAexon2PhgMPDS1153
ARNTLexon12PhgAMANA102
ARNTLexon13PhgGUR235
BDNFexonPhgAMANA102
CALB1exon11PhgMPDS1153`

`cat  '..../SNPs/longest_uces_semZ.fasta.dict' 
@HD	VN:1.5
@SQ	SN:ACAexon1PhgSARMA101	LN:309	M5:8b754971affd278122c56079aa00686c	UR:file:/media/tsn/Documentos/Tiago/UCEs_Tiago/1_FINALISSIMO_Tiago_Workstation_AMNH/Pheugopedius/SNPs/longest_uces_semZ.fasta
@SQ	SN:ACAexon2PhgMPDS1153	LN:460	M5:9f7656caae35268bb6c018e71edbb91f	UR:file:/media/tsn/Documentos/Tiago/UCEs_Tiago/1_FINALISSIMO_Tiago_Workstation_AMNH/Pheugopedius/SNPs/longest_uces_semZ.fasta
@SQ	SN:ARNTLexon12PhgAMANA102	LN:540	M5:527f7a783ce8e36416ba03cf01770c4a	UR:file:/media/tsn/Documentos/Tiago/UCEs_Tiago/1_FINALISSIMO_Tiago_Workstation_AMNH/Pheugopedius/SNPs/longest_uces_semZ.fasta
@SQ	SN:ARNTLexon13PhgGUR235	LN:242	M5:2518cf757f3af9fd6f16d39e9c152ab8	UR:file:/media/tsn/Documentos/Tiago/UCEs_Tiago/1_FINALISSIMO_Tiago_Workstation_AMNH/Pheugopedius/SNPs/longest_uces_semZ.fasta
@SQ	SN:BDNFexonPhgAMANA102	LN:878	M5:87c57b7fefd1cc4404b67a71208fa4bb	UR:file:/media/tsn/Documentos/Tiago/UCEs_Tiago/1_FINALISSIMO_Tiago_Workstation_AMNH/Pheugopedius/SNPs/longest_uces_semZ.fasta`

`grep $'ACAexon1PhgSARMA101\t117' -A1 -B1 '.../No_OUT/1SNPlocus_Pheugopedius-only-PASS-Q30-SNPs_maf0.014925373.vcf' | cut -f 1,2,4,5
#CHROM	POS	REF	ALT
ACAexon1PhgSARMA101	117	C	T
ACAexon2PhgMPDS1153	79	A	C`

**Comment by lindenb** [comment]
hum.. I'm puzzled for this one. Can you send the vcf and the ref fasta please ?

`plindenbaum  yahoo  fr`

**Comment by TiagoSousaNeves** [comment]
I already uploaded them in the first comment!

What is the code that you posted?

**Comment by lindenb** [comment]
> I already uploaded them in the first comment!

opssss, I'll check

**Comment by lindenb** [comment]
Sorry, I didn't see your attachement; :-(

my bug is that I 'm expecting a variant for each REF sequence.
It's fixed now. Thanks for pointing this bug.



$ java -jar dist/vcf2bam.jar -R /home/lindenb/tmp/longest_uces_semZ.fa ~/tmp/1SNPlocus_Pheugopedius-only-PASS-Q30-SNPs_maf0.014925373.vcf  

```
@HD	VN:1.5	SO:unsorted
(...)
0000000001	67	BDNFexonPhgAMANA102	1	60	100=	=	501	500	TGGTTTTAACAGTTCCACCAAGTGAGAAGAGTGATGACCATCCTTTTCTTTACTATGGTTATCTCATACTTCACTTGCATGAAAGCTGCCCCGATGAAAG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	RG:Z:Ph_c95505	NM:i:0
0000000001	147	BDNFexonPhgAMANA102	501	60	100=	=	1	-500	GGACATGTCTGGGGCAACTGTCACAGTCCTGGAGAAAGTTCCAGTACCCAAAGGCCAACTGAAGCAATACTTCTATGAGACCAAATGCAACCCTAAGGGG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	RG:Z:Ph_c95505	NM:i:0
0000000002	67	BDNFexonPhgAMANA102	1	60	100=	=	501	500	TGGTTTTAACAGTTCCACCAAGTGAGAAGAGTGATGACCATCCTTTTCTTTACTATGGTTATCTCATACTTCACTTGCATGAAAGCTGCCCCGATGAAAG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	RG:Z:Ph_c95505	NM:i:0
0000000002	147	BDNFexonPhgAMANA102	501	60	100=	=	1	-500	GGACATGTCTGGGGCAACTGTCACAGTCCTGGAGAAAGTTCCAGTACCCAAAGGCCAACTGAAGCAATACTTCTATGAGACCAAATGCAACCCTAAGGGG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	RG:Z:Ph_c95505	NM:i:0
0000000003	131	BDNFexonPhgAMANA102	1	60	100=	=	501	500	TGGTTTTAACAGTTCCACCAAGTGAGAAGAGTGATGACCATCCTTTTCTTTACTATGGTTATCTCATACTTCACTTGCATGAAAGCTGCCCCGATGAAAG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	RG:Z:Ph_c97221	NM:i:0
0000000003	83	BDNFexonPhgAMANA102	501	60	100=	=	1	-500	GGACATGTCTGGGGCAACTGTCACAGTCCTGGAGAAAGTTCCAGTACCCAAAGGCCAACTGAAGCAATACTTCTATGAGACCAAATGCAACCCTAAGGGG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	RG:Z:Ph_c97221	NM:i:0
0000000004	131	BDNFexonPhgAMANA102	1	60	100=	=	501	500	TGGTTTTAACAGTTCCACCAAGTGAGAAGAGTGATGACCATCCTTTTCTTTACTATGGTTATCTCATACTTCACTTGCATGAAAGCTGCCCCGATGAAAG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	RG:Z:Ph_c97221	NM:i:0
0000000004	83	BDNFexonPhgAMANA102	501	60	100=	=	1	-500	GGACATGTCTGGGGCAACTGTCACAGTCCTGGAGAAAGTTCCAGTACCCAAAGGCCAACTGAAGCAATACTTCTATGAGACCAAATGCAACCCTAAGGGG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	RG:Z:Ph_c97221	NM:i:0
```

**Comment by TiagoSousaNeves** [comment]
Perfect Pierre, thank you very much!

Best,

TSN
