### ISSUE TITLE
GC overhead limit exceeded with jvarkit vcfrenamechr

### ISSUE THREAD

**Issue by browngcm** [lindenb/jvarkit#87]
### Subject of the issue
I'm trying to use vcfrenamechr to rename the the Trinity headers in my VCF file to a naming format that is accepted by snpEff. My goal is to predict the effect of SNPs in my vcf file with snpEff. 

### Your environment
* version of jvarkit - latest version
* version of java - 1.8
* which OS - CentOS 6

### Steps to reproduce
```
/scratch/$USER/jvarkit/dist/vcfrenamechr /
-f /scratch/$USER/jvarkit/src/main/resources/chromnames/hg19_to_g1kv37.tsv /
-o SNPs_vcfrenamechr.vcf /scratch/$USER/interspecific_SNPs.vcf

```
### Expected behaviour
Rename Trinity headers to chromosomes

### Actual behaviour
[SEVERE][Launcher]GC overhead limit exceeded
[INFO][Launcher]vcfrenamechr Exited with failure (-1)

**Comment by lindenb** [comment]
Hum... I havent used this tool for years.... 
can you please try with a simple java cmd:

```
java -jar /scratch/$USER/jvarkit/dist/vcfrenamechr.jar \
-f /scratch/$USER/jvarkit/src/main/resources/chromnames/hg19_to_g1kv37.tsv \
>  SNPs_vcfrenamechr.vcf /scratch/$USER/interspecific_SNPs.vcf
```

or you could use vcfsetdict: http://lindenb.github.io/jvarkit/VcfSetSequenceDictionary.html

**Comment by MGCBrown** [comment]
Thanks!

It has been running for ~ 20 minutes but hasn't written anything to the output vcf file yet. Is that to be expected?

**Comment by lindenb** [comment]
> Is that to be expected?

of course not.

Can you please show the exact cmd line your have used ?

**Comment by MGCBrown** [comment]
java -jar /scratch/$USER/jvarkit/dist/vcfrenamechr.jar -f / /scratch/$USER/jvarkit/src/main/resources/chromnames/hg19_to_g1kv37.tsv >  SNPs.vcf / /scratch/$USER/SNPs/NFS_reference_to_SFS_alignment_interspecific_SNPs_PASS_var.flt.vcf

**Comment by lindenb** [comment]
opps I'm afraid I've done a typo in my previous comment....

**Comment by lindenb** [comment]
it should have been

```
java -jar /scratch/$USER/jvarkit/dist/vcfrenamechr.jar \
-f /scratch/$USER/jvarkit/src/main/resources/chromnames/hg19_to_g1kv37.tsv  \
    SNPs_vcfrenamechr.vcf > /scratch/$USER/interspecific_SNPs.vcf
```

sorry, you might have deleted your original VCF file.

**Comment by MGCBrown** [comment]
Forgive me if I'm wrong, but in the command you posted above my input vcf file (interspecific_SNPs.vcf) that I want edit is specified as the output file 'SNPs_vcfrenamechr.vcf > /scratch/$USER/interspecific_SNPs.vcf'

**Comment by MGCBrown** [comment]
Sorry I think that was my fault. 

With the command you provided, it deleted my vcf file because the input and output file were reversed. 
 
However, when I run the command the right way, it creates the output file but doesn't write anything to it.

**Comment by lindenb** [comment]
the current version works on my machine:

```
$ echo -e "ref\tCHANGEDref\nref2\tCHANGEDref2" > tmp.txt && java -jar dist/vcfrenamechr.jar   -m tmp.txt test/resources/toy.vcf.gz | cut -f 1 | grep CHANGED
##contig=<ID=CHANGEDref,length=45>
##contig=<ID=CHANGEDref2,length=40>
CHANGEDref
CHANGEDref
CHANGEDref2
CHANGEDref2
CHANGEDref2

```

is there any error message on your side ?

**Comment by MGCBrown** [comment]
No errors on my side. It's running but not writing anything. 

The variants in my vcf file have Trinity headings (TRINITY_DN1000|c115_g5_i1 len=247), so I'm not sure whether that is part of the problem. All I want to do is convert those Trinity headers to a format that is accepted by SNP annotation software such as snpEff. I haven't seen any examples from the literature where they successfully convert vcf headers so that the SNPs can be queried by snpEff. Many of these papers say that they wrote a "custom perl script" to predict the effect of SNPs (non-synonomous, synonomous). I've been looking for a solution to this problem for a long time but I still can't figure out a way to do that.

**Comment by lindenb** [comment]
can you please attach to this a few variant of your vcf (+ VCF header) as well as your mapping file.

**Comment by MGCBrown** [comment]
The variants in my vcf file are formatted like this:


TRINITY_DN192238_c0_g3_i5	4060	.	G	A	225	LowQual	DP=193;VDB=0.00378786;SGB=-0.693147;MQSB=5.0017e-18;MQ0F=0;AC=2;AN=2;DP4=0,0,61,89;MQ=36	GT:PL	1/1:255,255,0

How would I send you a sample of my mapping file? It's large.

**Comment by lindenb** [comment]
```
grep TRINITY_DN192238_c0_g3_i5 your_mapping.txt > minimapping.txt
 awk '/#/ {print;next;} {print; exit}' > mini.vcf
```

**Comment by lindenb** [comment]
attach  files minimapping.txt and mini.vcf by selecting them in your next comment area

**Comment by MGCBrown** [comment]
I've created the mini.vcf. Can I use the grep command on a .bam file and output to .txt or do I have to convert my mapping file from .bam to .txt first? Sorry, only a year of bioinformatics on under my belt; still much to learn.

**Comment by lindenb** [comment]
what is that bam ? vcfrenamechr doesn't use a bam!  It's a simple tab delimited file. http://lindenb.github.io/jvarkit/ConvertVcfChromosomes.html 

```
  * -f, --mapping, -m
      load a custom name mapping. Format (chrom-source\tchrom-dest\n)+
```

**Comment by MGCBrown** [comment]
Yes, yes I'm sorry about that. Got confused with terminology. Thanks for the tweet by the way.

**Comment by MGCBrown** [comment]
Thanks for the tweet, Pierre! I appreciate it.
