### ISSUE TITLE
issue running BLASTN2SNP

### ISSUE THREAD

**Issue by dhwnai2410** [lindenb/jvarkit#89]
## Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### Subject of the issue
unable to execute BLASTN2SNP
### Your environment
* version of jvarkit 
* version of java java 1.8
* the value of `${JAVA_HOME}`      bash: /usr/lib/jvm/java-8-oracle: Is a directory
* which OS  ubuntu 12.04

### Steps to reproduce
dhwani@dhwani-VirtualBox:~/Desktop/new_miseq_kmer/ref_seq$ java -jar ./jvarkit/dist/blastn2snp.jar res_blastn_out.xml 
[INFO][BlastNToSnp]Reading from res_blastn_out.xml
[SEVERE][BlastNToSnp]ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
	at com.sun.xml.internal.stream.XMLEventReaderImpl.peek(XMLEventReaderImpl.java:276)
	at com.github.lindenb.jvarkit.tools.blast.BlastNToSnp.peekIteration(BlastNToSnp.java:186)
	at com.github.lindenb.jvarkit.tools.blast.BlastNToSnp.run(BlastNToSnp.java:259)
	at com.github.lindenb.jvarkit.tools.blast.BlastNToSnp.doWork(BlastNToSnp.java:454)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:1164)
	at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:1322)
	at com.github.lindenb.jvarkit.tools.blast.BlastNToSnp.main(BlastNToSnp.java:474)
#query	hit	hit-index	hsp-index	query-POS	hit-POS	STRAND	REF(hit)	ALT(query)	blast.align_length	blast.hit.var	blast.query.varblast.mid.var
[INFO][Launcher]blastn2snp Exited with failure (-1)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by lindenb** [comment]
sorry for my late answer, I don't receive my mail from github for an unknow reason...

**Comment by lindenb** [comment]
I suppose there is an error with your res_blastn_out.xml

Try to **validate** your xml with xmllint ( http://xmlsoft.org/xmllint.html )
```
xmllint res_blastn_out.xml
```

or open res_blastn_out.xml as a file in firefox.

**Comment by dhwnai2410** [comment]
Hello Sir

That is the output generated from BLAST with option -m 8 , to generate the
result in XML format.

Regards
Dhwani

On Sun, Nov 19, 2017 at 6:13 PM, Pierre Lindenbaum <notifications@github.com

**Comment by lindenb** [comment]
> That is the output generated from BLAST with option -m 8 , to generate the result in XML format. 

ok, 

what is the output of 

```
xmllint res_blastn_out.xml
```

or can you open the xml file in firefox ?

**Comment by dhwnai2410** [comment]
This is the error

xmllint res_blastn_out.xml
res_blastn_out.xml:1: parser error : Start tag expected, '<' not found
read_1 HLA-A-Exon2 100.00 180 0 0 1 180 30 209 1e-103 357

**Comment by lindenb** [comment]
ok, so your  res_blastn_out.xml is not an XML file. It's a problem with the way your generated this file and it's not related to my software. closing.
