### ISSUE TITLE
Can't compile on Ubuntu 16.04.3 LTS w/ Oracle Java 9.0.1+11

### ISSUE THREAD

**Issue by JonN17** [lindenb/jvarkit#93]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java

### Subject of the issue
Describe your issue here.

trying to get bamstats04 to compile

### Your environment
* version of jvarkit - 
cloned 1/3/2018
* Java(TM) SE Runtime Environment (build 9.0.1+11)

* the value of `${JAVA_HOME}` 
/data/bioinformatics_software/oracleJava/jdk-9.0.1/bin/java
* which OS
Ubuntu 16.04.3 LTS
### Steps to reproduce
Tell us how to reproduce this issue. Please provide an example.
make bamstats04

### Expected behaviour
Tell us what should happen

it should compile

### Actual behaviour
Tell us what happens instead
it errors out 
==================
$ make bamstats04
mkdir -p /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/
echo "package com.github.lindenb.jvarkit.util.htsjdk;" > /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo '@javax.annotation.Generated("jvarkit")' >> /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo 'public class HtsjdkVersion{ private HtsjdkVersion(){}' >> /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo 'public static String getVersion() {return "2.13.0";}' >> /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo -n 'public static String getDate() {return "' >> /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java &&  date | tr -d '\n' >> /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java && echo ')";}' >> /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo 'public static String getHash() {return "2.13.0";}' >> /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo 'public static String getHome() {return "lib/com/github/samtools/htsjdk/2.13.0/htsjdk-2.13.0.jar";}' >> /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo 'public static String getJavadocUrl(final Class<?> clazz) {return "https://samtools.github.io/htsjdk/javadoc/htsjdk/"+clazz.getName().replaceAll("\\.","/")+".html";}' >> /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
echo '}'  >> /data/marketingGC_bias/jvarkit/src/main/generated-sources/java/com/github/lindenb/jvarkit/util/htsjdk/HtsjdkVersion.java
mkdir -p /data/marketingGC_bias/jvarkit/dist/
rm -rf "/data/marketingGC_bias/jvarkit/_tmp-2.13.0"
mkdir -p /data/marketingGC_bias/jvarkit/_tmp-2.13.0/META-INF/services
echo "com.github.lindenb.jvarkit.annotproc.JVarkitAnnotationProcessor" > /data/marketingGC_bias/jvarkit/_tmp-2.13.0/META-INF/services/javax.annotation.processing.Processor
echo '### Printing javac version : it should be Oracle 1.8 (NOT OpenJDK). if Not, check your $${PATH}.'
### Printing javac version : it should be Oracle 1.8 (NOT OpenJDK). if Not, check your $${PATH}.
javac -version
javac 9.0.1
#compile
javac -d /data/marketingGC_bias/jvarkit/_tmp-2.13.0 -sourcepath /data/marketingGC_bias/jvarkit/src/main/java:/data/marketingGC_bias/jvarkit/src/main/generated-sources/java /data/marketingGC_bias/jvarkit/src/main/java/com/github/lindenb/jvarkit/annotproc/JVarkitAnnotationProcessor.java
/data/marketingGC_bias/jvarkit/src/main/java/com/github/lindenb/semontology/Term.java:11: error: package javax.annotation is not visible
@javax.annotation.Generated(value="xslt",date="2017-04-06T09:53:14+02:00",comments="generated from https://github.com/lindenb/semontology")
      ^
  (package javax.annotation is declared in module java.xml.ws.annotation, which is not in the module graph)
1 error
Makefile:852: recipe for target '/data/marketingGC_bias/jvarkit/dist/annotproc.jar' failed

**Comment by lindenb** [comment]
you're using the new java 9. as stated in the documentation http://lindenb.github.io/jvarkit/BamStats04.html jvarkit must be compiled with java 8.

closing.
