### ISSUE TITLE
fixvcfmissinggenotypes filles in DP at wrong position

### ISSUE THREAD

**Issue by toedling** [lindenb/jvarkit#94]
I have a combined VCF file, combined from several filtered Mutect-output VCF files. While the
fixvcfmissinggenotypes.jar runs smoothly, it does fill in the observed read number at the wrong position. 
The one example line from a VCF file below after running the tool shows the issue.
The second sample (second-to-last column) is the sample with the mutation called, the first and third sample were filled in by the jar.
The genotype string in the example line indicates that DP should be the fourth-to-last number in each sample's string, and the third-to-last is supposed to FA (variant allele frequency). The jar seems to fill in DP, the total number of reads, at the third-to-last position in the place of FA. The correct entries should probably be exactly that number at the fourth-to-last position and "0.0" at the third-to-last position in each sample.

18	74208494	rs868449866	G	A	.	PASS	SOMATIC;VT=SNP	GT:AD:BQ:DP:FA:FXG:SS	0/0:.:.:63:.:1	0/1:36,3:35:39:0.077:.:2	0/0:.:.:34:.:1

**Comment by lindenb** [comment]
thans for the report, I don't usemuch  this tool . I'll check this . Can you please give me your command line and the output of `git rev-parse HEAD` ?

**Comment by lindenb** [comment]
here is a little cmd, can please please better explain what is wrong ? can you please post the original VCF line before applying my tool ?

```
$ paste <(echo "GT:AD:BQ:DP:FA:FXG:SS" | tr ":" "\n" ) <(echo "0/0:.:.:63:.:1"| tr ":" "\n") <(echo "0/1:36,3:35:39:0.077:.:2" | tr ":" "\n") <(echo "0/0:.:.:34:.:1" | tr ":" "\n")
GT	0/0	0/1	0/0
AD	.	36,3	.
BQ	.	35	.
DP	63	39	34
FA	.	0.077	.
FXG	1	.	1
SS		2	
```

**Comment by toedling** [comment]
Thanks for the quick response. Below is the original line from the VCF. The samples 1 and 3 in that file did not have the variant call, so for them there was no info. 

`18	74208494	rs868449866	G	A	.	PASS	SOMATIC;VT=SNP  GT:AD:BQ:DP:FA:SS	./.:.:.:.:.:.	0/1:36,3:35:39:0.077:2	./.:.:.:.:.:.`


Your tool filled in the Genotype and resulted in the line in my previous post. So I think it does look up the read number (DP) in each sample and fills it in, it just puts it at the wrong position. Each entry should have the format
`GT  :  AD  : BQ : DP : FA  : FXG  :  SS`
`0/1 : 36,3: 35 : 39 : 0.077 : . : 2   # previous sample with values`
`0/0 :       .       :    .   :  63  :    .      :  1     # new sample filled in by script`

So the filled-in sample has only six values, with FA, the variant allele frequency, apparently missing, while the original one now has seven values. 

For the version, I cloned it from Github yesterday,

**Comment by lindenb** [comment]
old VCF values:

```
GT	./.	0/1	./.
AD	.	36,3	.
BQ	.	35	.
DP	.	39	.
FA	.	0.077	.
SS	.	2	.
```

new 'fixed' values: 

```
GT	0/0	0/1	0/0
AD	.	36,3	.
BQ	.	35	.
DP	63	39	34
FA	.	0.077	.
FXG	1	.	1
SS		2	
```

I see both DP (63 and 34) have been filled and the Genotypes are set (0/0). This is what my program is supposed to do. There are some trailing values missing( for SS)  but unless I'm wrong I don't think it's a problem according to the VCF specification.

**Comment by toedling** [comment]
OK, I was not aware that you can just drop parts of the genotype string, but then the tool is working fine. Since I actually need the variant allele frequency for all samples, even it is 0.0 or very close to 0, I need to look for another tool and I think I just found a way to get that information with "samtools mpileup" followed by "bcftools call". Thanks for your efforts.
