### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 145

### ISSUE THREAD

**Issue by Babita004** [lindenb/jvarkit#95]
Hello,
I have used biostar214299 software for allele-specific reads. I have got following error:

[INFO][SAMSequenceDictionaryProgress]Count: 388874 Elapsed: 10 seconds(4.40%) Remains: 3 minutes(95.60%) Last: 1:5236879
[INFO][SAMSequenceDictionaryProgress]Count: 776211 Elapsed: 20 seconds(9.13%) Remains: 3 minutes(90.87%) Last: 1:10878579
[INFO][SAMSequenceDictionaryProgress]Count: 1177813 Elapsed: 30 seconds(13.53%) Remains: 3 minutes(86.47%) Last: 1:16117926
[INFO][SAMSequenceDictionaryProgress]Count: 1594904 Elapsed: 40 seconds(18.50%) Remains: 2 minutes(81.50%) Last: 1:22046185
[INFO][SAMSequenceDictionaryProgress]Count: 2019950 Elapsed: 50 seconds(24.38%) Remains: 2 minutes(75.62%) Last: 1:29042410
[INFO][SAMSequenceDictionaryProgress]Count: 2430899 Elapsed: 1 minute(1.88%) Remains: 52 minutes(98.12%) Last: 2:2234787
[INFO][SAMSequenceDictionaryProgress]Count: 2892174 Elapsed: 1 minute(2.89%) Remains: 39 minutes(97.11%) Last: 2:3439340
[SEVERE][Biostar214299]145
java.lang.ArrayIndexOutOfBoundsException: 145
    at com.github.lindenb.jvarkit.tools.biostar.Biostar214299.doWork(Biostar214299.java:297)
    at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMain(Launcher.java:1183)
    at com.github.lindenb.jvarkit.util.jcommander.Launcher.instanceMainWithExit(Launcher.java:1341)
    at com.github.lindenb.jvarkit.tools.biostar.Biostar214299.main(Biostar214299.java:338)
[INFO][Launcher]biostar214299 Exited with failure (-1)

Can you please give me any suggestions why this error come and how I can solve this problem.

Best
Vigyasa

**Comment by lindenb** [comment]
thanks for the report , it seems that it happens when the read is clipped. Give me a few minutes to update the code please.

**Comment by lindenb** [comment]
I've changed things. I'm about to leave my lab, can you please test this again on your side. thanks.

**Comment by Babita004** [comment]
Thank you so much for your prompt reply and help. Its working.


Best
