### ISSUE TITLE
(*Not a bug*) msa2vcf - Projection of coordinates for a reference?

### ISSUE THREAD

**Issue by LovellHAGSC** [lindenb/jvarkit#98]
Hi Pierre, 
I appreciate your work on the problem of extracting variants from multiple sequence alignments. 

I'm trying to annotate variants out of my multiple sequence alignment ... no problem getting the vcf (thanks!), but I'm having issues converting the coordinate system of the vcf to that of the reference sequences (which has the annotation). Basically, I want to: **adjust the positions of the vcfs based on the number of inserted / deleted bases upstream, using a specified sequence as the reference.** 

Do you have any tools to do this? Figured I'd ask before writing a script myself. 
Cheers,
John

**Comment by lindenb** [comment]
Hi @LovellHAGSC 
I'm sorry I don't use much this tool and there is currently no existing script to convert the position :-S

P.

**Comment by lindenb** [comment]
BTW you'd better use : use https://github.com/sanger-pathogens/snp_sites

**Comment by LovellHAGSC** [comment]
Thanks - figured as much ... 
Isn't `/snp_sites` just for snps? SNPs are easy to annotate - its the indels that make things difficult.

**Comment by lindenb** [comment]
honestly I've never tried snp_sites but the paper said it was better :-D.
Closing.
