### ISSUE TITLE
Parsing error when double allele in alt

### ISSUE THREAD

**Issue by jgarces02** [lindenb/jvarkit#99]
Hi @lindenb, 

First of all, thanks for this useful toolkit! I'm running vcfpolix.py with a snp.vcf and I get the following error because there are two alelles in alternative allele column... 
 `The provided VCF file is malformed at approximately line number 434: unparsable vcf record with allele A/G, for input source: /mnt/beegfs/jgarces/projects/exomes_test/results/3_variantCalling/tmp/1.vcf`

The vcf's row would be like this:
`chr1    10490111        .       T       A/G       .       PASS    AF=0.7143;DP=25;GPV=1.0983378999005645E-7;SPV=0.606864988558352;SS=1;SSC=2`

Is there any solution for this problem? Thanks in advance!

**Comment by lindenb** [comment]
Hi, what is  vcfpolix.py ? how does it relate to my package ?

**Comment by lindenb** [comment]
>>  unparsable vcf record with allele A/G,

> The vcf's row would be like this:

there is no A/G in your line.

**Comment by jgarces02** [comment]
Sorry, vcfpolyx...

**Comment by lindenb** [comment]
what is the version of the VCF header ? try to narrow the error by dividing the VCF.  I suspect your VCF is malformed and this is not related to my tool. Isn't there a stack trace in the error ?

**Comment by lindenb** [comment]
what generated this VCF ? There is only one value of AF while there are two ALT alleles...

**Comment by lindenb** [comment]
got it: the spec says https://samtools.github.io/hts-specs/VCFv4.2.pdf

> Comma separated list of alternate non-reference alleles. 

 it should be

` T A,G . `

not

` T A/G . `

closing.

**Comment by jgarces02** [comment]
You're right, it seems there's an error in the VCF generation. Thanks a lot!
